<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0;netstandard2.1;net8.0</TargetFrameworks>
    <RootNamespace>ProtoBuf.MessagePipes</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <AssemblyName>protobuf-net.MessagePipes</AssemblyName>
    <Title>protobuf-net.MessagePipes</Title>
    <Description>Provides a simple message-pipe using protobuf payloads</Description>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pipelines.Sockets.Unofficial" />
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.1'))">
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">
    <PackageReference Include="System.Threading.Channels" />
    <PackageReference Include="System.IO.Pipelines" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\protobuf-net.Core\protobuf-net.Core.csproj" />
  </ItemGroup>
  <ItemGroup Label="public API tracking">
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="all" />
    <!-- APIs for all target frameworks -->
    <AdditionalFiles Include="PublicAPI/PublicAPI.*.txt" />
    <!-- progressively additive APIs in later frameworks; each folder is effectively NET_X_Y_OR_GREATER -->
    <AdditionalFiles Include="PublicAPI/netstandard2.1/PublicAPI.*.txt" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.1'))" />
    <AdditionalFiles Include="PublicAPI/net8.0/PublicAPI.*.txt" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))" />
    <!-- net4x-only surface (e.g. persist-to-dll) -->
    <AdditionalFiles Include="PublicAPI/net462/PublicAPI.*.txt" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net462'))" />
  </ItemGroup>
</Project>
