<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0;net8.0</TargetFrameworks>
    <RootNamespace>ProtoBuf.FSharp</RootNamespace>
    <Title>protobuf-net.FSharp</Title>
    <Description>F# collection support for protobuf-net: serializes list, Map and Set</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\protobuf-net.Core\protobuf-net.Core.csproj" />
  </ItemGroup>
  <PropertyGroup Label="package validation">
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageValidationBaselineVersion>$(ProtoBufPackageBaseline)</PackageValidationBaselineVersion>
  </PropertyGroup>
</Project>
