#nullable enable
using ProtoBuf.BuildTools.Internal.Grpc;
using System.Collections.Generic;
using System.Text;

namespace ProtoBuf.BuildTools.Generators
{
    public sealed partial class GrpcProxyGenerator
    {
        /// <summary>
        /// The interceptors for one model: a single generic method carrying one
        /// <c>[InterceptsLocation]</c> per call site it takes over.
        /// </summary>
        /// <remarks>
        /// <para>
        /// One method per <em>receiver overload</em>, not per contract - the interceptor may be generic,
        /// which was checked rather than assumed (see <c>docs/aot-grpc.md</c>). That is why nothing here
        /// needs a per-contract name, and why the body is the same text for every consumer.
        /// </para>
        /// <para>
        /// The body is the runtime overload's own, with our factory in place of the reflective default:
        /// <c>(clientFactory ?? Model.Instance).CreateClient&lt;TService&gt;(client)</c>. The null check is
        /// real rather than decorative - the matcher only takes call sites that pass no factory, so it can
        /// never fire today, but it makes "silently discard a factory the consumer configured" impossible
        /// rather than merely unlikely.
        /// </para>
        /// <para>
        /// The attribute is declared here too, <c>file</c>-scoped, because it is not in any BCL - the same
        /// thing DapperAOT does. <c>file</c> keeps it from colliding with another generator's copy in the
        /// same assembly.
        /// </para>
        /// </remarks>
        private static string EmitInterceptors(string modelFullName, string hintTypeName,
            List<GrpcInterceptSite> sites)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace System.Runtime.CompilerServices");
            sb.AppendLine("{");
            Line(sb, 1, "[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
            Line(sb, 1, "file sealed class InterceptsLocationAttribute : global::System.Attribute");
            Line(sb, 1, "{");
            Line(sb, 2, "public InterceptsLocationAttribute(int version, string data) { }");
            Line(sb, 1, "}");
            sb.AppendLine("}");
            sb.AppendLine();

            sb.Append("namespace ").AppendLine(InterceptorSupport.Namespace);
            sb.AppendLine("{");
            Line(sb, 1, GeneratedCodeAttribute);
            Line(sb, 1, $"internal static class {hintTypeName}Interceptors");
            Line(sb, 1, "{");

            var first = true;
            foreach (var receiver in new[] { GrpcReceiverKind.CallInvoker, GrpcReceiverKind.ChannelBase })
            {
                var forThisReceiver = sites.FindAll(x => x.Receiver == receiver);
                if (forThisReceiver.Count == 0) continue;

                if (!first) sb.AppendLine();
                first = false;

                EmitOneInterceptor(sb, 2, modelFullName, receiver, forThisReceiver);
            }

            Line(sb, 1, "}");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void EmitOneInterceptor(StringBuilder sb, int indent, string modelFullName,
            GrpcReceiverKind receiver, List<GrpcInterceptSite> sites)
        {
            var receiverType = receiver == GrpcReceiverKind.CallInvoker
                ? "global::Grpc.Core.CallInvoker"
                : "global::Grpc.Core.ChannelBase";

            Line(sb, indent, "/// <summary>");
            Line(sb, indent, $"/// Replaces {sites.Count} call site(s) of "
                + $"<c>CreateGrpcService&lt;TService&gt;</c> on <c>{receiverType.Substring("global::".Length)}</c>,");
            Line(sb, indent, $"/// pointing them at <c>{modelFullName.Substring("global::".Length)}</c> "
                + "instead of the reflective default.");
            Line(sb, indent, "/// </summary>");

            foreach (var site in sites)
            {
                Line(sb, indent, "[global::System.Runtime.CompilerServices.InterceptsLocation("
                    + $"{site.LocationVersion}, {Literal(site.LocationData)})]");
            }

            Line(sb, indent, "public static TService CreateGrpcService<TService>(");
            Line(sb, indent + 1, $"this {receiverType} client,");
            Line(sb, indent + 1, $"{ClientFactoryFullName}? clientFactory = null)");
            Line(sb, indent + 1, "where TService : class");
            Line(sb, indent + 1, receiver == GrpcReceiverKind.CallInvoker
                ? $"=> (clientFactory ?? {modelFullName}.Instance).CreateClient<TService>(client);"
                : $"=> (clientFactory ?? {modelFullName}.Instance).CreateClient<TService>(client.CreateCallInvoker());");
        }

        private const string ClientFactoryFullName = "global::ProtoBuf.Grpc.Configuration.ClientFactory";
    }
}
