#nullable enable
using ProtoBuf.BuildTools.Internal.Grpc;
using System;
using System.Collections.Generic;
using System.Text;

namespace ProtoBuf.BuildTools.Generators
{
    public sealed partial class GrpcProxyGenerator
    {
        // the runtime surface the emitted code binds to; all of it is public API on protobuf-net.Grpc,
        // so generated code never needs InternalsVisibleTo
        private const string EmptyTypeName = "global::ProtoBuf.Grpc.Internal.Empty";
        private const string ReshapeTypeName = "global::ProtoBuf.Grpc.Internal.Reshape";
        private const string RegistryTypeName = "global::ProtoBuf.Grpc.Internal.GeneratedProxyRegistry";
        private const string BinderConfigurationTypeName = "global::ProtoBuf.Grpc.Configuration.BinderConfiguration";
        private const string CallContextTypeName = "global::ProtoBuf.Grpc.CallContext";
        private const string ServerMethodBinderTypeName = "global::ProtoBuf.Grpc.Configuration.IServerMethodBinder";
        private const string GeneratedNamespace = "ProtoBuf.Grpc.Generated";
        private const string GeneratedCodeAttribute = "[global::System.CodeDom.Compiler.GeneratedCode(\"protobuf-net.BuildTools\", \"1.0\")]";

        /// <summary>
        /// Emit the client proxy, the server bindings, and the module initializer that registers both.
        /// </summary>
        private static string Emit(GrpcInterfaceModel contract)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS0618 // ProtoBuf.Grpc.Internal.Reshape is intentionally obsoleted for direct consumption");
            sb.AppendLine();
            sb.Append("namespace ").AppendLine(GeneratedNamespace);
            sb.AppendLine("{");

            EmitClientProxy(sb, contract);
            sb.AppendLine();
            EmitServerBindings(sb, contract);
            sb.AppendLine();
            EmitModuleInitializer(sb, contract);

            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>
        /// A <c>[ModuleInitializer]</c> per contract, so that consumption is a static reference graph
        /// the trimmer and the AOT compiler can both see; nothing looks up attributes at runtime.
        /// </summary>
        private static void EmitModuleInitializer(StringBuilder sb, GrpcInterfaceModel contract)
        {
            sb.Append("    ").AppendLine(GeneratedCodeAttribute);
            sb.Append("    internal static class ").AppendLine(contract.InitTypeName);
            sb.AppendLine("    {");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        internal static void Init()");
            sb.AppendLine("        {");
            sb.Append("            ").Append(RegistryTypeName).Append(".RegisterClient<").Append(contract.InterfaceFullName)
                .Append(">(").Append(contract.ProxyTypeName).AppendLine(".Create);");
            sb.Append("            ").Append(RegistryTypeName).Append(".RegisterServer(typeof(").Append(contract.InterfaceFullName)
                .Append("), typeof(").Append(contract.ServerBindingsTypeName).AppendLine("));");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        // -------- client --------

        private static void EmitClientProxy(StringBuilder sb, GrpcInterfaceModel contract)
        {
            sb.Append("    ").AppendLine(GeneratedCodeAttribute);
            sb.AppendLine("    [global::System.Diagnostics.DebuggerNonUserCode]");
            sb.Append("    internal sealed class ").Append(contract.ProxyTypeName)
                .Append(" : global::Grpc.Core.ClientBase, ").AppendLine(contract.InterfaceFullName);
            sb.AppendLine("    {");

            // Marshallers and Method<,> descriptors are instance fields built from the caller-supplied
            // BinderConfiguration: that is where custom marshaller factories live, so resolving them
            // from the static BinderConfiguration.Default (or in a static initializer) would break every
            // service whose payloads aren't marshallable under the defaults.
            var payloadTypes = PayloadTypes(contract);
            var marshallers = new Dictionary<string, string>(StringComparer.Ordinal);
            var index = 0;
            foreach (var payload in payloadTypes)
            {
                var field = "__m" + index++;
                marshallers.Add(payload, field);
                sb.Append("        private readonly global::Grpc.Core.Marshaller<").Append(payload).Append("> ").Append(field).AppendLine(";");
            }

            var methodFields = new string[contract.Operations.Length];
            for (var i = 0; i < contract.Operations.Length; i++)
            {
                var operation = contract.Operations[i];
                methodFields[i] = "__op" + i;
                sb.Append("        private readonly ").Append(MethodType(operation)).Append(" ").Append(methodFields[i]).AppendLine(";");
            }
            sb.AppendLine();

            sb.Append("        public ").Append(contract.ProxyTypeName)
                .Append("(global::Grpc.Core.CallInvoker callInvoker, ").Append(BinderConfigurationTypeName).AppendLine(" config) : base(callInvoker)");
            sb.AppendLine("        {");
            sb.Append("            if (config is null) config = ").Append(BinderConfigurationTypeName).AppendLine(".Default;");
            foreach (var payload in payloadTypes)
            {
                sb.Append("            ").Append(marshallers[payload]).Append(" = config.GetMarshaller<").Append(payload).AppendLine(">();");
            }
            for (var i = 0; i < contract.Operations.Length; i++)
            {
                var operation = contract.Operations[i];
                sb.Append("            ").Append(methodFields[i]).Append(" = new ").Append(MethodType(operation)).Append("(")
                    .Append(MethodTypeEnum(operation.Kind)).Append(", ")
                    .Append(Literal(contract.ServiceName)).Append(", ")
                    .Append(Literal(operation.OperationName)).Append(", ")
                    .Append(marshallers[operation.RequestTypeFullName]).Append(", ")
                    .Append(marshallers[operation.ResponseTypeFullName]).AppendLine(");");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // the single-argument form is what a manual [Proxy(typeof(...))] consumer constructs
            sb.Append("        public ").Append(contract.ProxyTypeName).AppendLine("(global::Grpc.Core.CallInvoker callInvoker)");
            sb.Append("            : this(callInvoker, ").Append(BinderConfigurationTypeName).AppendLine(".Default) { }");
            sb.AppendLine();

            sb.Append("        public static ").Append(contract.InterfaceFullName)
                .Append(" Create(global::Grpc.Core.CallInvoker callInvoker, ").Append(BinderConfigurationTypeName).AppendLine(" config)");
            sb.Append("            => new ").Append(contract.ProxyTypeName).AppendLine("(callInvoker, config);");
            sb.AppendLine();
            sb.Append("        public static ").Append(contract.InterfaceFullName).AppendLine(" Create(global::Grpc.Core.CallInvoker callInvoker)");
            sb.Append("            => new ").Append(contract.ProxyTypeName).AppendLine("(callInvoker);");
            sb.AppendLine();

            sb.Append("        public override string ToString() => ").Append(Literal(contract.ServiceName + " / CallInvoker")).AppendLine(";");
            sb.AppendLine();

            for (var i = 0; i < contract.Operations.Length; i++)
            {
                EmitClientOperation(sb, contract, contract.Operations[i], methodFields[i]);
            }

            // the runtime proxy implements these as no-ops rather than binding them, because
            // infrastructure (ASP.NET Core DI, for one) calls Dispose on whatever it is handed
            if (contract.ImplementsDisposable)
            {
                sb.AppendLine("        void global::System.IDisposable.Dispose() { }");
                sb.AppendLine();
            }
            if (contract.ImplementsAsyncDisposable)
            {
                sb.AppendLine("        global::System.Threading.Tasks.ValueTask global::System.IAsyncDisposable.DisposeAsync() => default;");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
        }

        private static void EmitClientOperation(StringBuilder sb, GrpcInterfaceModel contract, GrpcOperationModel operation, string methodField)
        {
            // explicit interface implementation, so the proxy's own surface stays out of the way;
            // qualified with the interface that declares the operation, which is the base when the
            // contract inherits it
            sb.Append("        ").Append(operation.ReturnTypeDisplay).Append(" ").Append(operation.DeclaringInterfaceFullName)
                .Append(".").Append(operation.MethodName).Append("(");
            for (var i = 0; i < operation.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(operation.Parameters[i].TypeDisplay).Append(" ").Append(operation.Parameters[i].Name);
            }
            sb.AppendLine(")");
            sb.AppendLine("        {");

            if (operation.Context == GrpcContextKind.CancellationToken)
            {
                sb.Append("            ").Append(CallContextTypeName).Append(" __ctx = (").Append(CallContextTypeName)
                    .Append(")").Append(ContextParameterName(operation)).AppendLine(";");
            }

            var request = operation.RequestShape == GrpcArgShape.Void
                ? EmptyTypeName + ".Instance"
                : operation.Parameters[0].Name;

            var context = operation.Context switch
            {
                GrpcContextKind.CallContext => "in " + ContextParameterName(operation),
                GrpcContextKind.CancellationToken => "in __ctx",
                _ => "in " + CallContextTypeName + ".Default",
            };

            sb.Append("            ");
            if (!(operation.ResponseShape == GrpcResultShape.Sync && operation.VoidResponse)) sb.Append("return ");
            sb.Append(ReshapeTypeName).Append(".").Append(ClientReshapeMethod(operation)).Append("(")
                .Append(context).Append(", this.CallInvoker, ").Append(methodField).Append(", ").Append(request).AppendLine(", null);");

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // -------- server --------

        private static void EmitServerBindings(StringBuilder sb, GrpcInterfaceModel contract)
        {
            sb.Append("    ").AppendLine(GeneratedCodeAttribute);
            sb.AppendLine("    [global::System.Diagnostics.DebuggerNonUserCode]");
            sb.Append("    public static class ").AppendLine(contract.ServerBindingsTypeName);
            sb.AppendLine("    {");

            sb.Append("        public static int Bind<TService>(").Append(ServerMethodBinderTypeName).AppendLine("<TService> binder)");
            sb.Append("            where TService : class, ").AppendLine(contract.InterfaceFullName);
            sb.AppendLine("        {");
            sb.AppendLine("            var __cfg = binder.Configuration;");
            sb.AppendLine("            int count = 0;");

            foreach (var operation in contract.Operations)
            {
                var sameType = string.Equals(operation.RequestTypeFullName, operation.ResponseTypeFullName, StringComparison.Ordinal);
                var operationLiteral = Literal(operation.MethodName);

                // Marshallers are resolved per operation inside a try/catch so that one unmarshallable
                // payload can't take down the whole contract, and so the failure names the operation:
                // the host's startup log then points straight at the broken member.
                sb.AppendLine("            try");
                sb.AppendLine("            {");
                sb.Append("                var __m_req = __cfg.GetMarshaller<").Append(operation.RequestTypeFullName).AppendLine(">();");
                if (!sameType)
                {
                    sb.Append("                var __m_resp = __cfg.GetMarshaller<").Append(operation.ResponseTypeFullName).AppendLine(">();");
                }
                sb.Append("                var __op = new ").Append(MethodType(operation)).Append("(")
                    .Append(MethodTypeEnum(operation.Kind)).Append(", ")
                    .Append(Literal(contract.ServiceName)).Append(", ")
                    .Append(Literal(operation.OperationName)).Append(", __m_req, ")
                    .Append(sameType ? "__m_req" : "__m_resp").AppendLine(");");

                sb.Append("                binder.").Append(operation.Kind switch
                {
                    GrpcMethodKind.ServerStreaming => "AddServerStreamingMethod",
                    GrpcMethodKind.ClientStreaming => "AddClientStreamingMethod",
                    GrpcMethodKind.DuplexStreaming => "AddDuplexStreamingMethod",
                    _ => "AddUnaryMethod",
                })
                    .Append("<").Append(operation.RequestTypeFullName).Append(", ").Append(operation.ResponseTypeFullName).Append(">(__op, ")
                    // the declaring interface, since the metadata lookup is a GetMethod that doesn't
                    // search base interfaces
                    .Append("binder.GetMetadata(typeof(").Append(operation.DeclaringInterfaceFullName).Append("), ").Append(operationLiteral).Append("), ")
                    .Append(ServerHandlerName(operation)).AppendLine("<TService>);");
                sb.AppendLine("                count++;");
                sb.AppendLine("            }");
                sb.AppendLine("            catch (global::System.Exception __ex)");
                sb.AppendLine("            {");
                sb.Append("                throw new global::System.InvalidOperationException(\"Failed to bind '\" + ")
                    .Append(operationLiteral).Append(" + \"' on \" + typeof(").Append(contract.InterfaceFullName)
                    .AppendLine(").FullName + \": \" + __ex.Message, __ex);");
                sb.AppendLine("            }");
            }

            sb.AppendLine("            return count;");
            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var operation in contract.Operations)
            {
                EmitServerHandler(sb, contract, operation);
            }

            sb.AppendLine("    }");
        }

        private static string ServerHandlerName(GrpcOperationModel operation) => operation.MethodName + "_Server_" + operation.Kind;

        private static void EmitServerHandler(StringBuilder sb, GrpcInterfaceModel contract, GrpcOperationModel operation)
        {
            const string ServerCallContext = "global::Grpc.Core.ServerCallContext";
            var name = ServerHandlerName(operation);

            switch (operation.Kind)
            {
                case GrpcMethodKind.Unary:
                    sb.Append("        private static global::System.Threading.Tasks.Task<").Append(operation.ResponseTypeFullName)
                        .Append("> ").Append(name).Append("<TService>(TService service, ").Append(operation.RequestTypeFullName)
                        .Append(" request, ").Append(ServerCallContext).AppendLine(" ctx)");
                    sb.Append("            where TService : class, ").AppendLine(contract.InterfaceFullName);
                    sb.AppendLine("        {");
                    EmitServerContextLocal(sb, operation);
                    EmitServerReturn(sb, operation, ServiceCall(operation, "request"));
                    sb.AppendLine("        }");
                    break;

                case GrpcMethodKind.ServerStreaming:
                    sb.Append("        private static global::System.Threading.Tasks.Task ").Append(name)
                        .Append("<TService>(TService service, ").Append(operation.RequestTypeFullName)
                        .Append(" request, global::Grpc.Core.IServerStreamWriter<").Append(operation.ResponseTypeFullName)
                        .Append("> writer, ").Append(ServerCallContext).AppendLine(" ctx)");
                    sb.Append("            where TService : class, ").AppendLine(contract.InterfaceFullName);
                    sb.AppendLine("        {");
                    EmitServerContextLocal(sb, operation);
                    sb.Append("            return ").Append(ReshapeTypeName).Append(".WriteTo<").Append(operation.ResponseTypeFullName)
                        .Append(">(").Append(ServiceCall(operation, "request")).AppendLine(", writer, ctx.CancellationToken);");
                    sb.AppendLine("        }");
                    break;

                case GrpcMethodKind.ClientStreaming:
                    sb.Append("        private static global::System.Threading.Tasks.Task<").Append(operation.ResponseTypeFullName)
                        .Append("> ").Append(name).Append("<TService>(TService service, global::Grpc.Core.IAsyncStreamReader<")
                        .Append(operation.RequestTypeFullName).Append("> reader, ").Append(ServerCallContext).AppendLine(" ctx)");
                    sb.Append("            where TService : class, ").AppendLine(contract.InterfaceFullName);
                    sb.AppendLine("        {");
                    EmitServerContextLocal(sb, operation);
                    EmitRequestStreamLocal(sb, operation);
                    EmitServerReturn(sb, operation, ServiceCall(operation, "seq"));
                    sb.AppendLine("        }");
                    break;

                case GrpcMethodKind.DuplexStreaming:
                    sb.Append("        private static global::System.Threading.Tasks.Task ").Append(name)
                        .Append("<TService>(TService service, global::Grpc.Core.IAsyncStreamReader<").Append(operation.RequestTypeFullName)
                        .Append("> reader, global::Grpc.Core.IServerStreamWriter<").Append(operation.ResponseTypeFullName)
                        .Append("> writer, ").Append(ServerCallContext).AppendLine(" ctx)");
                    sb.Append("            where TService : class, ").AppendLine(contract.InterfaceFullName);
                    sb.AppendLine("        {");
                    EmitServerContextLocal(sb, operation);
                    EmitRequestStreamLocal(sb, operation);
                    sb.Append("            return ").Append(ReshapeTypeName).Append(".WriteTo<").Append(operation.ResponseTypeFullName)
                        .Append(">(").Append(ServiceCall(operation, "seq")).AppendLine(", writer, ctx.CancellationToken);");
                    sb.AppendLine("        }");
                    break;
            }
            sb.AppendLine();
        }

        private static void EmitServerContextLocal(StringBuilder sb, GrpcOperationModel operation)
        {
            switch (operation.Context)
            {
                case GrpcContextKind.CallContext:
                    sb.Append("            var __cc = new ").Append(CallContextTypeName).AppendLine("(service, ctx);");
                    break;
                case GrpcContextKind.CancellationToken:
                    sb.AppendLine("            var __ct = ctx.CancellationToken;");
                    break;
            }
        }

        private static void EmitRequestStreamLocal(StringBuilder sb, GrpcOperationModel operation)
        {
            sb.Append("            var seq = ").Append(ReshapeTypeName).Append(".AsAsyncEnumerable<")
                .Append(operation.RequestTypeFullName).AppendLine(">(reader, ctx.CancellationToken);");
        }

        /// <summary>
        /// Adapt whatever the service method returns to the <c>Task&lt;TResponse&gt;</c> the binder wants.
        /// </summary>
        private static void EmitServerReturn(StringBuilder sb, GrpcOperationModel operation, string call)
        {
            switch (operation.ResponseShape)
            {
                case GrpcResultShape.Task when operation.VoidResponse:
                    sb.Append("            return ").Append(ReshapeTypeName).Append(".EmptyTask(").Append(call).AppendLine(");");
                    break;
                case GrpcResultShape.Task:
                    sb.Append("            return ").Append(call).AppendLine(";");
                    break;
                case GrpcResultShape.ValueTask when operation.VoidResponse:
                    sb.Append("            return ").Append(ReshapeTypeName).Append(".EmptyValueTask(").Append(call).AppendLine(");");
                    break;
                case GrpcResultShape.ValueTask:
                    sb.Append("            return ").Append(call).AppendLine(".AsTask();");
                    break;
                case GrpcResultShape.Sync when operation.VoidResponse:
                    sb.Append("            ").Append(call).AppendLine(";");
                    sb.Append("            return ").Append(EmptyTypeName).AppendLine(".InstanceTask;");
                    break;
                case GrpcResultShape.Sync:
                    sb.Append("            return global::System.Threading.Tasks.Task.FromResult(").Append(call).AppendLine(");");
                    break;
                default:
                    sb.AppendLine("            throw new global::System.NotSupportedException(\"Unsupported response shape\");");
                    break;
            }
        }

        private static string ServiceCall(GrpcOperationModel operation, string requestExpression)
        {
            var args = new List<string>(2);
            if (!operation.VoidRequest) args.Add(requestExpression);
            switch (operation.Context)
            {
                case GrpcContextKind.CallContext: args.Add("__cc"); break;
                case GrpcContextKind.CancellationToken: args.Add("__ct"); break;
            }
            return "service." + operation.MethodName + "(" + string.Join(", ", args) + ")";
        }

        // -------- shared --------

        /// <summary>
        /// Every payload type on the contract, ordered so that the emitted field names are stable.
        /// </summary>
        private static SortedSet<string> PayloadTypes(GrpcInterfaceModel contract)
        {
            var payloads = new SortedSet<string>(StringComparer.Ordinal);
            foreach (var operation in contract.Operations)
            {
                payloads.Add(operation.RequestTypeFullName);
                payloads.Add(operation.ResponseTypeFullName);
            }
            return payloads;
        }

        private static string MethodType(GrpcOperationModel operation)
            => "global::Grpc.Core.Method<" + operation.RequestTypeFullName + ", " + operation.ResponseTypeFullName + ">";

        private static string ContextParameterName(GrpcOperationModel operation)
        {
            var index = operation.RequestShape == GrpcArgShape.Void ? 0 : 1;
            return operation.Parameters.Length > index ? operation.Parameters[index].Name : "context";
        }

        private static string MethodTypeEnum(GrpcMethodKind kind) => kind switch
        {
            GrpcMethodKind.ServerStreaming => "global::Grpc.Core.MethodType.ServerStreaming",
            GrpcMethodKind.ClientStreaming => "global::Grpc.Core.MethodType.ClientStreaming",
            GrpcMethodKind.DuplexStreaming => "global::Grpc.Core.MethodType.DuplexStreaming",
            _ => "global::Grpc.Core.MethodType.Unary",
        };

        /// <summary>
        /// The <c>Reshape</c> helper that adapts the client call to the operation's declared shape.
        /// </summary>
        private static string ClientReshapeMethod(GrpcOperationModel operation)
            => (operation.Kind, operation.ResponseShape, operation.VoidResponse) switch
            {
                (GrpcMethodKind.Unary, GrpcResultShape.Task, _) => "UnaryTaskAsync",
                (GrpcMethodKind.Unary, GrpcResultShape.ValueTask, false) => "UnaryValueTaskAsync",
                (GrpcMethodKind.Unary, GrpcResultShape.ValueTask, true) => "UnaryValueTaskAsyncVoid",
                (GrpcMethodKind.Unary, GrpcResultShape.Sync, false) => "UnarySync",
                (GrpcMethodKind.Unary, GrpcResultShape.Sync, true) => "UnarySyncVoid",
                (GrpcMethodKind.ServerStreaming, _, _) => "ServerStreamingAsync",
                (GrpcMethodKind.ClientStreaming, GrpcResultShape.Task, _) => "ClientStreamingTaskAsync",
                (GrpcMethodKind.ClientStreaming, GrpcResultShape.ValueTask, false) => "ClientStreamingValueTaskAsync",
                (GrpcMethodKind.ClientStreaming, GrpcResultShape.ValueTask, true) => "ClientStreamingValueTaskAsyncVoid",
                (GrpcMethodKind.DuplexStreaming, _, _) => "DuplexAsync",
                _ => "UnaryTaskAsync",
            };

        private static string Literal(string value)
        {
            var sb = new StringBuilder(value.Length + 2).Append('"');
            foreach (var c in value)
            {
                switch (c)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '"': sb.Append("\\\""); break;
                    default: sb.Append(c); break;
                }
            }
            return sb.Append('"').ToString();
        }
    }
}
