#nullable enable
using ProtoBuf.BuildTools.Internal.Aot;
using System.Globalization;
using System.Text;

namespace ProtoBuf.BuildTools.Generators
{
    partial class ProtoModelGenerator
    {
        private const string Serializers = "global::ProtoBuf.Serializers";
        private const string Features = Serializers + ".SerializerFeatures";
        private const string ServicesTypeName = "ProtoBufGeneratedServices";

        /// <summary>
        /// Render a plan as the partial half of the user's model class.
        /// </summary>
        /// <remarks>
        /// The shape here is copied from what ref-emit produces for the same contracts (see
        /// <c>src/AotRefGen</c>), rather than invented; the differences are deliberate - a nested
        /// services type rather than a mangled top-level one, and real explicit-interface members.
        /// </remarks>
        private static string Emit(ProtoModelPlan plan)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>")
              .AppendLine("#nullable disable")
              .AppendLine("#pragma warning disable CS1591")
              .AppendLine();

            const int indent = 0;
            if (plan.Namespace is not null)
            {
                sb.AppendLine($"namespace {plan.Namespace};").AppendLine();
            }

            Line(sb, indent, $"partial class {plan.TypeName}");
            Line(sb, indent, "{");

            // TODO: the base declares [DynamicallyAccessedMembers(DynamicAccess.ContractType)] on T,
            // but DynamicAccess is internal to protobuf-net so we cannot restate it here; confirm
            // against a real PublishAot build whether the override needs its own annotation
            Line(sb, indent + 1, $"protected sealed override {Serializers}.ISerializer<T> GetSerializer<T>()");
            Line(sb, indent + 2, $"=> {Serializers}.SerializerCache.Get<{ServicesTypeName}, T>();");
            sb.AppendLine();

            Line(sb, indent + 1, $"private sealed class {ServicesTypeName}");
            var prefix = ':';
            foreach (var contract in plan.Contracts)
            {
                Line(sb, indent + 2, $"{prefix} {Serializers}.ISerializer<{contract.TypeName}>");
                prefix = ',';
                if (contract.SkipConstructor)
                {
                    Line(sb, indent + 2, $", {Serializers}.IFactory<{contract.TypeName}>");
                }
            }
            Line(sb, indent + 1, "{");

            var first = true;
            foreach (var contract in plan.Contracts)
            {
                if (!first) sb.AppendLine();
                first = false;
                EmitContract(sb, indent + 2, contract);
            }

            Line(sb, indent + 1, "}");
            Line(sb, indent, "}");
            return sb.ToString();
        }

        private static void EmitContract(StringBuilder sb, int indent, ProtoContractPlan contract)
        {
            var self = $"{Serializers}.ISerializer<{contract.TypeName}>";

            Line(sb, indent, $"{Features} {self}.Features");
            Line(sb, indent + 1, $"=> {Features}.CategoryMessage | {Features}.WireTypeString;");
            sb.AppendLine();

            if (contract.SkipConstructor)
            {
                Line(sb, indent, $"{contract.TypeName} {Serializers}.IFactory<{contract.TypeName}>.Create(global::ProtoBuf.ISerializationContext context)");
                Line(sb, indent + 1, $"=> {Construct(contract)};");
                sb.AppendLine();
            }

            Line(sb, indent, $"{contract.TypeName} {self}.Read(ref global::ProtoBuf.ProtoReader.State state, {contract.TypeName} value)");
            Line(sb, indent, "{");
            // a struct arrives by value and is never null, so there is nothing to construct
            if (!contract.IsValueType)
            {
                Line(sb, indent + 1, $"value ??= {Construct(contract)};");
            }
            Line(sb, indent + 1, "int field;");
            Line(sb, indent + 1, "while ((field = state.ReadFieldHeader()) > 0)");
            Line(sb, indent + 1, "{");
            Line(sb, indent + 2, "switch (field)");
            Line(sb, indent + 2, "{");
            foreach (var member in contract.Members)
            {
                var number = member.FieldNumber.ToString(CultureInfo.InvariantCulture);
                Line(sb, indent + 3, $"case {number}:");
                Line(sb, indent + 3, "{");
                switch (member.Kind)
                {
                    case ProtoMemberKind.Bool:
                    case ProtoMemberKind.SByte:
                    case ProtoMemberKind.Byte:
                    case ProtoMemberKind.Int16:
                    case ProtoMemberKind.UInt16:
                    case ProtoMemberKind.Int32:
                    case ProtoMemberKind.UInt32:
                    case ProtoMemberKind.Int64:
                    case ProtoMemberKind.UInt64:
                    case ProtoMemberKind.Single:
                    case ProtoMemberKind.Double:
                    case ProtoMemberKind.Char:
                        Line(sb, indent + 4, $"value.{member.Name} = {ScalarRead(member)};");
                        break;
                    case ProtoMemberKind.String:
                        // a null string leaves the existing value alone, matching ref-emit
                        Line(sb, indent + 4, $"var tmp{number} = state.ReadString();");
                        Line(sb, indent + 4, $"if (tmp{number} != null) value.{member.Name} = tmp{number};");
                        break;
                    case ProtoMemberKind.Bytes:
                        // AppendBytes, not ReadBytes: repeated occurrences concatenate onto the
                        // existing array rather than replacing it
                        Line(sb, indent + 4, $"var tmp{number} = value.{member.Name};");
                        Line(sb, indent + 4, $"tmp{number} = state.AppendBytes(tmp{number});");
                        Line(sb, indent + 4, $"if (tmp{number} != null) value.{member.Name} = tmp{number};");
                        break;
                    // in all three cases the *existing* value is passed in, so repeated occurrences
                    // merge rather than replace; and the category is Repeated, not Message
                    case ProtoMemberKind.Message when member.IsNullable:
                        // a nullable struct message: seed from the current value, assign the result
                        // straight back - the read cannot produce a null
                        Line(sb, indent + 4, $"var tmp{number} = value.{member.Name}.GetValueOrDefault();");
                        Line(sb, indent + 4, $"value.{member.Name} = state.ReadMessage<{member.TypeName}>({Features}.CategoryRepeated, tmp{number}, this);");
                        break;
                    case ProtoMemberKind.Message when member.MessageIsValueType:
                        Line(sb, indent + 4, $"var tmp{number} = value.{member.Name};");
                        Line(sb, indent + 4, $"value.{member.Name} = state.ReadMessage<{member.TypeName}>({Features}.CategoryRepeated, tmp{number}, this);");
                        break;
                    case ProtoMemberKind.Message:
                        Line(sb, indent + 4, $"var tmp{number} = value.{member.Name};");
                        Line(sb, indent + 4, $"tmp{number} = state.ReadMessage<{member.TypeName}>({Features}.CategoryRepeated, tmp{number}, this);");
                        Line(sb, indent + 4, $"if (tmp{number} != null) value.{member.Name} = tmp{number};");
                        break;
                }
                Line(sb, indent + 4, "break;");
                Line(sb, indent + 3, "}");
            }
            Line(sb, indent + 3, "default:");
            Line(sb, indent + 4, "state.SkipField();");
            Line(sb, indent + 4, "break;");
            Line(sb, indent + 2, "}");
            Line(sb, indent + 1, "}");
            Line(sb, indent + 1, "return value;");
            Line(sb, indent, "}");
            sb.AppendLine();

            Line(sb, indent, $"void {self}.Write(ref global::ProtoBuf.ProtoWriter.State state, {contract.TypeName} value)");
            Line(sb, indent, "{");
            // ThrowUnexpectedSubtype is constrained to reference types, and a struct cannot have
            // sub-types anyway
            if (!contract.IsValueType)
            {
                Line(sb, indent + 1, "global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);");
            }
            foreach (var member in contract.Members)
            {
                var number = member.FieldNumber.ToString(CultureInfo.InvariantCulture);
                // hoist to a local, as ref-emit does; the member could be a computed property
                Line(sb, indent + 1, $"var tmp{number} = value.{member.Name};");

                if (member.IsNullable && member.Kind == ProtoMemberKind.Message)
                {
                    // a nullable struct message: presence decides, and the unwrapped value goes
                    // straight to WriteMessage
                    Line(sb, indent + 1, $"if (tmp{number}.HasValue)");
                    Line(sb, indent + 1, "{");
                    Line(sb, indent + 2, $"state.WriteMessage<{member.TypeName}>({number}, {Features}.CategoryRepeated, tmp{number}.GetValueOrDefault(), this);");
                    Line(sb, indent + 1, "}");
                    continue;
                }

                if (member.IsNullable)
                {
                    // presence decides, not value - so a nullable zero *is* written, unlike a plain
                    // zero. A declared default then nests inside, rather than replacing the test.
                    Line(sb, indent + 1, $"if (tmp{number}.HasValue)");
                    Line(sb, indent + 1, "{");
                    Line(sb, indent + 2, $"var val{number} = tmp{number}.GetValueOrDefault();");
                    if (member.DefaultLiteral is { } nullableDefault)
                    {
                        Line(sb, indent + 2, $"if (val{number} != {nullableDefault})");
                        Line(sb, indent + 2, "{");
                        EmitScalarWrite(sb, indent + 3, member, number, $"val{number}");
                        Line(sb, indent + 2, "}");
                    }
                    else
                    {
                        EmitScalarWrite(sb, indent + 2, member, number, $"val{number}");
                    }
                    Line(sb, indent + 1, "}");
                    continue;
                }

                switch (member.Kind)
                {
                    // int32 has a convenience overload that writes its own field header; everything
                    // else needs the header emitting separately, as ref-emit does
                    case ProtoMemberKind.Int32:
                        Line(sb, indent + 1, $"if ({ScalarGuard(member, $"tmp{number}")}) state.WriteInt32Varint({number}, {ScalarValue(member, $"tmp{number}")});");
                        break;
                    case ProtoMemberKind.Bool:
                    case ProtoMemberKind.SByte:
                    case ProtoMemberKind.Byte:
                    case ProtoMemberKind.Int16:
                    case ProtoMemberKind.UInt16:
                    case ProtoMemberKind.UInt32:
                    case ProtoMemberKind.Int64:
                    case ProtoMemberKind.UInt64:
                    case ProtoMemberKind.Single:
                    case ProtoMemberKind.Double:
                    case ProtoMemberKind.Char:
                        Line(sb, indent + 1, $"if ({ScalarGuard(member, $"tmp{number}")})");
                        Line(sb, indent + 1, "{");
                        EmitScalarWrite(sb, indent + 2, member, number, $"tmp{number}");
                        Line(sb, indent + 1, "}");
                        break;
                    case ProtoMemberKind.String when member.DefaultLiteral is { } declared:
                        // the null test has to be explicit here: WriteString skips nulls itself, but
                        // we must not compare a null against the declared default
                        Line(sb, indent + 1, $"if (tmp{number} != null && tmp{number} != {declared})");
                        Line(sb, indent + 1, "{");
                        Line(sb, indent + 2, $"state.WriteString({number}, tmp{number});");
                        Line(sb, indent + 1, "}");
                        break;
                    case ProtoMemberKind.String:
                        // no null test: WriteString(int, string) skips nulls itself
                        Line(sb, indent + 1, $"state.WriteString({number}, tmp{number});");
                        break;
                    case ProtoMemberKind.Bytes:
                        // unlike WriteString, WriteBytes(byte[]) neither skips nulls nor writes its
                        // own field header, so both are explicit here
                        Line(sb, indent + 1, $"if (tmp{number} != null)");
                        Line(sb, indent + 1, "{");
                        Line(sb, indent + 2, $"state.WriteFieldHeader({number}, global::ProtoBuf.WireType.String);");
                        Line(sb, indent + 2, $"state.WriteBytes(tmp{number});");
                        Line(sb, indent + 1, "}");
                        break;
                    case ProtoMemberKind.Message:
                        // likewise WriteMessage(int, ...) skips nulls itself
                        Line(sb, indent + 1, $"state.WriteMessage<{member.TypeName}>({number}, {Features}.CategoryRepeated, tmp{number}, this);");
                        break;
                }
            }
            Line(sb, indent, "}");
        }

        /// <summary>
        /// How a fresh instance is made: normally <c>new</c>, but SkipConstructor bypasses every
        /// constructor, exactly as ref-emit does.
        /// </summary>
        private static string Construct(ProtoContractPlan contract)
            => contract.SkipConstructor
                ? $"({contract.TypeName})global::ProtoBuf.BclHelpers.GetUninitializedObject(typeof({contract.TypeName}))"
                : $"new {contract.TypeName}()";

        /// <summary>
        /// The unguarded write for a scalar: the caller owns whatever test precedes it.
        /// </summary>
        private static void EmitScalarWrite(StringBuilder sb, int indent, ProtoMemberPlan member, string number, string local)
        {
            var expression = ScalarValue(member, local);
            if (member.Kind == ProtoMemberKind.Int32)
            {
                Line(sb, indent, $"state.WriteInt32Varint({number}, {expression});");
            }
            else
            {
                Line(sb, indent, $"state.WriteFieldHeader({number}, global::ProtoBuf.WireType.{ScalarWireType(member.Kind)});");
                Line(sb, indent, $"state.{ScalarSuffix(member.Kind, "Write")}({expression});");
            }
        }

        /// <summary>
        /// The value handed to the write method: an enum needs casting down to its underlying type,
        /// while a char converts to ushort implicitly.
        /// </summary>
        private static string ScalarValue(ProtoMemberPlan member, string local)
            => member.EnumTypeName is null ? local : $"({UnderlyingKeyword(member.Kind)}){local}";

        /// <summary>
        /// The value read back: cast up to the enum type, or to char, since the read methods deal in
        /// the underlying scalar.
        /// </summary>
        private static string ScalarRead(ProtoMemberPlan member)
        {
            var call = $"state.{ScalarSuffix(member.Kind, "Read")}()";
            if (member.EnumTypeName is { } enumType) return $"({enumType}){call}";
            return member.Kind == ProtoMemberKind.Char ? $"(char){call}" : call;
        }

        private static string UnderlyingKeyword(ProtoMemberKind kind) => kind switch
        {
            ProtoMemberKind.SByte => "sbyte",
            ProtoMemberKind.Byte => "byte",
            ProtoMemberKind.Int16 => "short",
            ProtoMemberKind.UInt16 => "ushort",
            ProtoMemberKind.Int32 => "int",
            ProtoMemberKind.UInt32 => "uint",
            ProtoMemberKind.Int64 => "long",
            ProtoMemberKind.UInt64 => "ulong",
            _ => kind.ToString(),
        };

        /// <summary>The <c>ReadXxx</c>/<c>WriteXxx</c> name for a scalar kind.</summary>
        private static string ScalarSuffix(ProtoMemberKind kind, string prefix) => prefix + (kind switch
        {
            ProtoMemberKind.Bool => "Boolean",
            ProtoMemberKind.Single => "Single",
            ProtoMemberKind.Double => "Double",
            ProtoMemberKind.Char => "UInt16", // a char goes on the wire as a ushort
            _ => kind.ToString(), // SByte, Byte, Int16, UInt16, Int32, UInt32, Int64, UInt64
        });

        private static string ScalarWireType(ProtoMemberKind kind) => kind switch
        {
            ProtoMemberKind.Single => "Fixed32",
            ProtoMemberKind.Double => "Fixed64",
            _ => "Varint",
        };

        /// <summary>
        /// The "is this worth writing" test: a member equal to its default is omitted, where the
        /// default is <c>[DefaultValue]</c> if declared and the type's own default otherwise.
        /// </summary>
        private static string ScalarGuard(ProtoMemberPlan member, string local)
        {
            if (member.DefaultLiteral is { } declared) return $"{local} != {declared}";

            // an enum compares against its own zero, which need not have a declared name
            if (member.EnumTypeName is { } enumType) return $"{local} != default({enumType})";

            return member.Kind switch
            {
                ProtoMemberKind.Bool => local,
                ProtoMemberKind.Single => $"{local} != 0f",
                ProtoMemberKind.Double => $"{local} != 0d",
                _ => $"{local} != 0",
            };
        }

        private static void Line(StringBuilder sb, int indent, string text)
            => sb.Append(' ', indent * 4).AppendLine(text);
    }
}
