#nullable enable
using ProtoBuf.BuildTools.Internal.Aot;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace ProtoBuf.BuildTools.Generators
{
    partial class ProtoModelGenerator
    {
        private const string Serializers = "global::ProtoBuf.Serializers";
        private const string Features = Serializers + ".SerializerFeatures";
        private const string ServicesTypeName = "ProtoBufGeneratedServices";

        private const string MemberTypes = "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes";

        /// <summary>Mirrors <c>ProtoBuf.Internal.DynamicAccess.ContractType</c>, which is internal.</summary>
        private const string DynamicallyAccessedMembers
            = "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers("
            + MemberTypes + ".PublicConstructors | " + MemberTypes + ".NonPublicConstructors | "
            + MemberTypes + ".PublicParameterlessConstructor | "
            + MemberTypes + ".PublicProperties | " + MemberTypes + ".NonPublicProperties | "
            + MemberTypes + ".PublicFields | " + MemberTypes + ".NonPublicFields | "
            + MemberTypes + ".PublicMethods | " + MemberTypes + ".NonPublicMethods | "
            + MemberTypes + ".PublicNestedTypes | " + MemberTypes + ".NonPublicNestedTypes)";

        /// <summary>
        /// Render a plan as the partial half of the user's model class.
        /// </summary>
        /// <remarks>
        /// The shape here is copied from what ref-emit produces for the same contracts (see
        /// <c>src/AotRefGen</c>), rather than invented; the differences are deliberate - a nested
        /// services type rather than a mangled top-level one, and real explicit-interface members.
        /// </remarks>
        private static string Emit(ProtoModelPlan plan)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>")
              .AppendLine("#nullable disable")
              .AppendLine("#pragma warning disable CS1591")
              .AppendLine();

            const int indent = 0;
            if (plan.Namespace is not null)
            {
                sb.AppendLine($"namespace {plan.Namespace};").AppendLine();
            }

            Line(sb, indent, $"partial class {plan.TypeName}");
            Line(sb, indent, "{");

            // the base declares [DynamicallyAccessedMembers(DynamicAccess.ContractType)] on T, and an
            // override must restate it exactly or trim analysis reports IL2095. DynamicAccess is
            // internal to protobuf-net, so the flags are spelled out; keep them in step with
            // protobuf-net.Core/Internal/DynamicallyAccessedMembersAttribute.cs. src/AotSmoke is what
            // catches any drift, since IL2095 reappears the moment the two disagree.
            var typeParameter = plan.AnnotateTrimming ? $"[{DynamicallyAccessedMembers}] T" : "T";
            Line(sb, indent + 1, $"protected sealed override {Serializers}.ISerializer<T> GetSerializer<{typeParameter}>()");
            Line(sb, indent + 2, $"=> {Serializers}.SerializerCache.Get<{ServicesTypeName}, T>();");
            sb.AppendLine();

            Line(sb, indent + 1, $"private sealed class {ServicesTypeName}");
            var prefix = ':';
            foreach (var contract in plan.Contracts)
            {
                Line(sb, indent + 2, $"{prefix} {Serializers}.ISerializer<{contract.TypeName}>");
                prefix = ',';
                if (contract.RootTypeName is not null)
                {
                    Line(sb, indent + 2, $", {Serializers}.ISubTypeSerializer<{contract.TypeName}>");
                }
                if (contract.SkipConstructor)
                {
                    Line(sb, indent + 2, $", {Serializers}.IFactory<{contract.TypeName}>");
                }
            }
            foreach (var enumType in EnumProxies(plan))
            {
                Line(sb, indent + 2, $", {Serializers}.ISerializerProxy<{enumType.Key}>");
                Line(sb, indent + 2, $", {Serializers}.ISerializerProxy<{enumType.Key}?>");
            }
            Line(sb, indent + 1, "{");

            var first = true;
            foreach (var contract in plan.Contracts)
            {
                if (!first) sb.AppendLine();
                first = false;
                EmitContract(sb, indent + 2, contract);
            }

            EmitEnumProxies(sb, indent + 2, plan);
            EmitAccessors(sb, indent + 2, plan);

            Line(sb, indent + 1, "}");
            Line(sb, indent, "}");
            return sb.ToString();
        }

        private static void EmitContract(StringBuilder sb, int indent, ProtoContractPlan contract)
        {
            var self = $"{Serializers}.ISerializer<{contract.TypeName}>";

            Line(sb, indent, $"{Features} {self}.Features");
            Line(sb, indent + 1, $"=> {Features}.CategoryMessage | {Features}.WireTypeString;");
            sb.AppendLine();

            if (contract.SkipConstructor)
            {
                Line(sb, indent, $"{contract.TypeName} {Serializers}.IFactory<{contract.TypeName}>.Create(global::ProtoBuf.ISerializationContext context)");
                Line(sb, indent + 1, $"=> {Construct(contract)};");
                sb.AppendLine();
            }

            if (contract.RootTypeName is { } root)
            {
                EmitSubTypeContract(sb, indent, contract, root);
                return;
            }

            Line(sb, indent, $"{contract.TypeName} {self}.Read(ref global::ProtoBuf.ProtoReader.State state, {contract.TypeName} value)");
            Line(sb, indent, "{");
            if (contract.IsTuple)
            {
                // a tuple is rebuilt through its constructor at the end, so the read works on locals;
                // they are seeded from the incoming value so repeated occurrences still merge
                foreach (var member in contract.Members)
                {
                    Line(sb, indent + 1, $"{member.DeclaredTypeName} arg{member.FieldNumber} = default;");
                }
                if (!contract.IsValueType)
                {
                    Line(sb, indent + 1, "if (value != null)");
                    Line(sb, indent + 1, "{");
                    foreach (var member in contract.Members)
                    {
                        Line(sb, indent + 2, $"arg{member.FieldNumber} = value.{member.Name};");
                    }
                    Line(sb, indent + 1, "}");
                }
                else
                {
                    foreach (var member in contract.Members)
                    {
                        Line(sb, indent + 1, $"arg{member.FieldNumber} = value.{member.Name};");
                    }
                }
            }
            // a struct arrives by value and is never null, so there is nothing to construct
            else if (!contract.IsValueType)
            {
                Line(sb, indent + 1, $"value ??= {Construct(contract)};");
            }
            EmitReadLoop(sb, indent + 1, contract, "value");
            if (contract.IsTuple)
            {
                var arguments = string.Join(", ", contract.Members.Select(static x => $"arg{x.FieldNumber}"));
                Line(sb, indent + 1, contract.IsTupleLiteral
                    ? $"value = ({arguments});"
                    : $"value = new {contract.TypeName}({arguments});");
            }
            Line(sb, indent + 1, "return value;");
            Line(sb, indent, "}");
            sb.AppendLine();

            Line(sb, indent, $"void {self}.Write(ref global::ProtoBuf.ProtoWriter.State state, {contract.TypeName} value)");
            Line(sb, indent, "{");
            // ThrowUnexpectedSubtype is constrained to reference types, and a struct, a sealed type
            // and a tuple all rule sub-types out at compile time - ref-emit omits it for each
            if (!contract.IsValueType && !contract.IsTuple && !contract.IsSealed)
            {
                Line(sb, indent + 1, "global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);");
            }
            EmitWriteMembers(sb, indent + 1, contract);
            Line(sb, indent, "}");
        }

        /// <summary>
        /// The field-dispatch loop shared by <c>Read</c> and <c>ReadSubType</c>.
        /// </summary>
        /// <param name="instance">
        /// What the members hang off. A sub-type read works through <c>SubTypeState&lt;T&gt;</c>,
        /// so the instance has to be hoisted out of it - which also constructs it on demand.
        /// </param>
        private static void EmitReadLoop(StringBuilder sb, int indent, ProtoContractPlan contract,
            string instance, EquatableArray<ProtoSubTypePlan> subTypes = default)
        {
            Line(sb, indent, "int field;");
            Line(sb, indent, "while ((field = state.ReadFieldHeader()) > 0)");
            Line(sb, indent, "{");
            Line(sb, indent + 1, "switch (field)");
            Line(sb, indent + 1, "{");
            foreach (var member in contract.Members)
            {
                var number = member.FieldNumber.ToString(CultureInfo.InvariantCulture);
                // a tuple reads into the locals it will pass to the constructor, not into the member
                var target = contract.IsTuple ? $"arg{number}" : $"{instance}.{member.Name}";
                Line(sb, indent + 2, $"case {number}:");
                Line(sb, indent + 2, "{");
                // a sub-type read holds the instance inside SubTypeState, and reading it is what
                // constructs it - so it is hoisted per case, exactly as ref-emit does
                if (instance != "value") Line(sb, indent + 3, $"var {instance} = value.Value;");
                if (member.Map.Factory is not null)
                {
                    // same merge shape as a collection, but the key and value features - and any
                    // sub-serializers they need - ride alongside
                    Line(sb, indent + 3, $"var tmp{number} = {target};");
                    Line(sb, indent + 3, $"tmp{number} = {Map(member)}.ReadMap(ref state, {MapFeatures(member)}, tmp{number}, {MapElementFeatures(member)}{MapSubSerializers(member)});");
                    Line(sb, indent + 3, $"if (tmp{number} != null) {Assign(contract, member, target, $"tmp{number}")}");
                    Line(sb, indent + 3, "break;");
                    Line(sb, indent + 2, "}");
                    continue;
                }
                if (member.Repeated.Factory is not null)
                {
                    // same merge shape as a sub-message: the existing collection is passed in, and
                    // the result assigned back only if non-null
                    Line(sb, indent + 3, $"var tmp{number} = {target};");
                    Line(sb, indent + 3, $"tmp{number} = {Repeated(member)}.ReadRepeated(ref state, {RepeatedFeatures(member)}, tmp{number}{RepeatedSubSerializer(member)});");
                    // ImmutableArray<T> is a struct and can never be null
                    Line(sb, indent + 3, member.Repeated.IsValueType
                        ? Assign(contract, member, target, $"tmp{number}")
                        : $"if (tmp{number} != null) {Assign(contract, member, target, $"tmp{number}")}");
                    Line(sb, indent + 3, "break;");
                    Line(sb, indent + 2, "}");
                    continue;
                }
                switch (member.Kind)
                {
                    case ProtoMemberKind.Bool:
                    case ProtoMemberKind.SByte:
                    case ProtoMemberKind.Byte:
                    case ProtoMemberKind.Int16:
                    case ProtoMemberKind.UInt16:
                    case ProtoMemberKind.Int32:
                    case ProtoMemberKind.UInt32:
                    case ProtoMemberKind.Int64:
                    case ProtoMemberKind.UInt64:
                    case ProtoMemberKind.Single:
                    case ProtoMemberKind.Double:
                    case ProtoMemberKind.Char:
                        if (ScalarReadHint(member) is { } hint) Line(sb, indent + 3, hint);
                        Line(sb, indent + 3, Assign(contract, member, target, ScalarRead(member)));
                        break;
                    case ProtoMemberKind.String:
                        // a null string leaves the existing value alone, matching ref-emit
                        Line(sb, indent + 3, $"var tmp{number} = state.ReadString();");
                        Line(sb, indent + 3, $"if (tmp{number} != null) {Assign(contract, member, target, $"tmp{number}")}");
                        break;
                    case ProtoMemberKind.Bytes:
                        // AppendBytes, not ReadBytes: repeated occurrences concatenate onto the
                        // existing array rather than replacing it
                        Line(sb, indent + 3, $"var tmp{number} = {target};");
                        Line(sb, indent + 3, $"tmp{number} = state.AppendBytes(tmp{number});");
                        Line(sb, indent + 3, $"if (tmp{number} != null) {Assign(contract, member, target, $"tmp{number}")}");
                        break;
                    // in all three cases the *existing* value is passed in, so repeated occurrences
                    // merge rather than replace; and the category is Repeated, not Message
                    case ProtoMemberKind.Message when member.IsNullable:
                        // a nullable struct message: seed from the current value, assign the result
                        // straight back - the read cannot produce a null
                        Line(sb, indent + 3, $"var tmp{number} = {target}.GetValueOrDefault();");
                        Line(sb, indent + 3, Assign(contract, member, target, $"state.ReadMessage<{member.TypeName}>({Features}.CategoryRepeated, tmp{number}, this)"));
                        break;
                    case ProtoMemberKind.Message when member.MessageIsValueType:
                        Line(sb, indent + 3, $"var tmp{number} = {target};");
                        Line(sb, indent + 3, Assign(contract, member, target, $"state.ReadMessage<{member.TypeName}>({Features}.CategoryRepeated, tmp{number}, this)"));
                        break;
                    case ProtoMemberKind.Message:
                        Line(sb, indent + 3, $"var tmp{number} = {target};");
                        Line(sb, indent + 3, $"tmp{number} = state.ReadMessage<{member.TypeName}>({Features}.CategoryRepeated, tmp{number}, this);");
                        Line(sb, indent + 3, $"if (tmp{number} != null) {Assign(contract, member, target, $"tmp{number}")}");
                        break;
                }
                Line(sb, indent + 3, "break;");
                Line(sb, indent + 2, "}");
            }
            // a derived layer arrives as a nested sub-item at its own field number; reading it hands
            // the whole SubTypeState down, so the instance is constructed at the deepest layer
            foreach (var subType in subTypes)
            {
                var number = subType.FieldNumber.ToString(CultureInfo.InvariantCulture);
                Line(sb, indent + 2, $"case {number}:");
                Line(sb, indent + 3, $"value.ReadSubType<{subType.TypeName}>(ref state, this);");
                Line(sb, indent + 3, "break;");
            }
            // an extensible contract keeps what it does not recognise rather than discarding it; the
            // instance has to be materialised for that, which is why the sub-type form reads
            // value.Value here rather than using the per-case local
            Line(sb, indent + 2, "default:");
            Line(sb, indent + 3, contract.Extensible == ProtoExtensibleKind.None
                ? "state.SkipField();"
                : $"state.AppendExtensionData({(instance == "value" ? "value" : "value.Value")}{ExtensionType(contract)});");
            Line(sb, indent + 3, "break;");
            Line(sb, indent + 1, "}");
            Line(sb, indent, "}");
        }

        /// <summary>
        /// The <c>typeof</c> argument that keys a typed extension bag, or nothing for the untyped
        /// form. Each layer of a hierarchy gets its own, so the same field number can appear at more
        /// than one level without colliding.
        /// </summary>
        private static string ExtensionType(ProtoContractPlan contract)
            => contract.Extensible == ProtoExtensibleKind.Typed ? $", typeof({contract.TypeName})" : "";

        /// <summary>The member writes shared by <c>Write</c> and <c>WriteSubType</c>.</summary>
        private static void EmitWriteMembers(StringBuilder sb, int indent, ProtoContractPlan contract)
        {
            foreach (var member in contract.Members)
            {
                var number = member.FieldNumber.ToString(CultureInfo.InvariantCulture);
                // hoist to a local, as ref-emit does; the member could be a computed property
                Line(sb, indent, $"var tmp{number} = value.{member.Name};");

                if (member.Map.Factory is not null)
                {
                    Line(sb, indent, $"if (tmp{number} != null)");
                    Line(sb, indent, "{");
                    Line(sb, indent + 1, $"{Map(member)}.WriteMap(ref state, {number}, {MapFeatures(member)}, tmp{number}, {MapElementFeatures(member)}{MapSubSerializers(member)});");
                    Line(sb, indent, "}");
                    continue;
                }

                if (member.Repeated.Factory is not null)
                {
                    var writeRepeated = $"{Repeated(member)}.WriteRepeated(ref state, {number}, {RepeatedFeatures(member)}, tmp{number}{RepeatedSubSerializer(member)});";
                    if (member.Repeated.IsValueType)
                    {
                        Line(sb, indent, writeRepeated);
                        continue;
                    }
                    Line(sb, indent, $"if (tmp{number} != null)");
                    Line(sb, indent, "{");
                    Line(sb, indent + 1, writeRepeated);
                    Line(sb, indent, "}");
                    continue;
                }

                if (member.IsNullable && member.Kind == ProtoMemberKind.Message)
                {
                    // a nullable struct message: presence decides, and the unwrapped value goes
                    // straight to WriteMessage
                    Line(sb, indent, $"if (tmp{number}.HasValue)");
                    Line(sb, indent, "{");
                    Line(sb, indent + 1, $"state.WriteMessage<{member.TypeName}>({number}, {Features}.CategoryRepeated, tmp{number}.GetValueOrDefault(), this);");
                    Line(sb, indent, "}");
                    continue;
                }

                if (member.IsNullable)
                {
                    // presence decides, not value - so a nullable zero *is* written, unlike a plain
                    // zero. A declared default then nests inside, rather than replacing the test.
                    Line(sb, indent, $"if (tmp{number}.HasValue)");
                    Line(sb, indent, "{");
                    Line(sb, indent + 1, $"var val{number} = tmp{number}.GetValueOrDefault();");
                    if (member.DefaultLiteral is { } nullableDefault)
                    {
                        Line(sb, indent + 1, $"if (val{number} != {nullableDefault})");
                        Line(sb, indent + 1, "{");
                        EmitScalarWrite(sb, indent + 2, member, number, $"val{number}");
                        Line(sb, indent + 1, "}");
                    }
                    else
                    {
                        EmitScalarWrite(sb, indent + 1, member, number, $"val{number}");
                    }
                    Line(sb, indent, "}");
                    continue;
                }

                // a tuple writes every scalar unconditionally: it is rebuilt through a constructor,
                // so "absent" and "default" cannot be told apart on the way back in
                if (contract.IsTuple && member.Kind is not (ProtoMemberKind.String
                    or ProtoMemberKind.Bytes or ProtoMemberKind.Message))
                {
                    EmitScalarWrite(sb, indent, member, number, $"tmp{number}");
                    continue;
                }

                switch (member.Kind)
                {
                    // int32 has a convenience overload that writes its own field header; everything
                    // else needs the header emitting separately, as ref-emit does
                    case ProtoMemberKind.Int32 when member.DataFormat == ProtoDataFormat.Default:
                        var int32Write = $"state.WriteInt32Varint({number}, {ScalarValue(member, $"tmp{number}")});";
                        Line(sb, indent, member.IsRequired
                            ? int32Write
                            : $"if ({ScalarGuard(member, $"tmp{number}")}) {int32Write}");
                        break;
                    case ProtoMemberKind.Int32:
                    case ProtoMemberKind.Bool:
                    case ProtoMemberKind.SByte:
                    case ProtoMemberKind.Byte:
                    case ProtoMemberKind.Int16:
                    case ProtoMemberKind.UInt16:
                    case ProtoMemberKind.UInt32:
                    case ProtoMemberKind.Int64:
                    case ProtoMemberKind.UInt64:
                    case ProtoMemberKind.Single:
                    case ProtoMemberKind.Double:
                    case ProtoMemberKind.Char:
                        // IsRequired means field presence, so there is no test to emit at all
                        if (member.IsRequired)
                        {
                            EmitScalarWrite(sb, indent, member, number, $"tmp{number}");
                            break;
                        }
                        Line(sb, indent, $"if ({ScalarGuard(member, $"tmp{number}")})");
                        Line(sb, indent, "{");
                        EmitScalarWrite(sb, indent + 1, member, number, $"tmp{number}");
                        Line(sb, indent, "}");
                        break;
                    case ProtoMemberKind.String when member.DefaultLiteral is { } declared:
                        // the null test has to be explicit here: WriteString skips nulls itself, but
                        // we must not compare a null against the declared default
                        Line(sb, indent, $"if (tmp{number} != null && tmp{number} != {declared})");
                        Line(sb, indent, "{");
                        Line(sb, indent + 1, $"state.WriteString({number}, tmp{number});");
                        Line(sb, indent, "}");
                        break;
                    case ProtoMemberKind.String:
                        // no null test: WriteString(int, string) skips nulls itself
                        Line(sb, indent, $"state.WriteString({number}, tmp{number});");
                        break;
                    case ProtoMemberKind.Bytes:
                        // unlike WriteString, WriteBytes(byte[]) neither skips nulls nor writes its
                        // own field header, so both are explicit here
                        Line(sb, indent, $"if (tmp{number} != null)");
                        Line(sb, indent, "{");
                        Line(sb, indent + 1, $"state.WriteFieldHeader({number}, global::ProtoBuf.WireType.String);");
                        Line(sb, indent + 1, $"state.WriteBytes(tmp{number});");
                        Line(sb, indent, "}");
                        break;
                    case ProtoMemberKind.Message:
                        // likewise WriteMessage/WriteGroup(int, ...) skip nulls themselves. Group
                        // affects the *write* only - its read is an ordinary ReadMessage
                        var writeMessage = member.DataFormat == ProtoDataFormat.Group ? "WriteGroup" : "WriteMessage";
                        Line(sb, indent, $"state.{writeMessage}<{member.TypeName}>({number}, {Features}.CategoryRepeated, tmp{number}, this);");
                        break;
                }
            }

            // the kept-but-unrecognised fields go out after every declared member
            if (contract.Extensible != ProtoExtensibleKind.None)
            {
                Line(sb, indent, $"state.AppendExtensionData(value{ExtensionType(contract)});");
            }
        }

        /// <summary>
        /// A contract in a <c>[ProtoInclude]</c> hierarchy.
        /// </summary>
        /// <remarks>
        /// Both directions route through the <em>root</em>'s <c>ISubTypeSerializer</c>: that is what
        /// walks down the chain, writing each layer's own members and nesting the next layer inside a
        /// sub-type marker. So <c>ISerializer&lt;T&gt;</c> is a pair of one-line delegations for every
        /// type in the hierarchy, and the real work is in the sub-type pair, which sees only the
        /// members this layer declares.
        /// </remarks>
        private static void EmitSubTypeContract(StringBuilder sb, int indent, ProtoContractPlan contract, string root)
        {
            var self = $"{Serializers}.ISerializer<{contract.TypeName}>";
            var sub = $"{Serializers}.ISubTypeSerializer<{contract.TypeName}>";
            var rootSub = $"{Serializers}.ISubTypeSerializer<{root}>";
            // the root's ReadSubType returns the root type, so anything below it needs a cast back
            var cast = contract.TypeName == root ? "" : $"({contract.TypeName})";

            Line(sb, indent, $"{contract.TypeName} {self}.Read(ref global::ProtoBuf.ProtoReader.State state, {contract.TypeName} value)");
            Line(sb, indent + 1, $"=> {cast}(({rootSub})this).ReadSubType(ref state, "
                + $"global::ProtoBuf.Serializers.SubTypeState<{root}>.Create(state.Context, value));");
            sb.AppendLine();

            Line(sb, indent, $"void {self}.Write(ref global::ProtoBuf.ProtoWriter.State state, {contract.TypeName} value)");
            Line(sb, indent + 1, $"=> (({rootSub})this).WriteSubType(ref state, value);");
            sb.AppendLine();

            Line(sb, indent, $"void {sub}.WriteSubType(ref global::ProtoBuf.ProtoWriter.State state, {contract.TypeName} value)");
            Line(sb, indent, "{");
            if (contract.SubTypes.Count != 0)
            {
                // the runtime type decides which layer to nest; anything else is a type the model
                // was never told about
                Line(sb, indent + 1, "if (global::ProtoBuf.Meta.TypeModel.IsSubType(value))");
                Line(sb, indent + 1, "{");
                var keyword = "if";
                foreach (var subType in contract.SubTypes)
                {
                    var local = $"sub{subType.FieldNumber.ToString(CultureInfo.InvariantCulture)}";
                    Line(sb, indent + 2, $"{keyword} (value is {subType.TypeName} {local})");
                    Line(sb, indent + 2, "{");
                    Line(sb, indent + 3, $"state.WriteSubType({subType.FieldNumber.ToString(CultureInfo.InvariantCulture)}, {local}, this);");
                    Line(sb, indent + 2, "}");
                    keyword = "else if";
                }
                Line(sb, indent + 2, "else");
                Line(sb, indent + 2, "{");
                Line(sb, indent + 3, "global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);");
                Line(sb, indent + 2, "}");
                Line(sb, indent + 1, "}");
            }
            else if (!contract.IsSealed)
            {
                Line(sb, indent + 1, "global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);");
            }
            EmitWriteMembers(sb, indent + 1, contract);
            Line(sb, indent, "}");
            sb.AppendLine();

            Line(sb, indent, $"{contract.TypeName} {sub}.ReadSubType(ref global::ProtoBuf.ProtoReader.State state, "
                + $"global::ProtoBuf.Serializers.SubTypeState<{contract.TypeName}> value)");
            Line(sb, indent, "{");
            EmitReadLoop(sb, indent + 1, contract, "obj", contract.SubTypes);
            Line(sb, indent + 1, "return value.Value;");
            Line(sb, indent, "}");
        }

        /// <summary>
        /// The enum types that need an <c>ISerializerProxy</c>, keyed by type name.
        /// </summary>
        /// <remarks>
        /// Only *repeated* enums need one. A plain enum member is written inline (cast to its
        /// underlying type), but <c>RepeatedSerializer</c> resolves an <c>ISerializer&lt;TEnum&gt;</c>
        /// from the model instead — so without this a repeated enum throws "no serializer for type"
        /// at runtime.
        /// </remarks>
        private static SortedDictionary<string, ProtoMemberKind> EnumProxies(ProtoModelPlan plan)
        {
            var result = new SortedDictionary<string, ProtoMemberKind>(StringComparer.Ordinal);
            foreach (var contract in plan.Contracts)
            {
                foreach (var member in contract.Members)
                {
                    if (member.Repeated.Factory is null) continue;
                    if (member.EnumTypeName is { } name) result[name] = member.Kind;
                }
            }
            return result;
        }

        private static void EmitEnumProxies(StringBuilder sb, int indent, ProtoModelPlan plan)
        {
            foreach (var pair in EnumProxies(plan))
            {
                // EnumSerializer<TEnum> implements both ISerializer<TEnum> and ISerializer<TEnum?>,
                // so the nullable proxy returns the very same instance
                var create = $"{Serializers}.EnumSerializer.Create{UnderlyingName(pair.Value)}<{pair.Key}>()";
                sb.AppendLine();
                Line(sb, indent, $"{Serializers}.ISerializer<{pair.Key}> {Serializers}.ISerializerProxy<{pair.Key}>.Serializer");
                Line(sb, indent + 1, $"=> {create};");
                sb.AppendLine();
                Line(sb, indent, $"{Serializers}.ISerializer<{pair.Key}?> {Serializers}.ISerializerProxy<{pair.Key}?>.Serializer");
                Line(sb, indent + 1, $"=> {create};");
            }
        }

        /// <summary>The <c>EnumSerializer.CreateXxx</c> suffix for an enum's underlying type.</summary>
        private static string UnderlyingName(ProtoMemberKind kind) => kind switch
        {
            ProtoMemberKind.SByte => "SByte",
            ProtoMemberKind.Byte => "Byte",
            ProtoMemberKind.Int16 => "Int16",
            ProtoMemberKind.UInt16 => "UInt16",
            ProtoMemberKind.UInt32 => "UInt32",
            ProtoMemberKind.Int64 => "Int64",
            ProtoMemberKind.UInt64 => "UInt64",
            _ => "Int32",
        };

        /// <summary>The <c>RepeatedSerializer</c> factory for a collection member.</summary>
        private static string Repeated(ProtoMemberPlan member)
        {
            var arguments = member.Repeated.TakesCollectionType
                ? $"<{member.DeclaredTypeName}, {member.ElementTypeName}>"
                : $"<{member.ElementTypeName}>";
            return $"{Serializers}.RepeatedSerializer.{member.Repeated.Factory}{arguments}()";
        }

        /// <summary>
        /// The features for a repeated member: the *element's* wire type, plus the packed opt-out.
        /// </summary>
        /// <remarks>
        /// Packing is a compile-time decision, not a runtime one: ref-emit bakes
        /// <c>OptionPackedDisabled</c> into the constant and simply omits it when
        /// <c>[ProtoMember(IsPacked = true)]</c> is set. Unpacked is the default, and that named
        /// argument is not supported yet, so this is always the disabled form.
        /// </remarks>
        private static string RepeatedFeatures(ProtoMemberPlan member)
        {
            var result = $"{Features}.{ElementWireType(member)}";
            if (!member.IsPacked) result += $" | {Features}.OptionPackedDisabled";
            if (member.OverwriteList) result += $" | {Features}.OptionClearCollection";
            return result;
        }

        private static string ElementWireType(ProtoMemberPlan member) => member.DataFormat switch
        {
            ProtoDataFormat.ZigZag => "WireTypeSignedVarint",
            ProtoDataFormat.FixedSize => Is64Bit(member.Kind) ? "WireTypeFixed64" : "WireTypeFixed32",
            _ => member.Kind switch
            {
                ProtoMemberKind.Single => "WireTypeFixed32",
                ProtoMemberKind.Double => "WireTypeFixed64",
                ProtoMemberKind.String or ProtoMemberKind.Bytes or ProtoMemberKind.Message => "WireTypeString",
                _ => "WireTypeVarint",
            },
        };

        /// <summary>A message element needs us passed along as its serializer; a scalar does not.</summary>
        private static string RepeatedSubSerializer(ProtoMemberPlan member)
            => member.Kind == ProtoMemberKind.Message ? ", this" : "";

        /// <summary>
        /// The statement that stores a value into a member.
        /// </summary>
        /// <remarks>
        /// C# forbids assigning an <c>init</c>-only property after construction; IL does not, which
        /// is why ref-emit simply calls the setter. <c>[UnsafeAccessor]</c> is the equivalent, and
        /// unlike reflection it is resolved at publish time, so it stays AOT-safe.
        /// </remarks>
        private static string Assign(ProtoContractPlan contract, ProtoMemberPlan member,
            string target, string expression)
            => member.IsInitOnly && !contract.IsTuple
                ? $"{AccessorName(contract, member)}({(contract.IsValueType ? "ref value" : "value")}, {expression});"
                : $"{target} = {expression};";

        /// <summary>A name unique across the whole services type, since the accessors all live on it.</summary>
        private static string AccessorName(ProtoContractPlan contract, ProtoMemberPlan member)
        {
            var name = contract.TypeName;
            if (name.StartsWith("global::", StringComparison.Ordinal)) name = name.Substring(8);

            var sb = new StringBuilder("Set_");
            foreach (var c in name)
            {
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            }
            return sb.Append('_').Append(member.Name).ToString();
        }

        /// <summary>
        /// The <c>[UnsafeAccessor]</c> declarations for every init-only member in the model.
        /// </summary>
        private static void EmitAccessors(StringBuilder sb, int indent, ProtoModelPlan plan)
        {
            foreach (var contract in plan.Contracts)
            {
                foreach (var member in contract.Members)
                {
                    if (!member.IsInitOnly || contract.IsTuple) continue;

                    var self = contract.IsValueType ? $"ref {contract.TypeName}" : contract.TypeName;
                    sb.AppendLine();
                    Line(sb, indent, "[global::System.Runtime.CompilerServices.UnsafeAccessor("
                        + "global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, "
                        + $"Name = \"set_{member.Name}\")]");
                    Line(sb, indent, $"private static extern void {AccessorName(contract, member)}("
                        + $"{self} target, {member.DeclaredTypeName} value);");
                }
            }
        }

        /// <summary>The <c>MapSerializer</c> factory for a dictionary member.</summary>
        private static string Map(ProtoMemberPlan member)
        {
            var map = member.Map;
            var arguments = map.TakesCollectionType
                ? $"<{member.DeclaredTypeName}, {map.KeyTypeName}, {map.ValueTypeName}>"
                : $"<{map.KeyTypeName}, {map.ValueTypeName}>";
            return $"{Serializers}.MapSerializer.{map.Factory}{arguments}()";
        }

        /// <summary>
        /// The features for a map member: the map is always length-prefixed (or a group), and the
        /// key and value wire types are passed separately.
        /// </summary>
        /// <remarks>
        /// <c>DataFormat</c> selects the root wire type and nothing else — <c>Group</c> is the only
        /// value that changes anything, since a map is length-prefixed either way. The per-key and
        /// per-value formats come from <c>[ProtoMap]</c>, which is refused.
        /// <c>OptionFailOnDuplicateKey</c> rides on whether the shape is a real protobuf <c>map</c>.
        /// </remarks>
        private static string MapFeatures(ProtoMemberPlan member)
        {
            var result = member.DataFormat == ProtoDataFormat.Group
                ? $"{Features}.WireTypeStartGroup"
                : $"{Features}.WireTypeString";
            if (!member.IsPacked) result += $" | {Features}.OptionPackedDisabled";
            if (member.OverwriteList) result += $" | {Features}.OptionClearCollection";
            if (!member.Map.IsValidProtobufMap) result += $" | {Features}.OptionFailOnDuplicateKey";
            return result;
        }

        private static string MapElementFeatures(ProtoMemberPlan member)
            => $"{Features}.{MapWireType(member.Map.KeyKind)}, {Features}.{MapWireType(member.Map.ValueKind)}";

        private static string MapWireType(ProtoMemberKind kind) => kind switch
        {
            ProtoMemberKind.Single => "WireTypeFixed32",
            ProtoMemberKind.Double => "WireTypeFixed64",
            ProtoMemberKind.String or ProtoMemberKind.Bytes or ProtoMemberKind.Message => "WireTypeString",
            _ => "WireTypeVarint",
        };

        /// <summary>
        /// A message key or value needs us passed along as its serializer. The two are positional, so
        /// a message value alone still has to pass a null for the key.
        /// </summary>
        private static string MapSubSerializers(ProtoMemberPlan member)
        {
            var key = member.Map.KeyKind == ProtoMemberKind.Message;
            var value = member.Map.ValueKind == ProtoMemberKind.Message;
            if (value) return key ? ", this, this" : ", null, this";
            return key ? ", this" : "";
        }

        /// <summary>
        /// How a fresh instance is made: normally <c>new</c>, but SkipConstructor bypasses every
        /// constructor, exactly as ref-emit does.
        /// </summary>
        private static string Construct(ProtoContractPlan contract)
            => contract.SkipConstructor
                ? $"({contract.TypeName})global::ProtoBuf.BclHelpers.GetUninitializedObject(typeof({contract.TypeName}))"
                : $"new {contract.TypeName}()";

        /// <summary>
        /// The unguarded write for a scalar: the caller owns whatever test precedes it.
        /// </summary>
        private static void EmitScalarWrite(StringBuilder sb, int indent, ProtoMemberPlan member, string number, string local)
        {
            var expression = ScalarValue(member, local);
            // the Int32 shortcut writes its own varint header, so it only applies at the default format
            if (member.Kind == ProtoMemberKind.Int32 && member.DataFormat == ProtoDataFormat.Default)
            {
                Line(sb, indent, $"state.WriteInt32Varint({number}, {expression});");
            }
            else
            {
                Line(sb, indent, $"state.WriteFieldHeader({number}, global::ProtoBuf.WireType.{ScalarWireType(member)});");
                Line(sb, indent, $"state.{ScalarSuffix(member.Kind, "Write")}({expression});");
            }
        }

        /// <summary>
        /// The value handed to the write method: an enum needs casting down to its underlying type,
        /// while a char converts to ushort implicitly.
        /// </summary>
        private static string ScalarValue(ProtoMemberPlan member, string local)
            => member.EnumTypeName is null ? local : $"({UnderlyingKeyword(member.Kind)}){local}";

        /// <summary>
        /// The value read back: cast up to the enum type, or to char, since the read methods deal in
        /// the underlying scalar.
        /// </summary>
        /// <summary>ZigZag reads need a wire-type hint first; no other format does.</summary>
        private static string? ScalarReadHint(ProtoMemberPlan member)
            => member.DataFormat == ProtoDataFormat.ZigZag
                ? "state.Hint(global::ProtoBuf.WireType.SignedVarint);" : null;

        private static string ScalarRead(ProtoMemberPlan member)
        {
            var call = $"state.{ScalarSuffix(member.Kind, "Read")}()";
            if (member.EnumTypeName is { } enumType) return $"({enumType}){call}";
            return member.Kind == ProtoMemberKind.Char ? $"(char){call}" : call;
        }

        private static string UnderlyingKeyword(ProtoMemberKind kind) => kind switch
        {
            ProtoMemberKind.SByte => "sbyte",
            ProtoMemberKind.Byte => "byte",
            ProtoMemberKind.Int16 => "short",
            ProtoMemberKind.UInt16 => "ushort",
            ProtoMemberKind.Int32 => "int",
            ProtoMemberKind.UInt32 => "uint",
            ProtoMemberKind.Int64 => "long",
            ProtoMemberKind.UInt64 => "ulong",
            _ => kind.ToString(),
        };

        /// <summary>The <c>ReadXxx</c>/<c>WriteXxx</c> name for a scalar kind.</summary>
        private static string ScalarSuffix(ProtoMemberKind kind, string prefix) => prefix + (kind switch
        {
            ProtoMemberKind.Bool => "Boolean",
            ProtoMemberKind.Single => "Single",
            ProtoMemberKind.Double => "Double",
            ProtoMemberKind.Char => "UInt16", // a char goes on the wire as a ushort
            _ => kind.ToString(), // SByte, Byte, Int16, UInt16, Int32, UInt32, Int64, UInt64
        });

        private static string ScalarWireType(ProtoMemberPlan member) => member.DataFormat switch
        {
            // ZigZag is always the signed varint; FixedSize picks its width from the member
            ProtoDataFormat.ZigZag => "SignedVarint",
            ProtoDataFormat.FixedSize => Is64Bit(member.Kind) ? "Fixed64" : "Fixed32",
            _ => member.Kind switch
            {
                ProtoMemberKind.Single => "Fixed32",
                ProtoMemberKind.Double => "Fixed64",
                _ => "Varint",
            },
        };

        private static bool Is64Bit(ProtoMemberKind kind)
            => kind is ProtoMemberKind.Int64 or ProtoMemberKind.UInt64 or ProtoMemberKind.Double;

        /// <summary>
        /// The "is this worth writing" test: a member equal to its default is omitted, where the
        /// default is <c>[DefaultValue]</c> if declared and the type's own default otherwise.
        /// </summary>
        private static string ScalarGuard(ProtoMemberPlan member, string local)
        {
            // note: IsRequired is handled by the callers omitting the test entirely, rather than
            // by returning "true" here - generated code is read by people
            if (member.DefaultLiteral is { } declared) return $"{local} != {declared}";

            // an enum compares against its own zero, which need not have a declared name
            if (member.EnumTypeName is { } enumType) return $"{local} != default({enumType})";

            return member.Kind switch
            {
                ProtoMemberKind.Bool => local,
                ProtoMemberKind.Single => $"{local} != 0f",
                ProtoMemberKind.Double => $"{local} != 0d",
                _ => $"{local} != 0",
            };
        }

        private static void Line(StringBuilder sb, int indent, string text)
            => sb.Append(' ', indent * 4).AppendLine(text);
    }
}
