#nullable enable
using ProtoBuf.BuildTools.Internal.Aot;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace ProtoBuf.BuildTools.Generators
{
    partial class ProtoModelGenerator
    {
        private const string Serializers = "global::ProtoBuf.Serializers";
        private const string Features = Serializers + ".SerializerFeatures";
        private const string ServicesTypeName = "ProtoBufGeneratedServices";

        private const string MemberTypes = "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes";

        /// <summary>Mirrors <c>ProtoBuf.Internal.DynamicAccess.ContractType</c>, which is internal.</summary>
        private const string DynamicallyAccessedMembers
            = "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers("
            + MemberTypes + ".PublicConstructors | " + MemberTypes + ".NonPublicConstructors | "
            + MemberTypes + ".PublicParameterlessConstructor | "
            + MemberTypes + ".PublicProperties | " + MemberTypes + ".NonPublicProperties | "
            + MemberTypes + ".PublicFields | " + MemberTypes + ".NonPublicFields | "
            + MemberTypes + ".PublicMethods | " + MemberTypes + ".NonPublicMethods | "
            + MemberTypes + ".PublicNestedTypes | " + MemberTypes + ".NonPublicNestedTypes)";

        /// <summary>
        /// Render a plan as the partial half of the user's model class.
        /// </summary>
        /// <remarks>
        /// The shape here is copied from what ref-emit produces for the same contracts (see
        /// <c>src/AotRefGen</c>), rather than invented; the differences are deliberate - a nested
        /// services type rather than a mangled top-level one, and real explicit-interface members.
        /// </remarks>
        private static string Emit(ProtoModelPlan plan)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>")
              .AppendLine("#nullable disable")
              .AppendLine("#pragma warning disable CS1591")
              .AppendLine();

            const int indent = 0;
            if (plan.Namespace is not null)
            {
                sb.AppendLine($"namespace {plan.Namespace};").AppendLine();
            }

            Line(sb, indent, $"partial class {plan.TypeName}");
            Line(sb, indent, "{");

            // the base declares [DynamicallyAccessedMembers(DynamicAccess.ContractType)] on T, and an
            // override must restate it exactly or trim analysis reports IL2095. DynamicAccess is
            // internal to protobuf-net, so the flags are spelled out; keep them in step with
            // protobuf-net.Core/Internal/DynamicallyAccessedMembersAttribute.cs. src/AotSmoke is what
            // catches any drift, since IL2095 reappears the moment the two disagree.
            var typeParameter = plan.AnnotateTrimming ? $"[{DynamicallyAccessedMembers}] T" : "T";
            Line(sb, indent + 1, $"protected sealed override {Serializers}.ISerializer<T> GetSerializer<{typeParameter}>()");
            Line(sb, indent + 2, $"=> {Serializers}.SerializerCache.Get<{ServicesTypeName}, T>();");
            sb.AppendLine();

            Line(sb, indent + 1, $"private sealed class {ServicesTypeName}");
            var prefix = ':';
            foreach (var contract in plan.Contracts)
            {
                // a contract with a hand-written serializer is *proxied*, never implemented
                Line(sb, indent + 2, contract.ExternalSerializerTypeName is null
                    ? $"{prefix} {Serializers}.ISerializer<{contract.TypeName}>"
                    : $"{prefix} {Serializers}.ISerializerProxy<{contract.TypeName}>");
                prefix = ',';
                if (contract.RootTypeName is not null)
                {
                    Line(sb, indent + 2, $", {Serializers}.ISubTypeSerializer<{contract.TypeName}>");
                }
                if (contract.SkipConstructor)
                {
                    Line(sb, indent + 2, $", {Serializers}.IFactory<{contract.TypeName}>");
                }
            }
            foreach (var enumType in EnumProxies(plan))
            {
                Line(sb, indent + 2, $", {Serializers}.ISerializerProxy<{enumType.Key}>");
                Line(sb, indent + 2, $", {Serializers}.ISerializerProxy<{enumType.Key}?>");
            }
            foreach (var collection in CollectionProxies(plan))
            {
                Line(sb, indent + 2, $", {Serializers}.ISerializerProxy<{collection.Key}>");
            }
            Line(sb, indent + 1, "{");

            EmitExternalCategoryAsserts(sb, indent + 2, plan);

            var first = true;
            foreach (var contract in plan.Contracts)
            {
                if (!first) sb.AppendLine();
                first = false;
                EmitContract(sb, indent + 2, contract);
            }

            EmitEnumProxies(sb, indent + 2, plan);
            EmitCollectionProxies(sb, indent + 2, plan);
            EmitAccessors(sb, indent + 2, plan);

            Line(sb, indent + 1, "}");
            Line(sb, indent, "}");
            return sb.ToString();
        }

        private static void EmitContract(StringBuilder sb, int indent, ProtoContractPlan contract)
        {
            var self = $"{Serializers}.ISerializer<{contract.TypeName}>";

            // a hand-written serializer replaces the body entirely - including Features - so we hand
            // it out rather than implementing ISerializer<T> ourselves at all
            if (contract.ExternalSerializerTypeName is { } external)
            {
                Line(sb, indent, $"{self} {Serializers}.ISerializerProxy<{contract.TypeName}>.Serializer");
                Line(sb, indent + 1, $"=> {Serializers}.SerializerCache.Get<{external}, {contract.TypeName}>();");
                return;
            }

            Line(sb, indent, $"{Features} {self}.Features");
            Line(sb, indent + 1, $"=> {Features}.CategoryMessage | {Features}."
                + (contract.IsGroup ? "WireTypeStartGroup" : "WireTypeString") + ";");
            sb.AppendLine();

            if (contract.SkipConstructor)
            {
                Line(sb, indent, $"{contract.TypeName} {Serializers}.IFactory<{contract.TypeName}>.Create(global::ProtoBuf.ISerializationContext context)");
                Line(sb, indent + 1, $"=> {Construct(contract)};");
                sb.AppendLine();
            }

            if (contract.RootTypeName is { } root)
            {
                EmitSubTypeContract(sb, indent, contract, root);
                return;
            }


            // when the surrogate carries a serializer of its own there are no members to inline, so
            // we convert and hand over to it - the shape a well-known-type surrogate needs
            if (contract.SurrogateSerializer is { } surrogateSerializer)
            {
                Line(sb, indent, $"{contract.TypeName} {self}.Read(ref global::ProtoBuf.ProtoReader.State state, {contract.TypeName} value)");
                Line(sb, indent, "{");
                Line(sb, indent + 1, $"var surrogate = {ToSurrogate(contract, "value")};");
                Line(sb, indent + 1, $"surrogate = {surrogateSerializer}.Read(ref state, surrogate);");
                Line(sb, indent + 1, $"return {ToUnderlying(contract, "surrogate")};");
                Line(sb, indent, "}");
                sb.AppendLine();

                Line(sb, indent, $"void {self}.Write(ref global::ProtoBuf.ProtoWriter.State state, {contract.TypeName} value)");
                Line(sb, indent, "{");
                Line(sb, indent + 1, $"var surrogate = {ToSurrogate(contract, "value")};");
                Line(sb, indent + 1, $"{surrogateSerializer}.Write(ref state, surrogate);");
                Line(sb, indent, "}");
                return;
            }

            // otherwise a surrogate contract's serializer *is* the surrogate's, with a conversion at
            // each end; everything below then works on the converted local rather than on `value`
            var surrogate = contract.SurrogateTypeName;
            var instance = surrogate is null ? "value" : "surrogate";
            var bodyType = surrogate ?? contract.TypeName;

            Line(sb, indent, $"{contract.TypeName} {self}.Read(ref global::ProtoBuf.ProtoReader.State state, {contract.TypeName} value)");
            Line(sb, indent, "{");
            if (surrogate is not null)
            {
                Line(sb, indent + 1, $"var {instance} = {ToSurrogate(contract, "value")};");
            }
            if (contract.IsTuple)
            {
                // a tuple is rebuilt through its constructor at the end, so the read works on locals;
                // they are seeded from the incoming value so repeated occurrences still merge
                foreach (var member in contract.Members)
                {
                    Line(sb, indent + 1, $"{member.DeclaredTypeName} arg{member.FieldNumber} = default;");
                }
                if (!contract.IsValueType)
                {
                    Line(sb, indent + 1, "if (value != null)");
                    Line(sb, indent + 1, "{");
                    foreach (var member in contract.Members)
                    {
                        Line(sb, indent + 2, $"arg{member.FieldNumber} = value.{member.Name};");
                    }
                    Line(sb, indent + 1, "}");
                }
                else
                {
                    foreach (var member in contract.Members)
                    {
                        Line(sb, indent + 1, $"arg{member.FieldNumber} = value.{member.Name};");
                    }
                }
            }
            // an abstract type with no sub-types cannot be constructed at all; ref-emit still emits
            // a serializer for it, whose read throws - which is what keeps its *referrers* working
            // while the member stays null
            else if (contract.IsAbstract)
            {
                Line(sb, indent + 1, $"if ({instance} is null) global::ProtoBuf.Meta.TypeModel"
                    + $".ThrowCannotCreateInstance(typeof({bodyType}));");
            }
            // a struct arrives by value and is never null, so there is nothing to construct
            else if (!contract.IsValueType)
            {
                Line(sb, indent + 1, $"{instance} ??= {Construct(contract, bodyType)};");
            }
            EmitCallback(sb, indent + 1, contract, instance, ProtoCallbackKind.BeforeDeserialize);
            EmitReadLoop(sb, indent + 1, contract, instance);
            if (contract.IsTuple)
            {
                var arguments = string.Join(", ", contract.Members.Select(static x => $"arg{x.FieldNumber}"));
                Line(sb, indent + 1, contract.IsTupleLiteral
                    ? $"{instance} = ({arguments});"
                    : $"{instance} = new {bodyType}({arguments});");
            }
            EmitCallback(sb, indent + 1, contract, instance, ProtoCallbackKind.AfterDeserialize);
            if (surrogate is not null) Line(sb, indent + 1, $"value = {ToUnderlying(contract, instance)};");
            Line(sb, indent + 1, "return value;");
            Line(sb, indent, "}");
            sb.AppendLine();

            Line(sb, indent, $"void {self}.Write(ref global::ProtoBuf.ProtoWriter.State state, {contract.TypeName} value)");
            Line(sb, indent, "{");
            if (surrogate is not null) Line(sb, indent + 1, $"var {instance} = {ToSurrogate(contract, "value")};");
            // ThrowUnexpectedSubtype is constrained to reference types, and a struct, a sealed type
            // and a tuple all rule sub-types out at compile time - ref-emit omits it for each. Note
            // it tests the *surrogate*, which is what carries any sub-types. IgnoreUnknownSubTypes
            // asks for the same omission outright: it is assertKnownType: false in TypeSerializer.
            if (!contract.IsValueType && !contract.IsTuple && !contract.IsSealed
                && !contract.IgnoreUnknownSubTypes)
            {
                Line(sb, indent + 1, $"global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype({instance});");
            }
            EmitCallback(sb, indent + 1, contract, instance, ProtoCallbackKind.BeforeSerialize);
            EmitWriteMembers(sb, indent + 1, contract, instance);
            EmitCallback(sb, indent + 1, contract, instance, ProtoCallbackKind.AfterSerialize);
            Line(sb, indent, "}");
        }

        /// <summary>
        /// A serialization callback, if the contract declares one for this point.
        /// </summary>
        /// <remarks>
        /// The placement is ref-emit's: the "before" hooks fire after construction but before the
        /// field loop, and the "after" hooks after it, so a deserialization callback sees a fully
        /// populated instance. The <c>System.Runtime.Serialization</c> spelling takes a
        /// <c>StreamingContext</c>, which comes from the state.
        /// </remarks>
        private static void EmitCallback(StringBuilder sb, int indent, ProtoContractPlan contract,
            string instance, ProtoCallbackKind kind)
        {
            var callbacks = contract.Callbacks;
            if (callbacks.Count <= (int)kind) return;

            var callback = callbacks[(int)kind];
            if (callback.MethodName is not { } method) return;

            var argument = callback.TakesContext
                ? "global::ProtoBuf.SerializationContext.AsStreamingContext(state.Context)"
                : "";
            Line(sb, indent, $"{instance}.{method}({argument});");
        }

        /// <summary>
        /// The field-dispatch loop shared by <c>Read</c> and <c>ReadSubType</c>.
        /// </summary>
        /// <param name="instance">
        /// What the members hang off. A sub-type read works through <c>SubTypeState&lt;T&gt;</c>,
        /// so the instance has to be hoisted out of it - which also constructs it on demand.
        /// </param>
        private static void EmitReadLoop(StringBuilder sb, int indent, ProtoContractPlan contract,
            string instance, EquatableArray<ProtoSubTypePlan> subTypes = default,
            bool fromSubTypeState = false)
        {
            // an empty message is legal protobuf, and has nothing to switch on
            var unknown = contract.Extensible == ProtoExtensibleKind.None
                ? "state.SkipField();"
                : $"state.AppendExtensionData({(instance == "value" ? "value" : "value.Value")}{ExtensionType(contract)});";
            if (contract.Members.Count == 0 && subTypes.Count == 0)
            {
                Line(sb, indent, "int field;");
                Line(sb, indent, "while ((field = state.ReadFieldHeader()) > 0)");
                Line(sb, indent, "{");
                Line(sb, indent + 1, unknown);
                Line(sb, indent, "}");
                return;
            }

            Line(sb, indent, "int field;");
            Line(sb, indent, "while ((field = state.ReadFieldHeader()) > 0)");
            Line(sb, indent, "{");
            Line(sb, indent + 1, "switch (field)");
            Line(sb, indent + 1, "{");
            foreach (var member in contract.Members)
            {
                var number = member.FieldNumber.ToString(CultureInfo.InvariantCulture);
                // a tuple reads into the locals it will pass to the constructor, not into the member
                var target = contract.IsTuple ? $"arg{number}" : MemberAccess(contract, member, instance);
                Line(sb, indent + 2, $"case {number}:");
                Line(sb, indent + 2, "{");
                // a sub-type read holds the instance inside SubTypeState, and reading it is what
                // constructs it - so it is hoisted per case, exactly as ref-emit does
                if (fromSubTypeState) Line(sb, indent + 3, $"var {instance} = value.Value;");
                if (member.Map.Factory is not null)
                {
                    // same merge shape as a collection, but the key and value features - and any
                    // sub-serializers they need - ride alongside
                    Line(sb, indent + 3, $"var tmp{number} = {target};");
                    var readMap = $"{Map(member)}.ReadMap(ref state, {MapFeatures(member)}, tmp{number}, {MapElementFeatures(member)}{MapSubSerializers(member)})";
                    if (member.IsReadOnly)
                    {
                        Line(sb, indent + 3, $"{readMap};");
                    }
                    else
                    {
                        Line(sb, indent + 3, $"tmp{number} = {readMap};");
                        Line(sb, indent + 3, $"if (tmp{number} != null) {Assign(contract, member, instance, target, $"tmp{number}")}");
                    }
                    Line(sb, indent + 3, "break;");
                    Line(sb, indent + 2, "}");
                    continue;
                }
                if (member.Repeated.Factory is not null)
                {
                    // same merge shape as a sub-message: the existing collection is passed in, and
                    // the result assigned back only if non-null
                    Line(sb, indent + 3, $"var tmp{number} = {target};");
                    var readRepeated = $"{Repeated(member)}.ReadRepeated(ref state, {RepeatedFeatures(member)}, tmp{number}{RepeatedSubSerializer(member)})";
                    if (member.IsReadOnly)
                    {
                        Line(sb, indent + 3, $"{readRepeated};");
                    }
                    else
                    {
                        Line(sb, indent + 3, $"tmp{number} = {readRepeated};");
                        // ImmutableArray<T> is a struct and can never be null
                        Line(sb, indent + 3, member.Repeated.IsValueType
                            ? Assign(contract, member, instance, target, $"tmp{number}")
                            : $"if (tmp{number} != null) {Assign(contract, member, instance, target, $"tmp{number}")}");
                    }
                    Line(sb, indent + 3, "break;");
                    Line(sb, indent + 2, "}");
                    continue;
                }
                // a lone wrapped value has its own API: the extra message layer is not expressible
                // as features on an ordinary read, so ReadAny/WriteAny handle it
                if (member.WrappedValue)
                {
                    Line(sb, indent + 3, $"var tmp{number} = {target};");
                    Line(sb, indent + 3, $"tmp{number} = state.ReadAny<{member.DeclaredTypeName}>({WrappedFeatures(member, forRead: true)}, tmp{number}{WrappedSerializer(member)});");
                    Line(sb, indent + 3, NullableTarget(member)
                        ? $"if (tmp{number} != null) {Assign(contract, member, instance, target, $"tmp{number}")}"
                        : Assign(contract, member, instance, target, $"tmp{number}"));
                    Line(sb, indent + 3, "break;");
                    Line(sb, indent + 2, "}");
                    continue;
                }
                switch (member.Kind)
                {
                    case ProtoMemberKind.Bool:
                    case ProtoMemberKind.SByte:
                    case ProtoMemberKind.Byte:
                    case ProtoMemberKind.Int16:
                    case ProtoMemberKind.UInt16:
                    case ProtoMemberKind.Int32:
                    case ProtoMemberKind.UInt32:
                    case ProtoMemberKind.Int64:
                    case ProtoMemberKind.UInt64:
                    case ProtoMemberKind.Single:
                    case ProtoMemberKind.Double:
                    case ProtoMemberKind.Char:
                    // the BCL types read through BclHelpers, which needs no hint and no cast
                    case ProtoMemberKind.DateTime:
                    case ProtoMemberKind.TimeSpan:
                    case ProtoMemberKind.Guid:
                    case ProtoMemberKind.Decimal:
                    case ProtoMemberKind.DateOnly:
                    case ProtoMemberKind.TimeOnly:
                    case ProtoMemberKind.IntPtr:
                    case ProtoMemberKind.UIntPtr:
                    case ProtoMemberKind.Parseable:
                        if (ScalarReadHint(member) is { } hint) Line(sb, indent + 3, hint);
                        Line(sb, indent + 3, Assign(contract, member, instance, target, ScalarRead(member, discard: member.IsReadOnly)));
                        break;
                    case ProtoMemberKind.Uri:
                        // an empty string means null, and the assignment is guarded on that rather
                        // than on the string itself - ReadString never returns null for a present field
                        Line(sb, indent + 3, $"var tmp{number} = state.ReadString();");
                        if (member.IsReadOnly)
                        {
                            Line(sb, indent + 3, $"_ = tmp{number}.Length != 0 ? {NewUri($"tmp{number}")} : null;");
                            break;
                        }
                        Line(sb, indent + 3, $"if (tmp{number}.Length != 0) "
                            + Assign(contract, member, instance, target, NewUri($"tmp{number}")));
                        break;
                    case ProtoMemberKind.String when member.IsReadOnly:
                        Line(sb, indent + 3, "state.ReadString();");
                        break;
                    case ProtoMemberKind.String:
                        // a null string leaves the existing value alone, matching ref-emit
                        Line(sb, indent + 3, $"var tmp{number} = state.ReadString();");
                        Line(sb, indent + 3, $"if (tmp{number} != null) {Assign(contract, member, instance, target, $"tmp{number}")}");
                        break;
                    case ProtoMemberKind.Bytes when member.OverwriteList:
                        // "bytes" is a scalar here, but OverwriteList still reaches BlobSerializer,
                        // where it selects AppendBytes(default) over AppendBytes(existing) - replace
                        // rather than append. RequiresOldValue is false with it set, so ref-emit does
                        // not read the current value at all; the explicit default() is because the
                        // AppendBytes overloads (array, Memory, ReadOnlyMemory, ArraySegment) make a
                        // bare `default` ambiguous.
                        if (member.IsReadOnly)
                        {
                            Line(sb, indent + 3, $"state.AppendBytes(default({member.DeclaredTypeName}));");
                            break;
                        }
                        Line(sb, indent + 3, $"var tmp{number} = state.AppendBytes(default({member.DeclaredTypeName}));");
                        Line(sb, indent + 3, member.MemberIsValueType
                            ? Assign(contract, member, instance, target, $"tmp{number}")
                            : $"if (tmp{number} != null) {Assign(contract, member, instance, target, $"tmp{number}")}");
                        break;
                    case ProtoMemberKind.Bytes:
                        // AppendBytes, not ReadBytes: repeated occurrences concatenate onto the
                        // existing array rather than replacing it
                        Line(sb, indent + 3, $"var tmp{number} = {target};");
                        if (member.IsReadOnly)
                        {
                            Line(sb, indent + 3, $"state.AppendBytes(tmp{number});");
                            break;
                        }
                        Line(sb, indent + 3, $"tmp{number} = state.AppendBytes(tmp{number});");
                        // a struct shape can never come back null, and cannot be compared to null
                        Line(sb, indent + 3, member.MemberIsValueType
                            ? Assign(contract, member, instance, target, $"tmp{number}")
                            : $"if (tmp{number} != null) {Assign(contract, member, instance, target, $"tmp{number}")}");
                        break;
                    // a scalar-category hand-written serializer: the member is not a sub-message at
                    // all, so it is read straight through the serializer with no ReadMessage framing
                    case ProtoMemberKind.Message when member.SubSerializerIsScalar:
                        Line(sb, indent + 3, $"var tmp{number} = {target};");
                        Line(sb, indent + 3, $"tmp{number} = {SubSerializer(member)}.Read(ref state, tmp{number});");
                        Line(sb, indent + 3, Assign(contract, member, instance, target, $"tmp{number}"));
                        break;
                    // in all three cases the *existing* value is passed in, so repeated occurrences
                    // merge rather than replace; and the category is Repeated, not Message
                    case ProtoMemberKind.Message when member.IsNullable:
                        // a nullable struct message: seed from the current value, assign the result
                        // straight back - the read cannot produce a null
                        Line(sb, indent + 3, $"var tmp{number} = {target}.GetValueOrDefault();");
                        Line(sb, indent + 3, Assign(contract, member, instance, target, $"state.ReadMessage<{member.TypeName}>({Features}.CategoryRepeated, tmp{number}, {SubSerializer(member)})"));
                        break;
                    case ProtoMemberKind.Message when member.MemberIsValueType:
                        Line(sb, indent + 3, $"var tmp{number} = {target};");
                        Line(sb, indent + 3, Assign(contract, member, instance, target, $"state.ReadMessage<{member.TypeName}>({Features}.CategoryRepeated, tmp{number}, {SubSerializer(member)})"));
                        break;
                    case ProtoMemberKind.Message:
                        Line(sb, indent + 3, $"var tmp{number} = {target};");
                        if (member.IsReadOnly)
                        {
                            // the instance it already holds is what gets populated
                            Line(sb, indent + 3, $"state.ReadMessage<{member.TypeName}>({Features}.CategoryRepeated, tmp{number}, {SubSerializer(member)});");
                            break;
                        }
                        Line(sb, indent + 3, $"tmp{number} = state.ReadMessage<{member.TypeName}>({Features}.CategoryRepeated, tmp{number}, {SubSerializer(member)});");
                        Line(sb, indent + 3, $"if (tmp{number} != null) {Assign(contract, member, instance, target, $"tmp{number}")}");
                        break;
                }
                // the presence flag is set whatever the value was - note it sits *outside* any null
                // test the assignment itself carries
                if (member.SpecifiedMember is { } specified)
                {
                    Line(sb, indent + 3, $"{instance}.{specified} = true;");
                }
                Line(sb, indent + 3, "break;");
                Line(sb, indent + 2, "}");
            }
            // a derived layer arrives as a nested sub-item at its own field number; reading it hands
            // the whole SubTypeState down, so the instance is constructed at the deepest layer
            foreach (var subType in subTypes)
            {
                var number = subType.FieldNumber.ToString(CultureInfo.InvariantCulture);
                Line(sb, indent + 2, $"case {number}:");
                Line(sb, indent + 3, $"value.ReadSubType<{subType.TypeName}>(ref state, this);");
                Line(sb, indent + 3, "break;");
            }
            // an extensible contract keeps what it does not recognise rather than discarding it; the
            // instance has to be materialised for that, which is why the sub-type form reads
            // value.Value here rather than using the per-case local
            Line(sb, indent + 2, "default:");
            Line(sb, indent + 3, unknown);
            Line(sb, indent + 3, "break;");
            Line(sb, indent + 1, "}");
            Line(sb, indent, "}");
        }

        /// <summary>
        /// The <c>typeof</c> argument that keys a typed extension bag, or nothing for the untyped
        /// form. Each layer of a hierarchy gets its own, so the same field number can appear at more
        /// than one level without colliding.
        /// </summary>
        private static string ExtensionType(ProtoContractPlan contract)
            => contract.Extensible == ProtoExtensibleKind.Typed ? $", typeof({contract.TypeName})" : "";

        /// <summary>The member writes shared by <c>Write</c> and <c>WriteSubType</c>.</summary>
        private static void EmitWriteMembers(StringBuilder sb, int baseIndent, ProtoContractPlan contract,
            string instance = "value")
        {
            foreach (var member in contract.Members)
            {
                // a conditional member wraps its whole write, and *replaces* the trivial-value guard
                // rather than adding to it - see WriteGuardSuppressed
                var condition = member.WriteCondition;
                if (condition is not null)
                {
                    Line(sb, baseIndent, $"if ({instance}.{condition})");
                    Line(sb, baseIndent, "{");
                }
                var indent = condition is null ? baseIndent : baseIndent + 1;

                var number = member.FieldNumber.ToString(CultureInfo.InvariantCulture);
                // hoist to a local, as ref-emit does; the member could be a computed property
                Line(sb, indent, $"var tmp{number} = {MemberAccess(contract, member, instance)};");

                // WriteAny handles the null itself, so there is no guard - not even for a null int?
                if (member.WrappedValue && member.Repeated.Factory is null && member.Map.Factory is null)
                {
                    Line(sb, indent, $"state.WriteAny<{member.DeclaredTypeName}>({number}, {WrappedFeatures(member)}, tmp{number}{WrappedSerializer(member)});");
                    goto written;
                }

                if (member.Map.Factory is not null)
                {
                    Line(sb, indent, $"if (tmp{number} != null)");
                    Line(sb, indent, "{");
                    Line(sb, indent + 1, $"{Map(member)}.WriteMap(ref state, {number}, {MapFeatures(member)}, tmp{number}, {MapElementFeatures(member)}{MapSubSerializers(member)});");
                    Line(sb, indent, "}");
                    goto written;
                }

                if (member.Repeated.Factory is not null)
                {
                    var writeRepeated = $"{Repeated(member)}.WriteRepeated(ref state, {number}, {RepeatedFeatures(member)}, tmp{number}{RepeatedSubSerializer(member)});";
                    if (member.Repeated.IsValueType)
                    {
                        Line(sb, indent, writeRepeated);
                        goto written;
                    }
                    Line(sb, indent, $"if (tmp{number} != null)");
                    Line(sb, indent, "{");
                    Line(sb, indent + 1, writeRepeated);
                    Line(sb, indent, "}");
                    goto written;
                }

                if (member.IsNullable && member.Kind == ProtoMemberKind.Message)
                {
                    // a nullable struct message: presence decides, and the unwrapped value goes
                    // straight to WriteMessage
                    Line(sb, indent, $"if (tmp{number}.HasValue)");
                    Line(sb, indent, "{");
                    Line(sb, indent + 1, $"state.WriteMessage<{member.TypeName}>({number}, {Features}.CategoryRepeated, tmp{number}.GetValueOrDefault(), {SubSerializer(member)});");
                    Line(sb, indent, "}");
                    goto written;
                }

                if (member.IsNullable)
                {
                    // presence decides, not value - so a nullable zero *is* written, unlike a plain
                    // zero. A declared default then nests inside, rather than replacing the test.
                    Line(sb, indent, $"if (tmp{number}.HasValue)");
                    Line(sb, indent, "{");
                    Line(sb, indent + 1, $"var val{number} = tmp{number}.GetValueOrDefault();");
                    if (member.DefaultLiteral is { } nullableDefault)
                    {
                        Line(sb, indent + 1, $"if (val{number} != {nullableDefault})");
                        Line(sb, indent + 1, "{");
                        EmitScalarWrite(sb, indent + 2, member, number, $"val{number}");
                        Line(sb, indent + 1, "}");
                    }
                    else
                    {
                        EmitScalarWrite(sb, indent + 1, member, number, $"val{number}");
                    }
                    Line(sb, indent, "}");
                    goto written;
                }

                // a tuple writes every scalar unconditionally: it is rebuilt through a constructor,
                // so "absent" and "default" cannot be told apart on the way back in
                if (contract.IsTuple && member.Kind is not (ProtoMemberKind.String
                    or ProtoMemberKind.Bytes or ProtoMemberKind.Message))
                {
                    EmitScalarWrite(sb, indent, member, number, $"tmp{number}");
                    goto written;
                }

                switch (member.Kind)
                {
                    // the date/time types are written unconditionally - zero is a legitimate date,
                    // so there is no "trivial" value to skip. TimeSpan is *not* one of these: it is
                    // guarded against TimeSpan.Zero
                    case ProtoMemberKind.DateTime:
                    case ProtoMemberKind.DateOnly:
                    case ProtoMemberKind.TimeOnly:
                        EmitScalarWrite(sb, indent, member, number, $"tmp{number}");
                        break;

                    // int32 has a convenience overload that writes its own field header; everything
                    // else needs the header emitting separately, as ref-emit does
                    case ProtoMemberKind.Int32 when member.DataFormat == ProtoDataFormat.Default:
                        var int32Write = $"state.WriteInt32Varint({number}, {ScalarValue(member, $"tmp{number}")});";
                        Line(sb, indent, member.IsRequired || member.WriteCondition is not null
                            ? int32Write
                            : $"if ({ScalarGuard(member, $"tmp{number}")}) {int32Write}");
                        break;
                    case ProtoMemberKind.Int32:
                    case ProtoMemberKind.Bool:
                    case ProtoMemberKind.SByte:
                    case ProtoMemberKind.Byte:
                    case ProtoMemberKind.Int16:
                    case ProtoMemberKind.UInt16:
                    case ProtoMemberKind.UInt32:
                    case ProtoMemberKind.Int64:
                    case ProtoMemberKind.UInt64:
                    case ProtoMemberKind.Single:
                    case ProtoMemberKind.Double:
                    case ProtoMemberKind.Char:
                    case ProtoMemberKind.TimeSpan:
                    case ProtoMemberKind.Guid:
                    case ProtoMemberKind.Decimal:
                    case ProtoMemberKind.IntPtr:
                    case ProtoMemberKind.UIntPtr:
                        // IsRequired means field presence, so there is no test to emit at all
                        if (member.IsRequired || member.WriteCondition is not null)
                        {
                            EmitScalarWrite(sb, indent, member, number, $"tmp{number}");
                            break;
                        }
                        Line(sb, indent, $"if ({ScalarGuard(member, $"tmp{number}")})");
                        Line(sb, indent, "{");
                        EmitScalarWrite(sb, indent + 1, member, number, $"tmp{number}");
                        Line(sb, indent, "}");
                        break;
                    case ProtoMemberKind.String when member.DefaultLiteral is { } declared:
                        // the null test has to be explicit here: WriteString skips nulls itself, but
                        // we must not compare a null against the declared default
                        Line(sb, indent, $"if (tmp{number} != null && tmp{number} != {declared})");
                        Line(sb, indent, "{");
                        Line(sb, indent + 1, $"state.WriteString({number}, tmp{number});");
                        Line(sb, indent, "}");
                        break;
                    case ProtoMemberKind.String:
                        // no null test: WriteString(int, string) skips nulls itself
                        Line(sb, indent, $"state.WriteString({number}, tmp{number});");
                        break;
                    case ProtoMemberKind.Parseable when !member.MemberIsValueType:
                        // a reference type has to be null-tested: ToString() would throw, and the
                        // bare WriteString(string) overload does not skip nulls the way the
                        // field-number one does
                        Line(sb, indent, $"if (tmp{number} != null)");
                        Line(sb, indent, "{");
                        EmitScalarWrite(sb, indent + 1, member, number, $"tmp{number}");
                        Line(sb, indent, "}");
                        break;
                    case ProtoMemberKind.Parseable:
                        // a value type is never null, and has no trivial value to compare against
                        EmitScalarWrite(sb, indent, member, number, $"tmp{number}");
                        break;
                    case ProtoMemberKind.Uri:
                        // the null test is explicit, unlike a plain string: WriteString(int, string)
                        // would skip a null itself, but OriginalString would already have thrown
                        Line(sb, indent, $"if (tmp{number} != null)");
                        Line(sb, indent, "{");
                        Line(sb, indent + 1, $"state.WriteString({number}, tmp{number}.OriginalString);");
                        Line(sb, indent, "}");
                        break;
                    // the struct shapes - ArraySegment<byte>, Memory<byte>, ReadOnlyMemory<byte> -
                    // can never be null, so ref-emit writes them unguarded. Not merely tidier:
                    // `!= null` does not compile against Memory<byte> at all
                    case ProtoMemberKind.Bytes when member.MemberIsValueType:
                        Line(sb, indent, $"state.WriteFieldHeader({number}, global::ProtoBuf.WireType.String);");
                        Line(sb, indent, $"state.WriteBytes(tmp{number});");
                        break;
                    case ProtoMemberKind.Bytes:
                        // unlike WriteString, WriteBytes(byte[]) neither skips nulls nor writes its
                        // own field header, so both are explicit here
                        Line(sb, indent, $"if (tmp{number} != null)");
                        Line(sb, indent, "{");
                        Line(sb, indent + 1, $"state.WriteFieldHeader({number}, global::ProtoBuf.WireType.String);");
                        Line(sb, indent + 1, $"state.WriteBytes(tmp{number});");
                        Line(sb, indent, "}");
                        break;
                    // a scalar-category hand-written serializer frames the member by its own wire
                    // type, not as a sub-message. The wire type comes off the serializer's Features
                    // at runtime rather than being baked in: it is the serializer's to declare, and
                    // GetWireType() is public precisely for this
                    case ProtoMemberKind.Message when member.SubSerializerIsScalar:
                        // WriteAny(int, T, ISerializer<T>) takes the features off the serializer and
                        // frames accordingly, which is exactly what is wanted and is *public* - the
                        // GetWireType extension that would let us write the header ourselves lives on
                        // an internal class, so generated code cannot reach it
                        Line(sb, indent, $"state.WriteAny<{member.TypeName}>({number}, tmp{number}, "
                            + $"{SubSerializer(member)});");
                        break;
                    case ProtoMemberKind.Message:
                        // likewise WriteMessage/WriteGroup(int, ...) skip nulls themselves. Group
                        // affects the *write* only - its read is an ordinary ReadMessage
                        var writeMessage = member.DataFormat == ProtoDataFormat.Group ? "WriteGroup" : "WriteMessage";
                        Line(sb, indent, $"state.{writeMessage}<{member.TypeName}>({number}, {Features}.CategoryRepeated, tmp{number}, {SubSerializer(member)});");
                        break;
                }

            written:
                if (condition is not null) Line(sb, baseIndent, "}");
            }

            // the kept-but-unrecognised fields go out after every declared member
            if (contract.Extensible != ProtoExtensibleKind.None)
            {
                Line(sb, baseIndent, $"state.AppendExtensionData(value{ExtensionType(contract)});");
            }
        }

        /// <summary>
        /// A contract in a <c>[ProtoInclude]</c> hierarchy.
        /// </summary>
        /// <remarks>
        /// Both directions route through the <em>root</em>'s <c>ISubTypeSerializer</c>: that is what
        /// walks down the chain, writing each layer's own members and nesting the next layer inside a
        /// sub-type marker. So <c>ISerializer&lt;T&gt;</c> is a pair of one-line delegations for every
        /// type in the hierarchy, and the real work is in the sub-type pair, which sees only the
        /// members this layer declares.
        /// </remarks>
        private static void EmitSubTypeContract(StringBuilder sb, int indent, ProtoContractPlan contract, string root)
        {
            var self = $"{Serializers}.ISerializer<{contract.TypeName}>";
            var sub = $"{Serializers}.ISubTypeSerializer<{contract.TypeName}>";
            var rootSub = $"{Serializers}.ISubTypeSerializer<{root}>";
            // the root's ReadSubType returns the root type, so anything below it needs a cast back
            var cast = contract.TypeName == root ? "" : $"({contract.TypeName})";

            Line(sb, indent, $"{contract.TypeName} {self}.Read(ref global::ProtoBuf.ProtoReader.State state, {contract.TypeName} value)");
            Line(sb, indent + 1, $"=> {cast}(({rootSub})this).ReadSubType(ref state, "
                + $"global::ProtoBuf.Serializers.SubTypeState<{root}>.Create(state.Context, value));");
            sb.AppendLine();

            Line(sb, indent, $"void {self}.Write(ref global::ProtoBuf.ProtoWriter.State state, {contract.TypeName} value)");
            Line(sb, indent + 1, $"=> (({rootSub})this).WriteSubType(ref state, value);");
            sb.AppendLine();

            Line(sb, indent, $"void {sub}.WriteSubType(ref global::ProtoBuf.ProtoWriter.State state, {contract.TypeName} value)");
            Line(sb, indent, "{");
            if (contract.SubTypes.Count != 0)
            {
                // the runtime type decides which layer to nest; anything else is a type the model
                // was never told about
                Line(sb, indent + 1, "if (global::ProtoBuf.Meta.TypeModel.IsSubType(value))");
                Line(sb, indent + 1, "{");
                var keyword = "if";
                foreach (var subType in contract.SubTypes)
                {
                    var local = $"sub{subType.FieldNumber.ToString(CultureInfo.InvariantCulture)}";
                    Line(sb, indent + 2, $"{keyword} (value is {subType.TypeName} {local})");
                    Line(sb, indent + 2, "{");
                    var tag = subType.FieldNumber.ToString(CultureInfo.InvariantCulture);
                    if (subType.IsGroup)
                    {
                        // WriteSubType(int, ...) hard-codes WireType.String, so a grouped sub-type
                        // writes its own header and uses the overload that takes no field number
                        Line(sb, indent + 3, $"state.WriteFieldHeader({tag}, global::ProtoBuf.WireType.StartGroup);");
                        Line(sb, indent + 3, $"state.WriteSubType({local}, this);");
                    }
                    else
                    {
                        Line(sb, indent + 3, $"state.WriteSubType({tag}, {local}, this);");
                    }
                    Line(sb, indent + 2, "}");
                    keyword = "else if";
                }
                if (!contract.IgnoreUnknownSubTypes)
                {
                    Line(sb, indent + 2, "else");
                    Line(sb, indent + 2, "{");
                    Line(sb, indent + 3, "global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);");
                    Line(sb, indent + 2, "}");
                }
                Line(sb, indent + 1, "}");
            }
            else if (!contract.IsSealed && !contract.IgnoreUnknownSubTypes)
            {
                Line(sb, indent + 1, "global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);");
            }
            EmitWriteMembers(sb, indent + 1, contract);
            Line(sb, indent, "}");
            sb.AppendLine();

            Line(sb, indent, $"{contract.TypeName} {sub}.ReadSubType(ref global::ProtoBuf.ProtoReader.State state, "
                + $"global::ProtoBuf.Serializers.SubTypeState<{contract.TypeName}> value)");
            Line(sb, indent, "{");
            EmitReadLoop(sb, indent + 1, contract, "obj", contract.SubTypes, fromSubTypeState: true);
            Line(sb, indent + 1, "return value.Value;");
            Line(sb, indent, "}");
        }

        /// <summary>
        /// The enum types that need an <c>ISerializerProxy</c>, keyed by type name.
        /// </summary>
        /// <remarks>
        /// Only *repeated* enums need one. A plain enum member is written inline (cast to its
        /// underlying type), but <c>RepeatedSerializer</c> resolves an <c>ISerializer&lt;TEnum&gt;</c>
        /// from the model instead â€” so without this a repeated enum throws "no serializer for type"
        /// at runtime.
        /// </remarks>
        private static SortedDictionary<string, ProtoMemberKind> EnumProxies(ProtoModelPlan plan)
        {
            var result = new SortedDictionary<string, ProtoMemberKind>(StringComparer.Ordinal);

            // an enum seeded as a contract in its own right is served by the same proxy
            foreach (var seeded in plan.Enums)
            {
                if (seeded.TypeName is { } name) result[name] = seeded.Underlying;
            }

            foreach (var contract in plan.Contracts)
            {
                foreach (var member in contract.Members)
                {
                    // a repeated enum resolves its serializer from the model, and so does a lone
                    // [NullWrappedValue] one - ReadAny/WriteAny take an ISerializer<TEnum?>
                    if (member.Repeated.Factory is null && !member.WrappedValue) continue;
                    if (member.EnumTypeName is { } name) result[name] = member.Kind;
                }
            }
            return result;
        }

        /// <summary>
        /// Collection types the model must serve an <c>ISerializer&lt;TCollection&gt;</c> for: a map
        /// with a repeated value resolves one from the model rather than taking it inline.
        /// </summary>
        private static SortedDictionary<string, string> CollectionProxies(ProtoModelPlan plan)
        {
            var result = new SortedDictionary<string, string>(StringComparer.Ordinal);
            foreach (var contract in plan.Contracts)
            {
                foreach (var member in contract.Members)
                {
                    if (member.Map.ValueSerializerFactory is { } factory
                        && member.Map.ValueTypeName is { } name)
                    {
                        result[name] = factory;
                    }
                }
            }
            return result;
        }

        private static void EmitCollectionProxies(StringBuilder sb, int indent, ProtoModelPlan plan)
        {
            foreach (var pair in CollectionProxies(plan))
            {
                sb.AppendLine();
                Line(sb, indent, $"{Serializers}.ISerializer<{pair.Key}> {Serializers}.ISerializerProxy<{pair.Key}>.Serializer");
                Line(sb, indent + 1, $"=> {pair.Value};");
            }
        }

        private static void EmitEnumProxies(StringBuilder sb, int indent, ProtoModelPlan plan)
        {
            foreach (var pair in EnumProxies(plan))
            {
                // EnumSerializer<TEnum> implements both ISerializer<TEnum> and ISerializer<TEnum?>,
                // so the nullable proxy returns the very same instance
                var create = $"{Serializers}.EnumSerializer.Create{UnderlyingName(pair.Value)}<{pair.Key}>()";
                sb.AppendLine();
                Line(sb, indent, $"{Serializers}.ISerializer<{pair.Key}> {Serializers}.ISerializerProxy<{pair.Key}>.Serializer");
                Line(sb, indent + 1, $"=> {create};");
                sb.AppendLine();
                Line(sb, indent, $"{Serializers}.ISerializer<{pair.Key}?> {Serializers}.ISerializerProxy<{pair.Key}?>.Serializer");
                Line(sb, indent + 1, $"=> {create};");
            }
        }

        /// <summary>The <c>EnumSerializer.CreateXxx</c> suffix for an enum's underlying type.</summary>
        private static string UnderlyingName(ProtoMemberKind kind) => kind switch
        {
            ProtoMemberKind.SByte => "SByte",
            ProtoMemberKind.Byte => "Byte",
            ProtoMemberKind.Int16 => "Int16",
            ProtoMemberKind.UInt16 => "UInt16",
            ProtoMemberKind.UInt32 => "UInt32",
            ProtoMemberKind.Int64 => "Int64",
            ProtoMemberKind.UInt64 => "UInt64",
            _ => "Int32",
        };

        /// <summary>The <c>RepeatedSerializer</c> factory for a collection member.</summary>
        private static string Repeated(ProtoMemberPlan member)
        {
            var arguments = member.Repeated.TakesCollectionType
                ? $"<{member.DeclaredTypeName}, {member.ElementTypeName}>"
                : $"<{member.ElementTypeName}>";
            return $"{Serializers}.RepeatedSerializer.{member.Repeated.Factory}{arguments}()";
        }

        /// <summary>
        /// The features for a repeated member: the *element's* wire type, plus the packed opt-out.
        /// </summary>
        /// <remarks>
        /// Packing is a compile-time decision, not a runtime one: ref-emit bakes
        /// <c>OptionPackedDisabled</c> into the constant and simply omits it when
        /// <c>[ProtoMember(IsPacked = true)]</c> is set. Unpacked is the default, and that named
        /// argument is not supported yet, so this is always the disabled form.
        /// </remarks>
        private static string RepeatedFeatures(ProtoMemberPlan member)
        {
            var result = $"{Features}.{ElementWireType(member)}";
            if (!member.IsPacked) result += $" | {Features}.OptionPackedDisabled";
            if (member.WrappedValue)
            {
                // field presence in the wrapper is what separates a null element from a zero one
                result += $" | {Features}.OptionWrappedValue";
                if (member.WrappedValueGroup) result += $" | {Features}.OptionWrappedValueGroup";
                result += $" | {Features}.OptionWrappedValueFieldPresence";
            }
            if (member.WrappedCollection)
            {
                result += $" | {Features}.OptionWrappedCollection";
                if (member.WrappedCollectionGroup) result += $" | {Features}.OptionWrappedCollectionGroup";
            }
            if (member.OverwriteList) result += $" | {Features}.OptionClearCollection";
            return result;
        }

        private static string ElementWireType(ProtoMemberPlan member) => member.DataFormat switch
        {
            ProtoDataFormat.ZigZag => "WireTypeSignedVarint",
            // on a *collection* Group is not the write-only change it is on a scalar member: it goes
            // into the element features, so the element carries group markers in both directions.
            // Only a message element can be grouped - protobuf-net refuses a grouped scalar
            // collection outright, which GroupedScalarList pins
            ProtoDataFormat.Group => "WireTypeStartGroup",
            // a compatibility-level BCL element expresses its format through the *element serializer*
            // (GetInbuiltSerializer takes it), not through the wire type - a FixedSize Guid at level
            // 300 is GuidBytes, which is still length-prefixed. Applying the format here as well
            // produced a Fixed32 header over a length-prefixed body
            ProtoDataFormat.FixedSize when !IsBclKind(member.Kind)
                => Is64Bit(member.Kind) ? "WireTypeFixed64" : "WireTypeFixed32",
            _ => KindWireType(member.Kind),
        };

        /// <summary>
        /// The wire type a kind carries when no <c>DataFormat</c> is selecting one — used for
        /// collection elements and for each side of a map, where the format does not apply.
        /// </summary>
        /// <remarks>
        /// The compatibility-level BCL types are the trap here: they are length-prefixed, not
        /// varints, so a <c>List&lt;DateTime&gt;</c> whose element defaulted to <c>WireTypeVarint</c>
        /// disagreed with ref-emit on the wire. <c>DateOnly</c>/<c>TimeOnly</c> go the other way —
        /// they use <c>BclHelpers</c> but under a varint header — which is why this cannot simply
        /// ask "is it a BCL kind".
        /// </remarks>
        private static string KindWireType(ProtoMemberKind kind) => kind switch
        {
            ProtoMemberKind.Single => "WireTypeFixed32",
            ProtoMemberKind.Double => "WireTypeFixed64",
            ProtoMemberKind.String or ProtoMemberKind.Bytes or ProtoMemberKind.Message
                or ProtoMemberKind.Uri or ProtoMemberKind.Parseable
                or ProtoMemberKind.DateTime or ProtoMemberKind.TimeSpan
                or ProtoMemberKind.Guid or ProtoMemberKind.Decimal
                // a map nested as a map value is length-prefixed like any other sub-message
                or ProtoMemberKind.Map => "WireTypeString",
            _ => "WireTypeVarint",
        };

        /// <summary>
        /// The features for a lone <c>[NullWrappedValue]</c>: the value's own wire type plus the
        /// wrapping. Note there is no field-presence flag here â€” that is a collection concern, where
        /// a null and a zero would otherwise be indistinguishable.
        /// </summary>
        /// <param name="forRead">
        /// The read takes the wire type from the field header, so it passes the wrapping alone;
        /// only the write states it.
        /// </param>
        private static string WrappedFeatures(ProtoMemberPlan member, bool forRead = false)
        {
            var result = forRead
                ? $"{Features}.OptionWrappedValue"
                : $"{Features}.{ElementWireType(member)} | {Features}.OptionWrappedValue";
            if (member.WrappedValueGroup) result += $" | {Features}.OptionWrappedValueGroup";
            return result;
        }

        /// <summary>
        /// Nothing: <c>ReadAny</c>/<c>WriteAny</c> resolve the serializer themselves.
        /// </summary>
        /// <remarks>
        /// Ref-emit passes <c>this as ISerializer&lt;TEnum?&gt;</c> here, which we cannot: our
        /// services type implements <c>ISerializerProxy&lt;TEnum?&gt;</c> rather than
        /// <c>ISerializer&lt;TEnum?&gt;</c>, and C# rejects that cast on a sealed type where IL
        /// merely yields null. Both end up in the same place â€” <c>serializer ??=
        /// TypeModel.GetSerializer&lt;T&gt;(Model)</c>, which resolves the proxy through the model.
        /// </remarks>
        private static string WrappedSerializer(ProtoMemberPlan member) => "";

        /// <summary>Does the read need a null test before assigning back?</summary>
        private static bool NullableTarget(ProtoMemberPlan member)
            => member.Kind is ProtoMemberKind.String or ProtoMemberKind.Bytes;

        /// <summary>
        /// The serializer to hand a nested message: ourselves, unless the contract declares a
        /// hand-written one, in which case we never implement <c>ISerializer&lt;T&gt;</c> for it.
        /// </summary>
        /// <summary>
        /// Assert, at runtime, that each hand-written serializer's category is the one we generated
        /// for. It is the single thing about an external serializer that changes the emitted shape
        /// and that cannot be checked while generating — <c>[ProtoContract(IsScalar)]</c> may name a
        /// serializer in another assembly, whose <c>Features</c> we can only take on trust.
        /// </summary>
        /// <remarks>
        /// In the services type's constructor rather than in the proxy: members call
        /// <c>SerializerCache.Get&lt;X, T&gt;()</c> directly, so the proxy is not on the path at all
        /// and an assert there never runs — which is how the first attempt at this failed silently.
        /// The constructor runs once per model, and <c>Debug.Assert</c> is
        /// <c>[Conditional("DEBUG")]</c> resolved against the *consumer's* compilation, so a release
        /// build pays nothing but an empty constructor.
        /// </remarks>
        private static void EmitExternalCategoryAsserts(StringBuilder sb, int indent, ProtoModelPlan plan)
        {
            var external = plan.Contracts
                .Where(static x => x.ExternalSerializerTypeName is not null).ToList();
            if (external.Count == 0) return;

            Line(sb, indent, $"public {ServicesTypeName}()");
            Line(sb, indent, "{");
            foreach (var contract in external)
            {
                var expected = contract.ExternalSerializerIsScalar ? "CategoryScalar" : "CategoryMessage";
                var fix = contract.ExternalSerializerIsScalar ? "false" : "true";
                Line(sb, indent + 1, "global::System.Diagnostics.Debug.Assert(");
                Line(sb, indent + 2, $"({Serializers}.SerializerCache.Get<{contract.ExternalSerializerTypeName}, "
                    + $"{contract.TypeName}>().Features");
                Line(sb, indent + 3, $"& ({Features}.CategoryScalar | {Features}.CategoryMessage))");
                Line(sb, indent + 3, $"== {Features}.{expected},");
                Line(sb, indent + 2, $"\"{Simplify(contract.TypeName)} is generated as {expected}, but its "
                    + $"serializer disagrees; \"");
                Line(sb, indent + 3, $"+ \"set [ProtoContract(IsScalar = {fix})] on it, or correct the serializer.\");");
            }
            Line(sb, indent, "}");
            sb.AppendLine();
        }

        private static string SubSerializer(ProtoMemberPlan member) => member.SubSerializer ?? "this";

        /// <summary>A message element needs a serializer passed along; a scalar does not.</summary>
        private static string RepeatedSubSerializer(ProtoMemberPlan member)
        {
            if (member.Kind == ProtoMemberKind.Message) return $", {SubSerializer(member)}";
            // a compatibility-level BCL element does not use the inbuilt default once the level or
            // format selects another form, so ref-emit hands the collection an explicit serializer.
            // CompatibilityLevel is already the *effective* one for the element
            return InbuiltSerializer(member.Kind, member.ElementTypeName,
                member.CompatibilityLevel, member.DataFormat) is { } inbuilt ? $", {inbuilt}" : "";
        }

        /// <summary>
        /// <c>TypeModel.GetInbuiltSerializer&lt;T&gt;(level, format)</c> for an element whose
        /// compatibility level selects something other than the level-200 form, or null when the
        /// inbuilt default already serves — which is what ref-emit passes in that case.
        /// </summary>
        /// <remarks>
        /// This is <c>CompilerContext.LoadSelfAsService</c>'s rule: it emits the call whenever
        /// <c>GetInbuiltSerializer</c> would return something that is not <c>PrimaryTypeProvider</c>,
        /// and a null reference otherwise. Only the four compatibility-level types have a second
        /// form to select, so only they can produce one.
        /// </remarks>
        private static string? InbuiltSerializer(ProtoMemberKind kind, string? typeName,
            int compatibilityLevel, ProtoDataFormat format)
        {
            if (typeName is null) return null;
            if (kind is not (ProtoMemberKind.DateTime or ProtoMemberKind.TimeSpan
                or ProtoMemberKind.Guid or ProtoMemberKind.Decimal))
            {
                return null;
            }
            if (compatibilityLevel <= 200) return null;
            return $"global::ProtoBuf.Meta.TypeModel.GetInbuiltSerializer<{typeName}>("
                + $"{CompatibilityLevelLiteral(compatibilityLevel)}, {DataFormatLiteral(format)})";
        }

        /// <summary>
        /// <c>ValueMember.GetEffectiveCompatibilityLevel</c>: at or below 200, <c>WellKnown</c>
        /// promotes to 240; above that it means nothing.
        /// </summary>
        private static int EffectiveCompatibilityLevel(int level, ProtoDataFormat format)
            => level > 200 ? level : format == ProtoDataFormat.WellKnown ? 240 : 200;

        private static string CompatibilityLevelLiteral(int level)
            => $"global::ProtoBuf.CompatibilityLevel.Level{level.ToString(CultureInfo.InvariantCulture)}";

        private static string DataFormatLiteral(ProtoDataFormat format)
            => "global::ProtoBuf.DataFormat." + format switch
            {
                ProtoDataFormat.Group => "Group",
                ProtoDataFormat.FixedSize => "FixedSize",
                ProtoDataFormat.ZigZag => "ZigZag",
                // TwosComplement is deliberately absent from ProtoDataFormat: it is byte-identical
                // to Default for every type we handle, so it maps onto it
                ProtoDataFormat.WellKnown => "WellKnown",
                _ => "Default",
            };

        /// <summary>
        /// The statement that stores a value into a member.
        /// </summary>
        /// <remarks>
        /// C# forbids assigning an <c>init</c>-only property after construction; IL does not, which
        /// is why ref-emit simply calls the setter. <c>[UnsafeAccessor]</c> is the equivalent, and
        /// unlike reflection it is resolved at publish time, so it stays AOT-safe.
        /// </remarks>
        private static string Assign(ProtoContractPlan contract, ProtoMemberPlan member,
            string instance, string target, string expression)
        {
            // a getter-only member has nowhere to put the result, so the read runs for its side
            // effects alone - which is the whole mechanism for a getter-only collection
            if (member.IsReadOnly) return $"{expression};";

            if (!member.UsesAccessor || contract.IsTuple) return $"{target} = {expression};";

            // the *instance*, not the literal "value": in a sub-type read the instance is hoisted
            // into a per-case local and `value` is the SubTypeState<T> wrapper, so hard-coding it
            // passed the wrapper to the accessor and would not compile
            var self = contract.IsValueType ? $"ref {instance}" : instance;

            // a field accessor hands back a ref, so the store is an ordinary assignment
            return member.AccessorField is null
                ? $"{AccessorName(contract, member)}({self}, {expression});"
                : $"{AccessorName(contract, member)}({self}) = {expression};";
        }

        /// <summary>
        /// How the member is named in generated code - normally ${instance}.{name}, but a non-public
        /// field can only be reached through its <c>[UnsafeAccessor]</c>, which serves both directions
        /// since it hands back a <c>ref</c>.
        /// </summary>
        private static string MemberAccess(ProtoContractPlan contract, ProtoMemberPlan member, string instance)
            => member.AccessorReads
                ? $"{AccessorName(contract, member)}({(contract.IsValueType ? "ref " : "")}{instance})"
                : $"{instance}.{member.Name}";

        /// <summary>The accessor that calls a contract's non-public parameterless constructor.</summary>
        private static string ConstructorAccessorName(ProtoContractPlan contract)
            => "Create_" + Sanitise(contract.TypeName);

        /// <summary>A name unique across the whole services type, since the accessors all live on it.</summary>
        private static string AccessorName(ProtoContractPlan contract, ProtoMemberPlan member)
            // the member name needs sanitising as much as the type's: under
            // ImplicitFields.AllFields the member can *be* a backing field, whose name renders as
            // `<Ignored>k__BackingField`
            => (member.AccessorField is null ? "Set_" : "Field_")
                + Sanitise(contract.TypeName) + "_" + Sanitise(member.Name);

        /// <summary>A type's full name, reduced to something legal in an identifier.</summary>
        private static string Sanitise(string typeName)
        {
            if (typeName.StartsWith("global::", StringComparison.Ordinal)) typeName = typeName.Substring(8);

            var sb = new StringBuilder(typeName.Length);
            foreach (var c in typeName)
            {
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            }
            return sb.ToString();
        }

        /// <summary>
        /// The <c>[UnsafeAccessor]</c> declarations for everything C# will not let the generated
        /// code reach directly: init-only and non-public setters, backing fields, and non-public
        /// parameterless constructors.
        /// </summary>
        private static void EmitAccessors(StringBuilder sb, int indent, ProtoModelPlan plan)
        {
            foreach (var contract in plan.Contracts)
            {
                if (contract.UsesConstructorAccessor)
                {
                    // the surrogate is what gets constructed when there is one, and it is the
                    // surrogate the parse checked, so name it here too
                    var constructed = contract.SurrogateTypeName ?? contract.TypeName;
                    sb.AppendLine();
                    Line(sb, indent, "[global::System.Runtime.CompilerServices.UnsafeAccessor("
                        + "global::System.Runtime.CompilerServices.UnsafeAccessorKind.Constructor)]");
                    Line(sb, indent, $"private static extern {constructed} "
                        + $"{ConstructorAccessorName(contract)}();");
                }

                foreach (var member in contract.Members)
                {
                    if (!member.UsesAccessor || contract.IsTuple) continue;

                    var self = contract.IsValueType ? $"ref {contract.TypeName}" : contract.TypeName;
                    sb.AppendLine();
                    if (member.AccessorField is { } fieldName)
                    {
                        Line(sb, indent, "[global::System.Runtime.CompilerServices.UnsafeAccessor("
                            + "global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, "
                            + $"Name = \"{fieldName}\")]");
                        Line(sb, indent, $"private static extern ref {member.DeclaredTypeName} "
                            + $"{AccessorName(contract, member)}({self} target);");
                    }
                    else
                    {
                        Line(sb, indent, "[global::System.Runtime.CompilerServices.UnsafeAccessor("
                            + "global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, "
                            + $"Name = \"set_{member.Name}\")]");
                        Line(sb, indent, $"private static extern void {AccessorName(contract, member)}("
                            + $"{self} target, {member.DeclaredTypeName} value);");
                    }
                }
            }
        }

        /// <summary>The <c>MapSerializer</c> factory for a dictionary member.</summary>
        private static string Map(ProtoMemberPlan member)
        {
            var map = member.Map;
            var arguments = map.TakesCollectionType
                ? $"<{member.DeclaredTypeName}, {map.KeyTypeName}, {map.ValueTypeName}>"
                : $"<{map.KeyTypeName}, {map.ValueTypeName}>";
            return $"{Serializers}.MapSerializer.{map.Factory}{arguments}()";
        }

        /// <summary>
        /// The features for a map member: the map is always length-prefixed (or a group), and the
        /// key and value wire types are passed separately.
        /// </summary>
        /// <remarks>
        /// The member's own <c>DataFormat</c> selects the root wire type and nothing else —
        /// <c>Group</c> is the only value that changes anything, since a map is length-prefixed
        /// either way. The per-key and per-value formats come from <c>[ProtoMap]</c>.
        /// <c>OptionFailOnDuplicateKey</c> rides on whether the shape is a real protobuf <c>map</c>.
        /// </remarks>
        private static string MapFeatures(ProtoMemberPlan member)
        {
            var result = member.DataFormat == ProtoDataFormat.Group
                ? $"{Features}.WireTypeStartGroup"
                : $"{Features}.WireTypeString";
            if (!member.IsPacked) result += $" | {Features}.OptionPackedDisabled";
            // note the split: field presence rides on the *map*, the wrapping on the value
            if (member.WrappedValue) result += $" | {Features}.OptionWrappedValueFieldPresence";
            if (member.WrappedCollection)
            {
                result += $" | {Features}.OptionWrappedCollection";
                if (member.WrappedCollectionGroup) result += $" | {Features}.OptionWrappedCollectionGroup";
            }
            if (member.OverwriteList) result += $" | {Features}.OptionClearCollection";
            // DisableMap lands on the same flag an invalid map shape does: duplicates throw rather
            // than replacing, because reading switches from SetValues to AddRange
            if (!member.Map.IsValidProtobufMap || member.DisableMap)
            {
                result += $" | {Features}.OptionFailOnDuplicateKey";
            }
            return result;
        }

        private static string MapElementFeatures(ProtoMemberPlan member)
        {
            var value = $"{Features}.{MapWireType(member.Map.ValueKind, member.MapValueFormat)}";
            if (member.WrappedValue)
            {
                value += $" | {Features}.OptionWrappedValue";
                if (member.WrappedValueGroup) value += $" | {Features}.OptionWrappedValueGroup";
            }
            return $"{Features}.{MapWireType(member.Map.KeyKind, member.MapKeyFormat)}, {value}";
        }

        /// <summary>
        /// The wire type for one side of a map, which <c>[ProtoMap]</c>'s per-key and per-value
        /// <c>DataFormat</c> selects.
        /// </summary>
        /// <remarks>
        /// The format only bites where there is something to select, which was taken from ref-emit
        /// rather than assumed: a <c>string</c> key ignores <c>FixedSize</c> entirely, and the
        /// <c>FixedSize</c> width comes from the <em>element</em> type just as it does for a scalar
        /// member — <c>int</c> gives <c>Fixed32</c>, <c>long</c> gives <c>Fixed64</c>.
        /// </remarks>
        private static string MapWireType(ProtoMemberKind kind, ProtoDataFormat format) => kind switch
        {
            ProtoMemberKind.Message => format == ProtoDataFormat.Group ? "WireTypeStartGroup" : "WireTypeString",
            _ => KindWireType(kind) switch
            {
                // the format only bites where the default is a varint - which is why a string key
                // ignores FixedSize, and why Single/Double keep their own fixed widths
                "WireTypeVarint" => format switch
                {
                    ProtoDataFormat.ZigZag => "WireTypeSignedVarint",
                    ProtoDataFormat.FixedSize => Is64Bit(kind) ? "WireTypeFixed64" : "WireTypeFixed32",
                    _ => "WireTypeVarint",
                },
                var fixedByKind => fixedByKind,
            },
        };

        /// <summary>
        /// A message key or value needs us passed along as its serializer. The two are positional, so
        /// a message value alone still has to pass a null for the key.
        /// </summary>
        private static string MapSubSerializers(ProtoMemberPlan member)
        {
            // the two sides are positional, so a value serializer needs the key slot filled with
            // null. Either side may want `this` (a message) or an inbuilt (a levelled BCL type);
            // note the *declared* level is combined with that side's own [ProtoMap] format, since
            // the member's own DataFormat selects the map's root wire type and nothing else
            var key = member.Map.KeyKind == ProtoMemberKind.Message ? "this"
                : InbuiltSerializer(member.Map.KeyKind, member.Map.KeyTypeName,
                    EffectiveCompatibilityLevel(member.DeclaredCompatibilityLevel, member.MapKeyFormat),
                    member.MapKeyFormat);
            var value = member.Map.ValueKind == ProtoMemberKind.Message ? "this"
                : InbuiltSerializer(member.Map.ValueKind, member.Map.ValueTypeName,
                    EffectiveCompatibilityLevel(member.DeclaredCompatibilityLevel, member.MapValueFormat),
                    member.MapValueFormat);

            if (value is not null) return $", {key ?? "null"}, {value}";
            return key is null ? "" : $", {key}";
        }

        /// <summary>
        /// How a fresh instance is made: normally <c>new</c>, but SkipConstructor bypasses every
        /// constructor, exactly as ref-emit does.
        /// </summary>
        /// <param name="typeName">
        /// What to construct â€” the contract itself, or its surrogate when it has one.
        /// </param>
        /// <summary>
        /// Convert an instance to its surrogate. A cast covers an <c>explicit</c> operator as well as
        /// an <c>implicit</c> one - ref-emit relies on the implicit form, but only the cast compiles
        /// for both - unless the model named conversion methods instead, which is how a type with no
        /// usable operators is hooked up.
        /// </summary>
        private static string ToSurrogate(ProtoContractPlan contract, string value)
            => contract.ToSurrogate is { } method
                ? $"{method}({value})"
                : $"({contract.SurrogateTypeName}){value}";

        /// <summary>The converse; see <see cref="ToSurrogate"/>.</summary>
        private static string ToUnderlying(ProtoContractPlan contract, string surrogate)
            => contract.ToUnderlying is { } method
                ? $"{method}({surrogate})"
                : $"({contract.TypeName}){surrogate}";

        private static string Construct(ProtoContractPlan contract, string? typeName = null)
        {
            typeName ??= contract.TypeName;
            if (contract.SkipConstructor)
            {
                return $"({typeName})global::ProtoBuf.BclHelpers.GetUninitializedObject(typeof({typeName}))";
            }
            // C# will not let us call a non-public constructor; IL has no such restriction, which is
            // why the runtime model reaches it by reflection and we reach it by [UnsafeAccessor]
            return contract.UsesConstructorAccessor
                ? $"{ConstructorAccessorName(contract)}()"
                : $"new {typeName}()";
        }

        /// <summary>
        /// The unguarded write for a scalar: the caller owns whatever test precedes it.
        /// </summary>
        private static void EmitScalarWrite(StringBuilder sb, int indent, ProtoMemberPlan member, string number, string local)
        {
            var expression = ScalarValue(member, local);
            if (member.Kind == ProtoMemberKind.Parseable)
            {
                Line(sb, indent, $"state.WriteFieldHeader({number}, global::ProtoBuf.WireType.String);");
                Line(sb, indent, $"state.WriteString({expression}.ToString());");
            }
            else if (BclSuffix(member) is { } bcl)
            {
                Line(sb, indent, $"state.WriteFieldHeader({number}, global::ProtoBuf.WireType.{BclWireType(member)});");
                Line(sb, indent, $"global::ProtoBuf.BclHelpers.Write{bcl}(ref state, {expression});");
            }
            // the Int32 shortcut writes its own varint header, so it only applies at the default format
            else if (member.Kind == ProtoMemberKind.Int32 && member.DataFormat == ProtoDataFormat.Default)
            {
                Line(sb, indent, $"state.WriteInt32Varint({number}, {expression});");
            }
            else
            {
                Line(sb, indent, $"state.WriteFieldHeader({number}, global::ProtoBuf.WireType.{ScalarWireType(member)});");
                Line(sb, indent, $"state.{ScalarSuffix(member.Kind, "Write")}({expression});");
            }
        }

        /// <summary>
        /// The value handed to the write method: an enum needs casting down to its underlying type,
        /// while a char converts to ushort implicitly.
        /// </summary>
        private static string ScalarValue(ProtoMemberPlan member, string local)
            => member.EnumTypeName is null ? local : $"({UnderlyingKeyword(member.Kind)}){local}";

        /// <summary>
        /// The value read back: cast up to the enum type, or to char, since the read methods deal in
        /// the underlying scalar.
        /// </summary>
        /// <summary>ZigZag reads need a wire-type hint first; no other format does.</summary>
        private static string? ScalarReadHint(ProtoMemberPlan member)
            => member.DataFormat == ProtoDataFormat.ZigZag
                ? "state.Hint(global::ProtoBuf.WireType.SignedVarint);" : null;

        /// <summary>
        /// The <c>BclHelpers</c> method suffix for a compatibility-level BCL type, or null if this
        /// member is not one.
        /// </summary>
        /// <remarks>
        /// Taken from ref-emit at each level. Note the level has already absorbed
        /// <c>DataFormat.WellKnown</c>, and that <c>FixedSize</c> selects the 16-byte Guid only at
        /// level 300 â€” below that it is simply ignored.
        /// </remarks>
        private static string? BclSuffix(ProtoMemberPlan member) => member.Kind switch
        {
            ProtoMemberKind.DateTime => member.CompatibilityLevel >= 240 ? "Timestamp" : "DateTime",
            ProtoMemberKind.TimeSpan => member.CompatibilityLevel >= 240 ? "Duration" : "TimeSpan",
            ProtoMemberKind.Guid => member.CompatibilityLevel >= 300
                ? (member.DataFormat == ProtoDataFormat.FixedSize ? "GuidBytes" : "GuidString")
                : "Guid",
            ProtoMemberKind.Decimal => member.CompatibilityLevel >= 300 ? "DecimalString" : "Decimal",

            // these two also live on BclHelpers, but are *not* compatibility-level types: the level
            // does not reach them, and the header is a varint rather than a length prefix
            ProtoMemberKind.DateOnly => "DateOnly",
            ProtoMemberKind.TimeOnly => "TimeOnly",
            _ => null,
        };

        /// <param name="discard">
        /// The result is going nowhere, so it is emitted as a bare statement â€” which means the casts
        /// have to go, since a cast expression is not a valid C# statement.
        /// </param>
        /// <summary>
        /// The field-header wire type for a BCL member. Length-prefixed by default, but
        /// <c>DataFormat</c> shifts some combinations â€” and not uniformly.
        /// </summary>
        /// <remarks>
        /// This is a probed table, not a rule: ref-emit takes the wire type from whichever serializer
        /// (type, level, format) resolves to, and the result has real quirks. <c>decimal</c> ignores
        /// the format entirely; <c>Guid</c> honours <c>Group</c> but ignores <c>FixedSize</c> below
        /// level 300 (where it instead selects the 16-byte form); <c>DateTime</c> and
        /// <c>TimeSpan</c> honour both. <c>ZigZag</c> is refused â€” it throws while building the model.
        /// </remarks>
        private static string BclWireType(ProtoMemberPlan member) => member.Kind switch
        {
            // DateOnly/TimeOnly are BclHelpers calls but not compatibility-level types; ref-emit
            // gives them a plain varint header, and DataFormat does not shift it
            ProtoMemberKind.DateOnly or ProtoMemberKind.TimeOnly => "Varint",
            _ => BclWireTypeByFormat(member),
        };

        private static string BclWireTypeByFormat(ProtoMemberPlan member) => member.DataFormat switch
        {
            ProtoDataFormat.Group when member.Kind != ProtoMemberKind.Decimal => "StartGroup",
            ProtoDataFormat.FixedSize when member.Kind
                is ProtoMemberKind.DateTime or ProtoMemberKind.TimeSpan => "Fixed64",
            _ => "String",
        };

        /// <summary>
        /// <c>UriDecorator</c>'s read: relative and absolute both round-trip, hence the kind.
        /// </summary>
        private static string NewUri(string text)
            => $"new global::System.Uri({text}, global::System.UriKind.RelativeOrAbsolute)";

        private static string ScalarRead(ProtoMemberPlan member, bool discard = false)
        {
            if (member.Kind == ProtoMemberKind.Parseable)
            {
                return $"{member.DeclaredTypeName}.Parse(state.ReadString())";
            }
            if (BclSuffix(member) is { } bcl) return $"global::ProtoBuf.BclHelpers.Read{bcl}(ref state)";

            var call = $"state.{ScalarSuffix(member.Kind, "Read")}()";
            if (discard) return call;
            if (member.EnumTypeName is { } enumType) return $"({enumType}){call}";
            return member.Kind == ProtoMemberKind.Char ? $"(char){call}" : call;
        }

        private static string UnderlyingKeyword(ProtoMemberKind kind) => kind switch
        {
            ProtoMemberKind.SByte => "sbyte",
            ProtoMemberKind.Byte => "byte",
            ProtoMemberKind.Int16 => "short",
            ProtoMemberKind.UInt16 => "ushort",
            ProtoMemberKind.Int32 => "int",
            ProtoMemberKind.UInt32 => "uint",
            ProtoMemberKind.Int64 => "long",
            ProtoMemberKind.UInt64 => "ulong",
            _ => kind.ToString(),
        };

        /// <summary>The <c>ReadXxx</c>/<c>WriteXxx</c> name for a scalar kind.</summary>
        private static string ScalarSuffix(ProtoMemberKind kind, string prefix) => prefix + (kind switch
        {
            ProtoMemberKind.Bool => "Boolean",
            ProtoMemberKind.Single => "Single",
            ProtoMemberKind.Double => "Double",
            ProtoMemberKind.Char => "UInt16", // a char goes on the wire as a ushort
            _ => kind.ToString(), // SByte, Byte, Int16, UInt16, Int32, UInt32, Int64, UInt64
        });

        private static string ScalarWireType(ProtoMemberPlan member) => member.DataFormat switch
        {
            // ZigZag is always the signed varint; FixedSize picks its width from the member
            ProtoDataFormat.ZigZag => "SignedVarint",
            ProtoDataFormat.FixedSize => Is64Bit(member.Kind) ? "Fixed64" : "Fixed32",
            _ => member.Kind switch
            {
                ProtoMemberKind.Single => "Fixed32",
                ProtoMemberKind.Double => "Fixed64",
                _ => "Varint",
            },
        };

        private static bool Is64Bit(ProtoMemberKind kind)
            => kind is ProtoMemberKind.Int64 or ProtoMemberKind.UInt64 or ProtoMemberKind.Double
                // ref-emit asks GetIntWireType for width 64 regardless of the platform
                or ProtoMemberKind.IntPtr or ProtoMemberKind.UIntPtr;

        /// <summary>
        /// The "is this worth writing" test: a member equal to its default is omitted, where the
        /// default is <c>[DefaultValue]</c> if declared and the type's own default otherwise.
        /// </summary>
        private static string ScalarGuard(ProtoMemberPlan member, string local)
        {
            // note: IsRequired is handled by the callers omitting the test entirely, rather than
            // by returning "true" here - generated code is read by people
            if (member.DefaultLiteral is { } declared) return $"{local} != {declared}";

            // an enum compares against its own zero, which need not have a declared name
            if (member.EnumTypeName is { } enumType) return $"{local} != default({enumType})";

            return member.Kind switch
            {
                ProtoMemberKind.Bool => local,
                ProtoMemberKind.Single => $"{local} != 0f",
                ProtoMemberKind.Double => $"{local} != 0d",
                // DateTime is the odd one out: ref-emit writes it unconditionally, so it never
                // reaches here (see the write, which skips the test for it entirely)
                ProtoMemberKind.TimeSpan => $"{local} != global::System.TimeSpan.Zero",
                ProtoMemberKind.Guid => $"{local} != global::System.Guid.Empty",
                ProtoMemberKind.Decimal => $"{local} != 0m",
                _ => $"{local} != 0",
            };
        }

        private static void Line(StringBuilder sb, int indent, string text)
            => sb.Append(' ', indent * 4).AppendLine(text);
    }
}
