<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>protobuf-net.ServiceModel</AssemblyName>
    <RootNamespace>ProtoBuf</RootNamespace>
    <Title>protobuf-net</Title>
    <Description>ServiceModel (WCF) extensions for protobuf-net</Description>
    <TargetFrameworks>net462;net8.0</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <FeatureServiceModelConfiguration>false</FeatureServiceModelConfiguration>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(TargetFramework)' == 'net462'">
    <DefineConstants>$(DefineConstants);FEAT_SERVICECONFIGMODEL</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <Reference Include="System.Configuration" />
    <Reference Include="System.ServiceModel" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net462'">
    <PackageReference Include="System.ServiceModel.Primitives" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\protobuf-net\protobuf-net.csproj" />
  </ItemGroup>
  <ItemGroup Label="public API tracking">
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="all" />
    <!-- APIs for all target frameworks -->
    <AdditionalFiles Include="PublicAPI/PublicAPI.*.txt" />
    <!-- progressively additive APIs in later frameworks; each folder is effectively NET_X_Y_OR_GREATER -->
    <AdditionalFiles Include="PublicAPI/netstandard2.1/PublicAPI.*.txt" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.1'))" />
    <AdditionalFiles Include="PublicAPI/net8.0/PublicAPI.*.txt" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))" />
    <!-- net4x-only surface (e.g. persist-to-dll) -->
    <AdditionalFiles Include="PublicAPI/net462/PublicAPI.*.txt" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net462'))" />
  </ItemGroup>
</Project>
