using ProtoBuf.Test.Nullables.Abstractions;
using Xunit;
using Xunit.Abstractions;

namespace ProtoBuf.Test.Nullables.WrappersProto
{
    public class WrappersProtoToCode : NullablesTestsBase
    {
        public WrappersProtoToCode(ITestOutputHelper log) : base(log)
        {
        }

        [Theory]
        [InlineData(".google.protobuf.DoubleValue", "global::double?")]
        [InlineData(".google.protobuf.FloatValue", "global::float?")]
        [InlineData(".google.protobuf.Int64Value", "global::long?")]
        [InlineData(".google.protobuf.UInt64Value", "global::ulong?")]
        [InlineData(".google.protobuf.Int32Value", "global::int?")]
        [InlineData(".google.protobuf.UInt32Value", "global::uint?")]
        [InlineData(".google.protobuf.BoolValue", "global::bool?")]
        [InlineData(".google.protobuf.StringValue", "global::string")]
        [InlineData(".google.protobuf.BytesValue", "global::byte[]")]
        [InlineData(".google.protobuf.Timestamp", "global::System.DateTime?")]
        [InlineData(".google.protobuf.Duration", "global::System.TimeSpan?")]
        public void GoogleProtobufWellKnownType_ConvertsToCSharpNullable(string protoFieldType, string csharpGeneratedType) 
            => AssertCSharpCodeGenerator(
                protobufSchemaContent: GetSimpleProtobufSchemaContent(protoFieldType),
                generatedCode: GetSimpleCSharpGeneratedCodeContent(csharpGeneratedType));

        string GetSimpleProtobufSchemaContent(string fieldType) => @$"
            import ""google/protobuf/wrappers.proto"";
            syntax = ""proto3"";

            message WrappedTest {{
                {fieldType} optionalValue = 42;
            }}
        ";

        string GetSimpleCSharpGeneratedCodeContent(string csharpGenerateFieldType) => @$"
            // <auto-generated>
            //   This file was generated by a tool; you should avoid making direct changes.
            //   Consider using 'partial classes' to extend these types
            //   Input: default.proto
            // </auto-generated>

            #region Designer generated code
            #pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
            [global::ProtoBuf.ProtoContract()]
            public partial class WrappedTest : global::ProtoBuf.IExtensible
            {{
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(42, DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
                public {csharpGenerateFieldType} optionalValue {{ get; set; }}

            }}

            #pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
            #endregion
        ";
    }
}
