// ClassicEmit twins — gap B18.
//
// `[ProtoModel(ClassicEmit = true)]` is the escape hatch we point consumers at when the raw writer
// cannot serve them; it is named in ProtoWriter.State.Raw.cs's own error text for the
// non-seekable-stream case. Until this file existed, NOT ONE test set it: the classic emit path
// was generated by nobody and compared against nothing, so the least-tested path here was the
// fallback.
//
// These are declared in the TEST project rather than beside the fixtures deliberately. The fixture
// files are shared with the golden tests and with AotRefGen, and a second model in them would
// change both for a reason that belongs only to the differential.
//
// DifferentialTests.DiscoverModels() finds every [ProtoModel] in the assembly, so each twin is
// compared against RuntimeTypeModel over the same samples automatically - GetSamples strips the
// "Classic" marker so `<Stem>ClassicModel` resolves to `<Stem>Samples`. That is what makes this
// cheap: no new harness, just the declarations.
//
// The set is chosen for where the two emit paths could plausibly diverge, not for breadth:
// groups (which take the raw path and skip the measure), callbacks (which disqualify a contract
// from measure-first entirely), repeated members (the packed work of B1 lands here), nesting
// (length prefixes and the length cache), and plain scalars as the control.

using ProtoBuf;
using ProtoBuf.Meta;

namespace AotFixtures.GroupedElements
{
    /// <summary>Groups, maps and collections, emitted the classic way.</summary>
    [ProtoModel(ClassicEmit = true)]
    [ProtoSerializable(typeof(Grouped))]
    [ProtoSerializable(typeof(GroupedMaps))]
    [ProtoSerializable(typeof(GroupedOnly))]
    [ProtoSerializable(typeof(Node))]
    public partial class GroupedElementsClassicModel : TypeModel { }
}

namespace AotFixtures.Callbacks
{
    /// <summary>
    /// The sharpest of the twins. A before-serialize callback used to disqualify a contract from
    /// measure-first outright; since gap B42 it does not - both passes fire the callback - so this
    /// pair now compares a classic write against a measure-first one that runs consumer code in
    /// each pass, which is a stronger test than it was.
    /// </summary>
    [ProtoModel(ClassicEmit = true)]
    [ProtoSerializable(typeof(Hooked))]
    [ProtoSerializable(typeof(Standard))]
    [ProtoSerializable(typeof(AfterOnly))]
    [ProtoSerializable(typeof(Holder))]
    [ProtoSerializable(typeof(Watched))]
    [ProtoSerializable(typeof(WatchedHolder))]
    public partial class CallbacksClassicModel : TypeModel { }
}

namespace AotFixtures.Lists
{
    /// <summary>Repeated members — where the packed work of B1 will land.</summary>
    [ProtoModel(ClassicEmit = true)]
    [ProtoSerializable(typeof(Repeated))]
    public partial class ListsClassicModel : TypeModel { }
}

namespace AotFixtures.Nested
{
    /// <summary>Nesting, i.e. length prefixes and the length cache.</summary>
    [ProtoModel(ClassicEmit = true)]
    [ProtoSerializable(typeof(Invoice))]
    [ProtoSerializable(typeof(Customer))]
    public partial class NestedClassicModel : TypeModel { }
}

namespace AotFixtures.Scalars
{
    /// <summary>The control: if this one diverges, something very basic is wrong.</summary>
    [ProtoModel(ClassicEmit = true)]
    [ProtoSerializable(typeof(Primitives))]
    public partial class ScalarsClassicModel : TypeModel { }
}
