
using ProtoBuf;
using ProtoBuf.Internal;
using ProtoBuf.Meta;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("protobuf-net.Test" + StrongNameIdentity.Suffix)]

[assembly: TypeForwardedTo(typeof(TypeModel))]
[assembly: TypeForwardedTo(typeof(ProtoReader))]
[assembly: TypeForwardedTo(typeof(ProtoWriter))]
[assembly: TypeForwardedTo(typeof(SerializationContext))]
[assembly: TypeForwardedTo(typeof(SubItemToken))]
[assembly: TypeForwardedTo(typeof(WireType))]
[assembly: TypeForwardedTo(typeof(PrefixStyle))]
[assembly: TypeForwardedTo(typeof(IExtensible))]
[assembly: TypeForwardedTo(typeof(IExtension))]
[assembly: TypeForwardedTo(typeof(IExtensionResettable))]
[assembly: TypeForwardedTo(typeof(TypeFormatEventArgs))]
[assembly: TypeForwardedTo(typeof(TypeFormatEventHandler))]
[assembly: TypeForwardedTo(typeof(ProtoTypeCode))]
[assembly: TypeForwardedTo(typeof(DataFormat))]
[assembly: TypeForwardedTo(typeof(ProtoException))]
[assembly: TypeForwardedTo(typeof(DiscriminatedUnion128))]
[assembly: TypeForwardedTo(typeof(DiscriminatedUnion128Object))]
[assembly: TypeForwardedTo(typeof(DiscriminatedUnion32))]
[assembly: TypeForwardedTo(typeof(DiscriminatedUnion32Object))]
[assembly: TypeForwardedTo(typeof(DiscriminatedUnion64))]
[assembly: TypeForwardedTo(typeof(DiscriminatedUnion64Object))]
[assembly: TypeForwardedTo(typeof(DiscriminatedUnionObject))]
[assembly: TypeForwardedTo(typeof(BclHelpers))]
[assembly: TypeForwardedTo(typeof(TimeSpanScale))]
[assembly: TypeForwardedTo(typeof(BufferExtension))]
[assembly: TypeForwardedTo(typeof(Extensible))]

[assembly: TypeForwardedTo(typeof(ProtoBeforeDeserializationAttribute))]
[assembly: TypeForwardedTo(typeof(ProtoBeforeSerializationAttribute))]
[assembly: TypeForwardedTo(typeof(ProtoAfterDeserializationAttribute))]
[assembly: TypeForwardedTo(typeof(ProtoAfterSerializationAttribute))]
[assembly: TypeForwardedTo(typeof(ProtoContractAttribute))]
[assembly: TypeForwardedTo(typeof(ProtoEnumAttribute))]
[assembly: TypeForwardedTo(typeof(ProtoConverterAttribute))]
[assembly: TypeForwardedTo(typeof(ProtoIncludeAttribute))]
[assembly: TypeForwardedTo(typeof(ProtoIgnoreAttribute))]
[assembly: TypeForwardedTo(typeof(ProtoMapAttribute))]
[assembly: TypeForwardedTo(typeof(ProtoMemberAttribute))]
[assembly: TypeForwardedTo(typeof(MemberSerializationOptions))]
[assembly: TypeForwardedTo(typeof(ProtoPartialMemberAttribute))]
[assembly: TypeForwardedTo(typeof(ProtoPartialIgnoreAttribute))]
[assembly: TypeForwardedTo(typeof(ImplicitFields))]
[assembly: TypeForwardedTo(typeof(IProtoInput<>))]
[assembly: TypeForwardedTo(typeof(IProtoOutput<>))]
[assembly: TypeForwardedTo(typeof(IMeasuredProtoOutput<>))]
[assembly: TypeForwardedTo(typeof(MeasureState<>))]