// ---- AotFixtures.AbstractLeaf.AbstractLeafModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable PBN9002

namespace AotFixtures.AbstractLeaf;

partial class AbstractLeafModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected AbstractLeafModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static AbstractLeafModel Instance { get; } = new AbstractLeafModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.AbstractLeaf.Holder>
        , global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.AbstractLeaf.Shape>
    {
        private static readonly ProtoBufGeneratedServices s_default = new ProtoBufGeneratedServices();

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.AbstractLeaf.Holder>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.AbstractLeaf.Holder global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.AbstractLeaf.Holder>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.AbstractLeaf.Holder value)
            => RawRead_AotFixtures_AbstractLeaf_Holder(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.AbstractLeaf.Holder>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.AbstractLeaf.Holder value)
            => RawWrite_AotFixtures_AbstractLeaf_Holder(ref state, value);

        public static void RawWrite_AotFixtures_AbstractLeaf_Holder(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.AbstractLeaf.Holder value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Value;
            if (tmp1 != null)
            {
                state.WriteRawTag((1 << 3) | 2);  // Value
                var lengths1 = state.RawLengths;
                if (!lengths1.TryGetValue(tmp1, out var len1))
                {
                    len1 = Measure_AotFixtures_AbstractLeaf_Shape(tmp1, state.RawDepthBudget, lengths1);
                    lengths1[tmp1] = len1;
                }
                state.WriteRawVarint64((ulong)len1);
                RawWrite_AotFixtures_AbstractLeaf_Shape(ref state, tmp1);
            }
            var tmp2 = value.Name;
            if (tmp2 != null)
            {
                state.WriteRawTag((2 << 3) | 2);  // Name
                state.WriteRawString(tmp2);
            }
        }

        private static long Measure_AotFixtures_AbstractLeaf_Holder(global::AotFixtures.AbstractLeaf.Holder value, int depth, global::System.Collections.Generic.Dictionary<object, long> lengths)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.Value;
            if (tmp1 != null)
            {
                if (!lengths.TryGetValue(tmp1, out var len1))
                {
                    len1 = Measure_AotFixtures_AbstractLeaf_Shape(tmp1, depth, lengths);
                    lengths[tmp1] = len1;
                }
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64((ulong)len1) + len1;  // Value
            }
            var tmp2 = value.Name;
            if (tmp2 != null)
            {
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawString(tmp2);  // Name
            }
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.AbstractLeaf.Holder>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.AbstractLeaf.Holder value)
            => global::ProtoBuf.ProtoWriter.State.TryMeasureRaw(context, out var depth, out var lengths)
                && Measure_AotFixtures_AbstractLeaf_Holder(value, depth, lengths) is var len && len <= int.MaxValue
                ? (int)len : -1;

        private static global::AotFixtures.AbstractLeaf.Holder RawRead_AotFixtures_AbstractLeaf_Holder(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.AbstractLeaf.Holder value)
        {
            value ??= new global::AotFixtures.AbstractLeaf.Holder();
            uint tag = state.ReadRawTagOrPending();
            while (tag != 0)
            {
                switch (tag)
                {
                    // raw read pass: legacy-mode - member Value: target type not raw-eligible
                    case (1 << 3) | 0:
                    case (1 << 3) | 1:
                    case (1 << 3) | 2:  // Value, field 1
                    case (1 << 3) | 3:
                    case (1 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp1 = value.Value;
                        tmp1 = state.ReadMessage<global::AotFixtures.AbstractLeaf.Shape>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp1, s_default);
                        if (tmp1 != null) value.Value = tmp1;
                        break;
                    }
                    case (2 << 3) | 2:  // Name, field 2, length-prefixed
                    {
                        var tmp2 = state.ReadRawString();
                        if (tmp2 != null) value.Name = tmp2;
                        break;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTagOrPending();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.AbstractLeaf.Shape>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.AbstractLeaf.Shape global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.AbstractLeaf.Shape>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.AbstractLeaf.Shape value)
        {
            if (value is null) global::ProtoBuf.Meta.TypeModel.ThrowCannotCreateInstance(typeof(global::AotFixtures.AbstractLeaf.Shape));
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        value.Sides = state.ReadInt32();
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.AbstractLeaf.Shape>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.AbstractLeaf.Shape value)
            => RawWrite_AotFixtures_AbstractLeaf_Shape(ref state, value);

        public static void RawWrite_AotFixtures_AbstractLeaf_Shape(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.AbstractLeaf.Shape value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Sides;
            if (tmp1 != 0)
            {
                state.WriteRawTag((1 << 3) | 0);  // Sides
                state.WriteRawVarint64(unchecked((ulong)(long)tmp1));
            }
        }

        private static long Measure_AotFixtures_AbstractLeaf_Shape(global::AotFixtures.AbstractLeaf.Shape value, int depth, global::System.Collections.Generic.Dictionary<object, long> lengths)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.Sides;
            if (tmp1 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp1));  // Sides
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.AbstractLeaf.Shape>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.AbstractLeaf.Shape value)
            => global::ProtoBuf.ProtoWriter.State.TryMeasureRaw(context, out var depth, out var lengths)
                && Measure_AotFixtures_AbstractLeaf_Shape(value, depth, lengths) is var len && len <= int.MaxValue
                ? (int)len : -1;

        // raw read pass: skipped - contract shape (value type, tuple, surrogate or external serializer)
    }
}
