// ---- AotFixtures.Bytes.BytesModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable PBN9002

namespace AotFixtures.Bytes;

partial class BytesModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected BytesModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static BytesModel Instance { get; } = new BytesModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.Bytes.Blob value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Bytes.Blob>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.Bytes.Blob value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Bytes.Blob>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Bytes.Blob>
    {
        private static readonly ProtoBufGeneratedServices Self = new();

        private static readonly ProtoBufGeneratedServices s_default = new ProtoBufGeneratedServices();

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Bytes.Blob>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Bytes.Blob global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Bytes.Blob>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Bytes.Blob value)
            => RawRead_AotFixtures_Bytes_Blob(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Bytes.Blob>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Bytes.Blob value)
            => RawWrite_AotFixtures_Bytes_Blob(ref state, value, state.RawDepthBudget);

        public static void RawWrite_AotFixtures_Bytes_Blob(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Bytes.Blob value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Payload;
            if (tmp1 != null)
            {
                state.WriteRawTag((1 << 3) | 2);  // Payload
                state.WriteRawBytes(tmp1);
            }
            var tmp2 = value.Other;
            if (tmp2 != null)
            {
                state.WriteRawTag((2 << 3) | 2);  // Other
                state.WriteRawBytes(tmp2);
            }
            var tmp3 = value.Single;
            if (tmp3 != 0)
            {
                state.WriteRawTag((3 << 3) | 0);  // Single
                state.WriteRawVarint32(tmp3);
            }
            var tmp4 = value.Segment;
            state.WriteFieldHeader(4, global::ProtoBuf.WireType.String);
            state.WriteBytes(tmp4);
            var tmp5 = value.Memory;
            state.WriteFieldHeader(5, global::ProtoBuf.WireType.String);
            state.WriteBytes(tmp5);
            var tmp6 = value.ReadOnly;
            state.WriteFieldHeader(6, global::ProtoBuf.WireType.String);
            state.WriteBytes(tmp6);
        }

        private static long Measure_AotFixtures_Bytes_Blob(global::AotFixtures.Bytes.Blob value, int depth, global::ProtoBuf.RawLengthBuffer slots, global::ProtoBuf.ISerializationContext context)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.Payload;
            if (tmp1 != null)
            {
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint32((uint)tmp1.Length) + tmp1.Length;  // Payload
            }
            var tmp2 = value.Other;
            if (tmp2 != null)
            {
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint32((uint)tmp2.Length) + tmp2.Length;  // Other
            }
            var tmp3 = value.Single;
            if (tmp3 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint32(tmp3);  // Single
            var tmp4 = value.Segment;
            var bytes4 = ((global::System.ReadOnlyMemory<byte>)tmp4).Length;
            len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint32((uint)bytes4) + bytes4;  // Segment
            var tmp5 = value.Memory;
            var bytes5 = ((global::System.ReadOnlyMemory<byte>)tmp5).Length;
            len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint32((uint)bytes5) + bytes5;  // Memory
            var tmp6 = value.ReadOnly;
            var bytes6 = ((global::System.ReadOnlyMemory<byte>)tmp6).Length;
            len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint32((uint)bytes6) + bytes6;  // ReadOnly
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Bytes.Blob>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Bytes.Blob value)
        {
            if (!global::ProtoBuf.ProtoWriter.State.TryMeasureRawSlots(context, out var depth, out var slots)) return -1;
            var entry = slots.Mark();
            var len = Measure_AotFixtures_Bytes_Blob(value, depth, slots, context);
            slots.Enter(value, entry);
            return len <= int.MaxValue ? (int)len : -1;
        }

        private static global::AotFixtures.Bytes.Blob RawRead_AotFixtures_Bytes_Blob(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Bytes.Blob value)
        {
            value ??= new global::AotFixtures.Bytes.Blob();
            uint tag = state.ReadRawTagOrPending();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 2:  // Payload, field 1, length-prefixed
                        value.Payload = state.AppendRawBytes(value.Payload);
                        break;
                    case (2 << 3) | 2:  // Other, field 2, length-prefixed
                        value.Other = state.AppendRawBytes(value.Other);
                        break;
                    // raw read pass: legacy-mode - member Single: kind Byte
                    case (3 << 3) | 0:
                    case (3 << 3) | 1:
                    case (3 << 3) | 2:  // Single, field 3
                    case (3 << 3) | 3:
                    case (3 << 3) | 5:
                    {
                        state.StashTag(tag);
                        value.Single = state.ReadByte();
                        break;
                    }
                    case (4 << 3) | 2:  // Segment, field 4, length-prefixed
                        value.Segment = state.AppendRawBytes(value.Segment);
                        break;
                    case (5 << 3) | 2:  // Memory, field 5, length-prefixed
                        value.Memory = state.AppendRawBytes(value.Memory);
                        break;
                    case (6 << 3) | 2:  // ReadOnly, field 6, length-prefixed
                        value.ReadOnly = state.AppendRawBytes(value.ReadOnly);
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTagOrPending();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2 or 3 or 4 or 5 or 6;
        }
    }
}
