// ---- AotFixtures.Bytes.BytesModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591

namespace AotFixtures.Bytes;

partial class BytesModel
{
    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Bytes.Blob>
    {
        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Bytes.Blob>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Bytes.Blob global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Bytes.Blob>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Bytes.Blob value)
        {
            value ??= new global::AotFixtures.Bytes.Blob();
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        var tmp1 = value.Payload;
                        tmp1 = state.AppendBytes(tmp1);
                        if (tmp1 != null) value.Payload = tmp1;
                        break;
                    }
                    case 2:
                    {
                        var tmp2 = value.Other;
                        tmp2 = state.AppendBytes(tmp2);
                        if (tmp2 != null) value.Other = tmp2;
                        break;
                    }
                    case 3:
                    {
                        value.Single = state.ReadByte();
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Bytes.Blob>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Bytes.Blob value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Payload;
            if (tmp1 != null)
            {
                state.WriteFieldHeader(1, global::ProtoBuf.WireType.String);
                state.WriteBytes(tmp1);
            }
            var tmp2 = value.Other;
            if (tmp2 != null)
            {
                state.WriteFieldHeader(2, global::ProtoBuf.WireType.String);
                state.WriteBytes(tmp2);
            }
            var tmp3 = value.Single;
            if (tmp3 != 0)
            {
                state.WriteFieldHeader(3, global::ProtoBuf.WireType.Varint);
                state.WriteByte(tmp3);
            }
        }
    }
}

// ---- ProtoModelAttributes.g.cs ----
// <auto-generated/>
#nullable enable
namespace ProtoBuf
{
    /// <summary>
    /// Marks a partial <see cref="global::ProtoBuf.Meta.TypeModel"/> subclass as a compile-time
    /// serialization model, to be populated by the protobuf-net generator.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class ProtoModelAttribute : global::System.Attribute
    {
    }

    /// <summary>
    /// Declares a root type that the associated model can serialize; every contract reachable
    /// from a root is included in the model automatically.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    internal sealed class ProtoSerializableAttribute : global::System.Attribute
    {
        /// <summary>
        /// Create a new instance.
        /// </summary>
        public ProtoSerializableAttribute(global::System.Type type) => Type = type;

        /// <summary>
        /// The root type to include in the model.
        /// </summary>
        public global::System.Type Type { get; }
    }

    /// <summary>
    /// Declares that the associated model serializes one type by way of another, for types
    /// that cannot carry <c>[ProtoContract(Surrogate = ...)]</c> themselves — a BCL type,
    /// or anything else you do not own.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is the compile-time equivalent of <c>RuntimeTypeModel.SetSurrogate</c>. The
    /// conversion is a cast in each direction unless <see cref="Converter"/> names a type
    /// supplying static conversion methods, which is how a type with no usable operators —
    /// <c>NodaTime.Duration</c>, say — is hooked up.
    /// </para>
    /// <para>
    /// Apply it to a model to configure that model alone, or to an <b>assembly</b> to offer
    /// the pairing to every model that references it — which is how a library can ship
    /// surrogates for types it supports, without each consumer restating them. A model's
    /// own declaration wins over one it merely references.
    /// </para>
    /// </remarks>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Class | global::System.AttributeTargets.Assembly,
        AllowMultiple = true, Inherited = false)]
    internal sealed class ProtoSurrogateAttribute : global::System.Attribute
    {
        /// <summary>
        /// Create a new instance.
        /// </summary>
        public ProtoSurrogateAttribute(global::System.Type type, global::System.Type surrogate)
        {
            Type = type;
            Surrogate = surrogate;
        }

        /// <summary>
        /// The type being serialized.
        /// </summary>
        public global::System.Type Type { get; }

        /// <summary>
        /// The type that carries its wire shape.
        /// </summary>
        public global::System.Type Surrogate { get; }

        /// <summary>
        /// A type declaring the static conversion methods named by <see cref="ToSurrogate"/>
        /// and <see cref="ToType"/>; when omitted, a cast is used in both directions.
        /// </summary>
        public global::System.Type? Converter { get; set; }

        /// <summary>
        /// The <see cref="Converter"/> method converting the type to its surrogate.
        /// </summary>
        public string? ToSurrogate { get; set; }

        /// <summary>
        /// The <see cref="Converter"/> method converting a surrogate back to the type.
        /// </summary>
        public string? ToType { get; set; }
    }
}
