// ---- AotFixtures.Defaults.DefaultsModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591

namespace AotFixtures.Defaults;

partial class DefaultsModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected DefaultsModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static DefaultsModel Instance { get; } = new DefaultsModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Declared>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Parsed>
    {
        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Declared>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Defaults.Declared global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Declared>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Defaults.Declared value)
        {
            value ??= new global::AotFixtures.Defaults.Declared();
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        value.Number = state.ReadInt32();
                        break;
                    }
                    case 2:
                    {
                        var tmp2 = state.ReadString();
                        if (tmp2 != null) value.Text = tmp2;
                        break;
                    }
                    case 3:
                    {
                        value.Flag = state.ReadBoolean();
                        break;
                    }
                    case 4:
                    {
                        value.Ratio = state.ReadDouble();
                        break;
                    }
                    case 5:
                    {
                        value.Big = state.ReadInt64();
                        break;
                    }
                    case 6:
                    {
                        value.Plain = state.ReadInt32();
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Declared>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Defaults.Declared value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Number;
            if (tmp1 != 5) state.WriteInt32Varint(1, tmp1);
            var tmp2 = value.Text;
            if (tmp2 != null && tmp2 != "abc")
            {
                state.WriteString(2, tmp2);
            }
            var tmp3 = value.Flag;
            if (tmp3 != true)
            {
                state.WriteFieldHeader(3, global::ProtoBuf.WireType.Varint);
                state.WriteBoolean(tmp3);
            }
            var tmp4 = value.Ratio;
            if (tmp4 != 2.5D)
            {
                state.WriteFieldHeader(4, global::ProtoBuf.WireType.Fixed64);
                state.WriteDouble(tmp4);
            }
            var tmp5 = value.Big;
            if (tmp5 != 7L)
            {
                state.WriteFieldHeader(5, global::ProtoBuf.WireType.Varint);
                state.WriteInt64(tmp5);
            }
            var tmp6 = value.Plain;
            if (tmp6 != 0) state.WriteInt32Varint(6, tmp6);
        }

        // raw read pass: skipped - member Number: [DefaultValue]

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Parsed>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Defaults.Parsed global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Parsed>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Defaults.Parsed value)
        {
            value ??= new global::AotFixtures.Defaults.Parsed();
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        value.ByName = (global::AotFixtures.Defaults.Shade)state.ReadUInt16();
                        break;
                    }
                    case 2:
                    {
                        value.ByValue = (global::AotFixtures.Defaults.Shade)state.ReadUInt16();
                        break;
                    }
                    case 3:
                    {
                        value.Letter = (char)state.ReadUInt16();
                        break;
                    }
                    case 4:
                    {
                        value.DirectChar = (char)state.ReadUInt16();
                        break;
                    }
                    case 5:
                    {
                        value.ByConverter = (global::AotFixtures.Defaults.Shade)state.ReadUInt16();
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Parsed>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Defaults.Parsed value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.ByName;
            if (tmp1 != (global::AotFixtures.Defaults.Shade)(2))
            {
                state.WriteFieldHeader(1, global::ProtoBuf.WireType.Varint);
                state.WriteUInt16((ushort)tmp1);
            }
            var tmp2 = value.ByValue;
            if (tmp2 != (global::AotFixtures.Defaults.Shade)(4))
            {
                state.WriteFieldHeader(2, global::ProtoBuf.WireType.Varint);
                state.WriteUInt16((ushort)tmp2);
            }
            var tmp3 = value.Letter;
            if (tmp3 != 'x')
            {
                state.WriteFieldHeader(3, global::ProtoBuf.WireType.Varint);
                state.WriteUInt16(tmp3);
            }
            var tmp4 = value.DirectChar;
            if (tmp4 != 'y')
            {
                state.WriteFieldHeader(4, global::ProtoBuf.WireType.Varint);
                state.WriteUInt16(tmp4);
            }
            var tmp5 = value.ByConverter;
            if (tmp5 != (global::AotFixtures.Defaults.Shade)(1))
            {
                state.WriteFieldHeader(5, global::ProtoBuf.WireType.Varint);
                state.WriteUInt16((ushort)tmp5);
            }
        }

        // raw read pass: skipped - member ByName: [DefaultValue]
    }
}
