// ---- AotFixtures.Defaults.DefaultsModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable PBN9002

namespace AotFixtures.Defaults;

partial class DefaultsModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected DefaultsModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static DefaultsModel Instance { get; } = new DefaultsModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Defaults.Declared>
        , global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Defaults.Parsed>
    {
        private static readonly ProtoBufGeneratedServices s_default = new ProtoBufGeneratedServices();

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Declared>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Defaults.Declared global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Declared>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Defaults.Declared value)
            => RawRead_AotFixtures_Defaults_Declared(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Declared>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Defaults.Declared value)
            => RawWrite_AotFixtures_Defaults_Declared(ref state, value, state.RawDepthBudget);

        public static void RawWrite_AotFixtures_Defaults_Declared(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Defaults.Declared value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Number;
            if (tmp1 != 5)
            {
                state.WriteRawTag((1 << 3) | 0);  // Number
                state.WriteRawVarint64(unchecked((ulong)(long)tmp1));
            }
            var tmp2 = value.Text;
            if (tmp2 != null && tmp2 != "abc")
            {
                state.WriteRawTag((2 << 3) | 2);  // Text
                state.WriteRawString(tmp2);
            }
            var tmp3 = value.Flag;
            if (tmp3 != true)
            {
                state.WriteRawTagBool((3 << 3) | 0, tmp3);  // Flag
            }
            var tmp4 = value.Ratio;
            if (tmp4 != 2.5D)
            {
                state.WriteRawTag((4 << 3) | 1);  // Ratio
                state.WriteRawDouble(tmp4);
            }
            var tmp5 = value.Big;
            if (tmp5 != 7L)
            {
                state.WriteRawTag((5 << 3) | 0);  // Big
                state.WriteRawVarint64(unchecked((ulong)tmp5));
            }
            var tmp6 = value.Plain;
            if (tmp6 != 0)
            {
                state.WriteRawTag((6 << 3) | 0);  // Plain
                state.WriteRawVarint64(unchecked((ulong)(long)tmp6));
            }
        }

        private static long Measure_AotFixtures_Defaults_Declared(global::AotFixtures.Defaults.Declared value, int depth, global::System.Collections.Generic.Dictionary<object, long> lengths)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.Number;
            if (tmp1 != 5) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp1));  // Number
            var tmp2 = value.Text;
            if (tmp2 != null && tmp2 != "abc")
            {
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawString(tmp2);  // Text
            }
            var tmp3 = value.Flag;
            if (tmp3 != true) len += 2;  // Flag
            var tmp4 = value.Ratio;
            if (tmp4 != 2.5D) len += 9;  // Ratio
            var tmp5 = value.Big;
            if (tmp5 != 7L) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)tmp5));  // Big
            var tmp6 = value.Plain;
            if (tmp6 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp6));  // Plain
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Defaults.Declared>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Defaults.Declared value)
            => global::ProtoBuf.ProtoWriter.State.TryMeasureRaw(context, out var depth, out var lengths)
                && Measure_AotFixtures_Defaults_Declared(value, depth, lengths) is var len && len <= int.MaxValue
                ? (int)len : -1;

        private static global::AotFixtures.Defaults.Declared RawRead_AotFixtures_Defaults_Declared(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Defaults.Declared value)
        {
            value ??= new global::AotFixtures.Defaults.Declared();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // Number, field 1, varint
                        value.Number = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (1 << 3) | 5:  // Number, field 1, fixed32
                        value.Number = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (1 << 3) | 1:  // Number, field 1, fixed64
                        value.Number = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (2 << 3) | 2:  // Text, field 2, length-prefixed
                    {
                        var tmp2 = state.ReadRawString();
                        if (tmp2 != null) value.Text = tmp2;
                        break;
                    }
                    case (3 << 3) | 0:  // Flag, field 3, varint
                        value.Flag = state.ReadRawVarint32() != 0;
                        break;
                    case (3 << 3) | 5:  // Flag, field 3, fixed32
                        value.Flag = state.ReadRawFixed32() != 0;
                        break;
                    case (3 << 3) | 1:  // Flag, field 3, fixed64
                        value.Flag = state.ReadRawFixed64() != 0;
                        break;
                    case (4 << 3) | 1:  // Ratio, field 4, fixed64
                        value.Ratio = state.ReadRawDouble();
                        break;
                    case (5 << 3) | 0:  // Big, field 5, varint
                        value.Big = unchecked((long)state.ReadRawVarint64());
                        break;
                    case (5 << 3) | 1:  // Big, field 5, fixed64
                        value.Big = unchecked((long)state.ReadRawFixed64());
                        break;
                    case (5 << 3) | 5:  // Big, field 5, fixed32
                        value.Big = (long)unchecked((int)state.ReadRawFixed32());
                        break;
                    case (6 << 3) | 0:  // Plain, field 6, varint
                        value.Plain = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (6 << 3) | 5:  // Plain, field 6, fixed32
                        value.Plain = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (6 << 3) | 1:  // Plain, field 6, fixed64
                        value.Plain = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2 or 3 or 4 or 5 or 6;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Parsed>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Defaults.Parsed global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Parsed>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Defaults.Parsed value)
            => RawRead_AotFixtures_Defaults_Parsed(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Defaults.Parsed>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Defaults.Parsed value)
            => RawWrite_AotFixtures_Defaults_Parsed(ref state, value, state.RawDepthBudget);

        public static void RawWrite_AotFixtures_Defaults_Parsed(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Defaults.Parsed value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.ByName;
            if (tmp1 != (global::AotFixtures.Defaults.Shade)(2))
            {
                state.WriteRawTag((1 << 3) | 0);  // ByName
                state.WriteRawVarint32((ushort)tmp1);
            }
            var tmp2 = value.ByValue;
            if (tmp2 != (global::AotFixtures.Defaults.Shade)(4))
            {
                state.WriteRawTag((2 << 3) | 0);  // ByValue
                state.WriteRawVarint32((ushort)tmp2);
            }
            var tmp3 = value.Letter;
            if (tmp3 != 'x')
            {
                state.WriteRawTag((3 << 3) | 0);  // Letter
                state.WriteRawVarint32(tmp3);
            }
            var tmp4 = value.DirectChar;
            if (tmp4 != 'y')
            {
                state.WriteRawTag((4 << 3) | 0);  // DirectChar
                state.WriteRawVarint32(tmp4);
            }
            var tmp5 = value.ByConverter;
            if (tmp5 != (global::AotFixtures.Defaults.Shade)(1))
            {
                state.WriteRawTag((5 << 3) | 0);  // ByConverter
                state.WriteRawVarint32((ushort)tmp5);
            }
        }

        private static long Measure_AotFixtures_Defaults_Parsed(global::AotFixtures.Defaults.Parsed value, int depth, global::System.Collections.Generic.Dictionary<object, long> lengths)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.ByName;
            if (tmp1 != (global::AotFixtures.Defaults.Shade)(2)) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint32((ushort)tmp1);  // ByName
            var tmp2 = value.ByValue;
            if (tmp2 != (global::AotFixtures.Defaults.Shade)(4)) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint32((ushort)tmp2);  // ByValue
            var tmp3 = value.Letter;
            if (tmp3 != 'x') len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint32(tmp3);  // Letter
            var tmp4 = value.DirectChar;
            if (tmp4 != 'y') len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint32(tmp4);  // DirectChar
            var tmp5 = value.ByConverter;
            if (tmp5 != (global::AotFixtures.Defaults.Shade)(1)) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint32((ushort)tmp5);  // ByConverter
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Defaults.Parsed>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Defaults.Parsed value)
            => global::ProtoBuf.ProtoWriter.State.TryMeasureRaw(context, out var depth, out var lengths)
                && Measure_AotFixtures_Defaults_Parsed(value, depth, lengths) is var len && len <= int.MaxValue
                ? (int)len : -1;

        private static global::AotFixtures.Defaults.Parsed RawRead_AotFixtures_Defaults_Parsed(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Defaults.Parsed value)
        {
            value ??= new global::AotFixtures.Defaults.Parsed();
            uint tag = state.ReadRawTagOrPending();
            while (tag != 0)
            {
                switch (tag)
                {
                    // raw read pass: legacy-mode - member ByName: kind UInt16
                    case (1 << 3) | 0:
                    case (1 << 3) | 1:
                    case (1 << 3) | 2:  // ByName, field 1
                    case (1 << 3) | 3:
                    case (1 << 3) | 5:
                    {
                        state.StashTag(tag);
                        value.ByName = (global::AotFixtures.Defaults.Shade)state.ReadUInt16();
                        break;
                    }
                    // raw read pass: legacy-mode - member ByValue: kind UInt16
                    case (2 << 3) | 0:
                    case (2 << 3) | 1:
                    case (2 << 3) | 2:  // ByValue, field 2
                    case (2 << 3) | 3:
                    case (2 << 3) | 5:
                    {
                        state.StashTag(tag);
                        value.ByValue = (global::AotFixtures.Defaults.Shade)state.ReadUInt16();
                        break;
                    }
                    // raw read pass: legacy-mode - member Letter: kind Char
                    case (3 << 3) | 0:
                    case (3 << 3) | 1:
                    case (3 << 3) | 2:  // Letter, field 3
                    case (3 << 3) | 3:
                    case (3 << 3) | 5:
                    {
                        state.StashTag(tag);
                        value.Letter = (char)state.ReadUInt16();
                        break;
                    }
                    // raw read pass: legacy-mode - member DirectChar: kind Char
                    case (4 << 3) | 0:
                    case (4 << 3) | 1:
                    case (4 << 3) | 2:  // DirectChar, field 4
                    case (4 << 3) | 3:
                    case (4 << 3) | 5:
                    {
                        state.StashTag(tag);
                        value.DirectChar = (char)state.ReadUInt16();
                        break;
                    }
                    // raw read pass: legacy-mode - member ByConverter: kind UInt16
                    case (5 << 3) | 0:
                    case (5 << 3) | 1:
                    case (5 << 3) | 2:  // ByConverter, field 5
                    case (5 << 3) | 3:
                    case (5 << 3) | 5:
                    {
                        state.StashTag(tag);
                        value.ByConverter = (global::AotFixtures.Defaults.Shade)state.ReadUInt16();
                        break;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTagOrPending();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2 or 3 or 4 or 5;
        }
    }
}
