// ---- AotFixtures.Getter.GetterModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591

namespace AotFixtures.Getter;

partial class GetterModel
{
    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Getters>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Nested>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Point>
    {
        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Getters>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Getter.Getters global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Getters>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Getter.Getters value)
        {
            value ??= new global::AotFixtures.Getter.Getters();
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        var tmp1 = value.Numbers;
                        global::ProtoBuf.Serializers.RepeatedSerializer.CreateList<int>().ReadRepeated(ref state, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp1);
                        break;
                    }
                    case 2:
                    {
                        var tmp2 = value.Map;
                        global::ProtoBuf.Serializers.MapSerializer.CreateDictionary<int, string>().ReadMap(ref state, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp2, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString);
                        break;
                    }
                    case 3:
                    {
                        var tmp3 = value.Child;
                        state.ReadMessage<global::AotFixtures.Getter.Nested>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp3, this);
                        break;
                    }
                    case 4:
                    {
                        state.ReadInt32();
                        break;
                    }
                    case 5:
                    {
                        state.ReadString();
                        break;
                    }
                    case 6:
                    {
                        var tmp6 = value.Blob;
                        state.AppendBytes(tmp6);
                        break;
                    }
                    case 7:
                    {
                        state.ReadInt32();
                        break;
                    }
                    case 8:
                    {
                        state.ReadInt32();
                        break;
                    }
                    case 9:
                    {
                        global::ProtoBuf.BclHelpers.ReadDateTime(ref state);
                        break;
                    }
                    case 10:
                    {
                        var tmp10 = value.Array;
                        global::ProtoBuf.Serializers.RepeatedSerializer.CreateVector<int>().ReadRepeated(ref state, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp10);
                        break;
                    }
                    case 11:
                    {
                        var tmp11 = value.Where;
                        state.ReadMessage<global::AotFixtures.Getter.Point>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp11, this);
                        break;
                    }
                    case 12:
                    {
                        var tmp12 = value.Maybe2.GetValueOrDefault();
                        state.ReadMessage<global::AotFixtures.Getter.Point>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp12, this);
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Getters>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Getter.Getters value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Numbers;
            if (tmp1 != null)
            {
                global::ProtoBuf.Serializers.RepeatedSerializer.CreateList<int>().WriteRepeated(ref state, 1, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp1);
            }
            var tmp2 = value.Map;
            if (tmp2 != null)
            {
                global::ProtoBuf.Serializers.MapSerializer.CreateDictionary<int, string>().WriteMap(ref state, 2, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp2, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString);
            }
            var tmp3 = value.Child;
            state.WriteMessage<global::AotFixtures.Getter.Nested>(3, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp3, this);
            var tmp4 = value.Value;
            if (tmp4 != 0) state.WriteInt32Varint(4, tmp4);
            var tmp5 = value.Text;
            state.WriteString(5, tmp5);
            var tmp6 = value.Blob;
            if (tmp6 != null)
            {
                state.WriteFieldHeader(6, global::ProtoBuf.WireType.String);
                state.WriteBytes(tmp6);
            }
            var tmp7 = value.Maybe;
            if (tmp7.HasValue)
            {
                var val7 = tmp7.GetValueOrDefault();
                state.WriteInt32Varint(7, val7);
            }
            var tmp8 = value.Colour;
            if (tmp8 != default(global::AotFixtures.Getter.Shade)) state.WriteInt32Varint(8, (int)tmp8);
            var tmp9 = value.When;
            state.WriteFieldHeader(9, global::ProtoBuf.WireType.String);
            global::ProtoBuf.BclHelpers.WriteDateTime(ref state, tmp9);
            var tmp10 = value.Array;
            if (tmp10 != null)
            {
                global::ProtoBuf.Serializers.RepeatedSerializer.CreateVector<int>().WriteRepeated(ref state, 10, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp10);
            }
            var tmp11 = value.Where;
            state.WriteMessage<global::AotFixtures.Getter.Point>(11, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp11, this);
            var tmp12 = value.Maybe2;
            if (tmp12.HasValue)
            {
                state.WriteMessage<global::AotFixtures.Getter.Point>(12, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp12.GetValueOrDefault(), this);
            }
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Nested>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Getter.Nested global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Nested>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Getter.Nested value)
        {
            value ??= new global::AotFixtures.Getter.Nested();
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        value.Id = state.ReadInt32();
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Nested>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Getter.Nested value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Id;
            if (tmp1 != 0) state.WriteInt32Varint(1, tmp1);
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Point>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Getter.Point global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Point>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Getter.Point value)
        {
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        value.X = state.ReadInt32();
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Point>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Getter.Point value)
        {
            var tmp1 = value.X;
            if (tmp1 != 0) state.WriteInt32Varint(1, tmp1);
        }
    }
}
