// ---- AotFixtures.Getter.GetterModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable PBN9002

namespace AotFixtures.Getter;

partial class GetterModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected GetterModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static GetterModel Instance { get; } = new GetterModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Getters>
        , global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Getter.Nested>
        , global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Getter.Point>
    {
        private static readonly ProtoBufGeneratedServices s_default = new ProtoBufGeneratedServices();

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Getters>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Getter.Getters global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Getters>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Getter.Getters value)
            => RawRead_AotFixtures_Getter_Getters(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Getters>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Getter.Getters value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Numbers;
            if (tmp1 != null)
            {
                foreach (var item1 in global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(tmp1))
                {
                    state.WriteRawTag((1 << 3) | 0);  // Numbers
                    state.WriteRawVarint64(unchecked((ulong)(long)item1));
                }
            }
            var tmp2 = value.Map;
            if (tmp2 != null)
            {
                global::ProtoBuf.Serializers.MapSerializer.CreateDictionary<int, string>().WriteMap(ref state, 2, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp2, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString);
            }
            var tmp3 = value.Child;
            if (tmp3 != null)
            {
                state.WriteRawTag((3 << 3) | 2);  // Child
                if (!state.RawLengths.TryGetValue(tmp3, out var len3))
                {
                    len3 = Measure_AotFixtures_Getter_Nested(tmp3, state.RawDepthBudget, state.RawLengths);
                    state.RawLengths[tmp3] = len3;
                }
                state.WriteRawVarint64((ulong)len3);
                RawWrite_AotFixtures_Getter_Nested(ref state, tmp3, state.RawDepthBudget);
            }
            var tmp4 = value.Value;
            if (tmp4 != 0)
            {
                state.WriteRawTag((4 << 3) | 0);  // Value
                state.WriteRawVarint64(unchecked((ulong)(long)tmp4));
            }
            var tmp5 = value.Text;
            if (tmp5 != null)
            {
                state.WriteRawTag((5 << 3) | 2);  // Text
                state.WriteRawString(tmp5);
            }
            var tmp6 = value.Blob;
            if (tmp6 != null)
            {
                state.WriteRawTag((6 << 3) | 2);  // Blob
                state.WriteRawBytes(tmp6);
            }
            var tmp7 = value.Maybe;
            if (tmp7.HasValue)
            {
                var val7 = tmp7.GetValueOrDefault();
                state.WriteRawTag((7 << 3) | 0);  // Maybe
                state.WriteRawVarint64(unchecked((ulong)(long)val7));
            }
            var tmp8 = value.Colour;
            if (tmp8 != default(global::AotFixtures.Getter.Shade))
            {
                state.WriteRawTag((8 << 3) | 0);  // Colour
                state.WriteRawVarint64(unchecked((ulong)(long)(int)tmp8));
            }
            var tmp9 = value.When;
            state.WriteFieldHeader(9, global::ProtoBuf.WireType.String);
            global::ProtoBuf.BclHelpers.WriteDateTime(ref state, tmp9);
            var tmp10 = value.Array;
            if (tmp10 != null)
            {
                foreach (var item10 in tmp10)
                {
                    state.WriteRawTag((10 << 3) | 0);  // Array
                    state.WriteRawVarint64(unchecked((ulong)(long)item10));
                }
            }
            var tmp11 = value.Where;
            state.WriteRawTag((11 << 3) | 2);  // Where
            var len11 = Measure_AotFixtures_Getter_Point(tmp11, state.RawDepthBudget, state.RawLengths);
            state.WriteRawVarint64((ulong)len11);
            RawWrite_AotFixtures_Getter_Point(ref state, tmp11, state.RawDepthBudget);
            var tmp12 = value.Maybe2;
            if (tmp12.HasValue)
            {
                state.WriteMessage<global::AotFixtures.Getter.Point>(12, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp12.GetValueOrDefault(), this);
            }
        }

        private static global::AotFixtures.Getter.Getters RawRead_AotFixtures_Getter_Getters(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Getter.Getters value)
        {
            value ??= new global::AotFixtures.Getter.Getters();
            uint tag = state.ReadRawTagOrPending();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // Numbers, field 1, unpacked run (varint)
                        Field_AotFixtures_Getter_Getters_Numbers(value) ??= new global::System.Collections.Generic.List<int>();
                        do { value.Numbers.Add(unchecked((int)state.ReadRawVarint32())); }
                        while ((tag = state.ReadRawTag()) == ((1 << 3) | 0));
                        continue;
                    case (1 << 3) | 2:  // Numbers, field 1, packed
                        Field_AotFixtures_Getter_Getters_Numbers(value) ??= new global::System.Collections.Generic.List<int>();
                        state.ReadPackedVarint32(value.Numbers);
                        break;
                    case (1 << 3) | 5:  // Numbers, field 1, fixed32
                        Field_AotFixtures_Getter_Getters_Numbers(value) ??= new global::System.Collections.Generic.List<int>();
                        value.Numbers.Add(unchecked((int)state.ReadRawFixed32()));
                        break;
                    case (1 << 3) | 1:  // Numbers, field 1, fixed64
                        Field_AotFixtures_Getter_Getters_Numbers(value) ??= new global::System.Collections.Generic.List<int>();
                        value.Numbers.Add(checked((int)unchecked((long)state.ReadRawFixed64())));
                        break;
                    // raw read pass: legacy-mode - member Map: map without a plain setter
                    case (2 << 3) | 0:
                    case (2 << 3) | 1:
                    case (2 << 3) | 2:  // Map, field 2
                    case (2 << 3) | 3:
                    case (2 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp2 = value.Map;
                        tmp2 = global::ProtoBuf.Serializers.MapSerializer.CreateDictionary<int, string>().ReadMap(ref state, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp2, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString);
                        if (tmp2 != null) Field_AotFixtures_Getter_Getters_Map(value) = tmp2;
                        break;
                    }
                    // raw read pass: legacy-mode - member Child: accessor-reached setter
                    case (3 << 3) | 0:
                    case (3 << 3) | 1:
                    case (3 << 3) | 2:  // Child, field 3
                    case (3 << 3) | 3:
                    case (3 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp3 = value.Child;
                        tmp3 = state.ReadMessage<global::AotFixtures.Getter.Nested>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp3, s_default);
                        if (tmp3 != null) Field_AotFixtures_Getter_Getters_Child(value) = tmp3;
                        break;
                    }
                    // raw read pass: legacy-mode - member Value: accessor-reached setter
                    case (4 << 3) | 0:
                    case (4 << 3) | 1:
                    case (4 << 3) | 2:  // Value, field 4
                    case (4 << 3) | 3:
                    case (4 << 3) | 5:
                    {
                        state.StashTag(tag);
                        Field_AotFixtures_Getter_Getters_Value(value) = state.ReadInt32();
                        break;
                    }
                    // raw read pass: legacy-mode - member Text: accessor-reached setter
                    case (5 << 3) | 0:
                    case (5 << 3) | 1:
                    case (5 << 3) | 2:  // Text, field 5
                    case (5 << 3) | 3:
                    case (5 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp5 = state.ReadString();
                        if (tmp5 != null) Field_AotFixtures_Getter_Getters_Text(value) = tmp5;
                        break;
                    }
                    // raw read pass: legacy-mode - member Blob: accessor-reached setter
                    case (6 << 3) | 0:
                    case (6 << 3) | 1:
                    case (6 << 3) | 2:  // Blob, field 6
                    case (6 << 3) | 3:
                    case (6 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp6 = value.Blob;
                        tmp6 = state.AppendBytes(tmp6);
                        if (tmp6 != null) Field_AotFixtures_Getter_Getters_Blob(value) = tmp6;
                        break;
                    }
                    // raw read pass: legacy-mode - member Maybe: accessor-reached setter
                    case (7 << 3) | 0:
                    case (7 << 3) | 1:
                    case (7 << 3) | 2:  // Maybe, field 7
                    case (7 << 3) | 3:
                    case (7 << 3) | 5:
                    {
                        state.StashTag(tag);
                        Field_AotFixtures_Getter_Getters_Maybe(value) = state.ReadInt32();
                        break;
                    }
                    // raw read pass: legacy-mode - member Colour: accessor-reached setter
                    case (8 << 3) | 0:
                    case (8 << 3) | 1:
                    case (8 << 3) | 2:  // Colour, field 8
                    case (8 << 3) | 3:
                    case (8 << 3) | 5:
                    {
                        state.StashTag(tag);
                        Field_AotFixtures_Getter_Getters_Colour(value) = (global::AotFixtures.Getter.Shade)state.ReadInt32();
                        break;
                    }
                    // raw read pass: legacy-mode - member When: accessor-reached setter
                    case (9 << 3) | 0:
                    case (9 << 3) | 1:
                    case (9 << 3) | 2:  // When, field 9
                    case (9 << 3) | 3:
                    case (9 << 3) | 5:
                    {
                        state.StashTag(tag);
                        Field_AotFixtures_Getter_Getters_When(value) = global::ProtoBuf.BclHelpers.ReadDateTime(ref state);
                        break;
                    }
                    // raw read pass: legacy-mode - member Array: array without a plain setter
                    case (10 << 3) | 0:
                    case (10 << 3) | 1:
                    case (10 << 3) | 2:  // Array, field 10
                    case (10 << 3) | 3:
                    case (10 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp10 = value.Array;
                        tmp10 = global::ProtoBuf.Serializers.RepeatedSerializer.CreateVector<int>().ReadRepeated(ref state, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp10);
                        if (tmp10 != null) Field_AotFixtures_Getter_Getters_Array(value) = tmp10;
                        break;
                    }
                    // raw read pass: legacy-mode - member Where: accessor-reached setter
                    case (11 << 3) | 0:
                    case (11 << 3) | 1:
                    case (11 << 3) | 2:  // Where, field 11
                    case (11 << 3) | 3:
                    case (11 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp11 = value.Where;
                        Field_AotFixtures_Getter_Getters_Where(value) = state.ReadMessage<global::AotFixtures.Getter.Point>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp11, s_default);
                        break;
                    }
                    // raw read pass: legacy-mode - member Maybe2: accessor-reached setter
                    case (12 << 3) | 0:
                    case (12 << 3) | 1:
                    case (12 << 3) | 2:  // Maybe2, field 12
                    case (12 << 3) | 3:
                    case (12 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp12 = value.Maybe2.GetValueOrDefault();
                        Field_AotFixtures_Getter_Getters_Maybe2(value) = state.ReadMessage<global::AotFixtures.Getter.Point>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp12, s_default);
                        break;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTagOrPending();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2 or 3 or 4 or 5 or 6 or 7 or 8 or 9 or 10 or 11 or 12;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Nested>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Getter.Nested global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Nested>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Getter.Nested value)
            => RawRead_AotFixtures_Getter_Nested(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Nested>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Getter.Nested value)
            => RawWrite_AotFixtures_Getter_Nested(ref state, value, state.RawDepthBudget);

        public static void RawWrite_AotFixtures_Getter_Nested(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Getter.Nested value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Id;
            if (tmp1 != 0)
            {
                state.WriteRawTag((1 << 3) | 0);  // Id
                state.WriteRawVarint64(unchecked((ulong)(long)tmp1));
            }
        }

        private static long Measure_AotFixtures_Getter_Nested(global::AotFixtures.Getter.Nested value, int depth, global::System.Collections.Generic.Dictionary<object, long> lengths)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.Id;
            if (tmp1 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp1));  // Id
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Getter.Nested>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Getter.Nested value)
            => global::ProtoBuf.ProtoWriter.State.TryMeasureRaw(context, out var depth, out var lengths)
                && Measure_AotFixtures_Getter_Nested(value, depth, lengths) is var len && len <= int.MaxValue
                ? (int)len : -1;

        private static global::AotFixtures.Getter.Nested RawRead_AotFixtures_Getter_Nested(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Getter.Nested value)
        {
            value ??= new global::AotFixtures.Getter.Nested();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // Id, field 1, varint
                        value.Id = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (1 << 3) | 5:  // Id, field 1, fixed32
                        value.Id = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (1 << 3) | 1:  // Id, field 1, fixed64
                        value.Id = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Point>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Getter.Point global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Point>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Getter.Point value)
        {
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        value.X = state.ReadInt32();
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Getter.Point>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Getter.Point value)
            => RawWrite_AotFixtures_Getter_Point(ref state, value, state.RawDepthBudget);

        public static void RawWrite_AotFixtures_Getter_Point(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Getter.Point value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            var tmp1 = value.X;
            if (tmp1 != 0)
            {
                state.WriteRawTag((1 << 3) | 0);  // X
                state.WriteRawVarint64(unchecked((ulong)(long)tmp1));
            }
        }

        private static long Measure_AotFixtures_Getter_Point(global::AotFixtures.Getter.Point value, int depth, global::System.Collections.Generic.Dictionary<object, long> lengths)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.X;
            if (tmp1 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp1));  // X
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Getter.Point>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Getter.Point value)
            => global::ProtoBuf.ProtoWriter.State.TryMeasureRaw(context, out var depth, out var lengths)
                && Measure_AotFixtures_Getter_Point(value, depth, lengths) is var len && len <= int.MaxValue
                ? (int)len : -1;

        // raw read pass: skipped - contract shape (value type, tuple, surrogate or external serializer)

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<Numbers>k__BackingField")]
        private static extern ref global::System.Collections.Generic.List<int> Field_AotFixtures_Getter_Getters_Numbers(global::AotFixtures.Getter.Getters target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<Map>k__BackingField")]
        private static extern ref global::System.Collections.Generic.Dictionary<int, string> Field_AotFixtures_Getter_Getters_Map(global::AotFixtures.Getter.Getters target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<Child>k__BackingField")]
        private static extern ref global::AotFixtures.Getter.Nested Field_AotFixtures_Getter_Getters_Child(global::AotFixtures.Getter.Getters target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<Value>k__BackingField")]
        private static extern ref int Field_AotFixtures_Getter_Getters_Value(global::AotFixtures.Getter.Getters target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<Text>k__BackingField")]
        private static extern ref string Field_AotFixtures_Getter_Getters_Text(global::AotFixtures.Getter.Getters target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<Blob>k__BackingField")]
        private static extern ref byte[] Field_AotFixtures_Getter_Getters_Blob(global::AotFixtures.Getter.Getters target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<Maybe>k__BackingField")]
        private static extern ref int? Field_AotFixtures_Getter_Getters_Maybe(global::AotFixtures.Getter.Getters target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<Colour>k__BackingField")]
        private static extern ref global::AotFixtures.Getter.Shade Field_AotFixtures_Getter_Getters_Colour(global::AotFixtures.Getter.Getters target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<When>k__BackingField")]
        private static extern ref global::System.DateTime Field_AotFixtures_Getter_Getters_When(global::AotFixtures.Getter.Getters target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<Array>k__BackingField")]
        private static extern ref int[] Field_AotFixtures_Getter_Getters_Array(global::AotFixtures.Getter.Getters target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<Where>k__BackingField")]
        private static extern ref global::AotFixtures.Getter.Point Field_AotFixtures_Getter_Getters_Where(global::AotFixtures.Getter.Getters target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "<Maybe2>k__BackingField")]
        private static extern ref global::AotFixtures.Getter.Point? Field_AotFixtures_Getter_Getters_Maybe2(global::AotFixtures.Getter.Getters target);
    }
}
