// ---- AotFixtures.ImplicitIgnore.ImplicitIgnoreModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591

namespace AotFixtures.ImplicitIgnore;

partial class ImplicitIgnoreModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected ImplicitIgnoreModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static ImplicitIgnoreModel Instance { get; } = new ImplicitIgnoreModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.ImplicitIgnore.Excluded>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.ImplicitIgnore.PartiallyPinned>
    {
        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.ImplicitIgnore.Excluded>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.ImplicitIgnore.Excluded global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.ImplicitIgnore.Excluded>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.ImplicitIgnore.Excluded value)
            => RawRead_AotFixtures_ImplicitIgnore_Excluded(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.ImplicitIgnore.Excluded>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.ImplicitIgnore.Excluded value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Pinned;
            if (tmp1 != 0) state.WriteInt32Varint(1, tmp1);
            var tmp4 = value.ImplicitField;
            if (tmp4 != 0) state.WriteInt32Varint(4, tmp4);
            var tmp5 = value.ImplicitProperty;
            if (tmp5 != 0) state.WriteInt32Varint(5, tmp5);
        }

        public static global::AotFixtures.ImplicitIgnore.Excluded RawRead_AotFixtures_ImplicitIgnore_Excluded(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.ImplicitIgnore.Excluded value)
        {
            value ??= new global::AotFixtures.ImplicitIgnore.Excluded();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // Pinned, field 1, varint
                        value.Pinned = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (1 << 3) | 5:  // Pinned, field 1, fixed32
                        value.Pinned = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (1 << 3) | 1:  // Pinned, field 1, fixed64
                        value.Pinned = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (4 << 3) | 0:  // ImplicitField, field 4, varint
                        value.ImplicitField = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (4 << 3) | 5:  // ImplicitField, field 4, fixed32
                        value.ImplicitField = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (4 << 3) | 1:  // ImplicitField, field 4, fixed64
                        value.ImplicitField = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (5 << 3) | 0:  // ImplicitProperty, field 5, varint
                        value.ImplicitProperty = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (5 << 3) | 5:  // ImplicitProperty, field 5, fixed32
                        value.ImplicitProperty = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (5 << 3) | 1:  // ImplicitProperty, field 5, fixed64
                        value.ImplicitProperty = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) switch
            {
                1 or 4 or 5 => true,
                _ => false,
            };
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.ImplicitIgnore.PartiallyPinned>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.ImplicitIgnore.PartiallyPinned global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.ImplicitIgnore.PartiallyPinned>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.ImplicitIgnore.PartiallyPinned value)
            => RawRead_AotFixtures_ImplicitIgnore_PartiallyPinned(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.ImplicitIgnore.PartiallyPinned>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.ImplicitIgnore.PartiallyPinned value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp2 = value.Beta;
            if (tmp2 != 0) state.WriteInt32Varint(2, tmp2);
            var tmp10 = value.Alpha;
            if (tmp10 != 0) state.WriteInt32Varint(10, tmp10);
            var tmp11 = value.Gamma;
            if (tmp11 != 0) state.WriteInt32Varint(11, tmp11);
        }

        public static global::AotFixtures.ImplicitIgnore.PartiallyPinned RawRead_AotFixtures_ImplicitIgnore_PartiallyPinned(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.ImplicitIgnore.PartiallyPinned value)
        {
            value ??= new global::AotFixtures.ImplicitIgnore.PartiallyPinned();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (2 << 3) | 0:  // Beta, field 2, varint
                        value.Beta = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (2 << 3) | 5:  // Beta, field 2, fixed32
                        value.Beta = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (2 << 3) | 1:  // Beta, field 2, fixed64
                        value.Beta = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (10 << 3) | 0:  // Alpha, field 10, varint
                        value.Alpha = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (10 << 3) | 5:  // Alpha, field 10, fixed32
                        value.Alpha = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (10 << 3) | 1:  // Alpha, field 10, fixed64
                        value.Alpha = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (11 << 3) | 0:  // Gamma, field 11, varint
                        value.Gamma = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (11 << 3) | 5:  // Gamma, field 11, fixed32
                        value.Gamma = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (11 << 3) | 1:  // Gamma, field 11, fixed64
                        value.Gamma = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) switch
            {
                2 or 10 or 11 => true,
                _ => false,
            };
        }
    }
}
