// ---- AotFixtures.Keywords.KeywordsModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable PBN9002

namespace AotFixtures.Keywords;

partial class KeywordsModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected KeywordsModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static KeywordsModel Instance { get; } = new KeywordsModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Keywords.Inner>
        , global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Keywords.Keywords>
        , global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Keywords.Pair>
    {
        private static readonly ProtoBufGeneratedServices s_default = new ProtoBufGeneratedServices();

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Keywords.Inner>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Keywords.Inner global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Keywords.Inner>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Keywords.Inner value)
            => RawRead_AotFixtures_Keywords_Inner(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Keywords.Inner>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Keywords.Inner value)
            => RawWrite_AotFixtures_Keywords_Inner(ref state, value, state.RawDepthBudget);

        public static void RawWrite_AotFixtures_Keywords_Inner(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Keywords.Inner value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.@int;
            if (tmp1 != 0)
            {
                state.WriteRawTag((1 << 3) | 0);  // int
                state.WriteRawVarint64(unchecked((ulong)(long)tmp1));
            }
        }

        private static long Measure_AotFixtures_Keywords_Inner(global::AotFixtures.Keywords.Inner value, int depth, global::System.Collections.Generic.Dictionary<object, long> lengths)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.@int;
            if (tmp1 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp1));  // int
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Keywords.Inner>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Keywords.Inner value)
            => global::ProtoBuf.ProtoWriter.State.TryMeasureRaw(context, out var depth, out var lengths)
                && Measure_AotFixtures_Keywords_Inner(value, depth, lengths) is var len && len <= int.MaxValue
                ? (int)len : -1;

        private static global::AotFixtures.Keywords.Inner RawRead_AotFixtures_Keywords_Inner(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Keywords.Inner value)
        {
            value ??= new global::AotFixtures.Keywords.Inner();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // int, field 1, varint
                        value.@int = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (1 << 3) | 5:  // int, field 1, fixed32
                        value.@int = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (1 << 3) | 1:  // int, field 1, fixed64
                        value.@int = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Keywords.Keywords>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Keywords.Keywords global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Keywords.Keywords>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Keywords.Keywords value)
            => RawRead_AotFixtures_Keywords_Keywords(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Keywords.Keywords>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Keywords.Keywords value)
            => RawWrite_AotFixtures_Keywords_Keywords(ref state, value, state.RawDepthBudget);

        public static void RawWrite_AotFixtures_Keywords_Keywords(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Keywords.Keywords value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.@case;
            if (tmp1 != 0)
            {
                state.WriteRawTag((1 << 3) | 0);  // case
                state.WriteRawVarint64(unchecked((ulong)(long)tmp1));
            }
            var tmp2 = value.@event;
            if (tmp2 != null)
            {
                state.WriteRawTag((2 << 3) | 2);  // event
                state.WriteRawString(tmp2);
            }
            var tmp3 = value.@params;
            if (tmp3 != null)
            {
                foreach (var item3 in global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(tmp3))
                {
                    state.WriteRawTag((3 << 3) | 0);  // params
                    state.WriteRawVarint64(unchecked((ulong)(long)item3));
                }
            }
            var tmp4 = value.@class;
            if (tmp4 != null)
            {
                state.WriteRawTag((4 << 3) | 2);  // class
                if (!state.RawLengths.TryGetValue(tmp4, out var len4))
                {
                    len4 = Measure_AotFixtures_Keywords_Inner(tmp4, state.RawDepthBudget, state.RawLengths);
                    state.RawLengths[tmp4] = len4;
                }
                state.WriteRawVarint64((ulong)len4);
                RawWrite_AotFixtures_Keywords_Inner(ref state, tmp4, depth);
            }
            var tmp5 = value.@lock;
            if (tmp5 != null)
            {
                state.WriteRawTag((5 << 3) | 2);  // lock
                if (!state.RawLengths.TryGetValue(tmp5, out var len5))
                {
                    len5 = Measure_AotFixtures_Keywords_Pair(tmp5, state.RawDepthBudget, state.RawLengths);
                    state.RawLengths[tmp5] = len5;
                }
                state.WriteRawVarint64((ulong)len5);
                RawWrite_AotFixtures_Keywords_Pair(ref state, tmp5, depth);
            }
            var tmp6 = value.value;
            if (tmp6 != 0)
            {
                state.WriteRawTag((6 << 3) | 0);  // value
                state.WriteRawVarint64(unchecked((ulong)(long)tmp6));
            }
        }

        private static long Measure_AotFixtures_Keywords_Keywords(global::AotFixtures.Keywords.Keywords value, int depth, global::System.Collections.Generic.Dictionary<object, long> lengths)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.@case;
            if (tmp1 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp1));  // case
            var tmp2 = value.@event;
            if (tmp2 != null)
            {
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawString(tmp2);  // event
            }
            var tmp3 = value.@params;
            if (tmp3 != null)
            {
                foreach (var item3 in global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(tmp3))
                {
                    len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)item3));
                }
            }
            var tmp4 = value.@class;
            if (tmp4 != null)
            {
                if (!lengths.TryGetValue(tmp4, out var len4))
                {
                    len4 = Measure_AotFixtures_Keywords_Inner(tmp4, depth, lengths);
                    lengths[tmp4] = len4;
                }
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64((ulong)len4) + len4;  // class
            }
            var tmp5 = value.@lock;
            if (tmp5 != null)
            {
                if (!lengths.TryGetValue(tmp5, out var len5))
                {
                    len5 = Measure_AotFixtures_Keywords_Pair(tmp5, depth, lengths);
                    lengths[tmp5] = len5;
                }
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64((ulong)len5) + len5;  // lock
            }
            var tmp6 = value.value;
            if (tmp6 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp6));  // value
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Keywords.Keywords>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Keywords.Keywords value)
            => global::ProtoBuf.ProtoWriter.State.TryMeasureRaw(context, out var depth, out var lengths)
                && Measure_AotFixtures_Keywords_Keywords(value, depth, lengths) is var len && len <= int.MaxValue
                ? (int)len : -1;

        private static global::AotFixtures.Keywords.Keywords RawRead_AotFixtures_Keywords_Keywords(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Keywords.Keywords value)
        {
            value ??= new global::AotFixtures.Keywords.Keywords();
            uint tag = state.ReadRawTagOrPending();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // case, field 1, varint
                        value.@case = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (1 << 3) | 5:  // case, field 1, fixed32
                        value.@case = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (1 << 3) | 1:  // case, field 1, fixed64
                        value.@case = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (2 << 3) | 2:  // event, field 2, length-prefixed
                    {
                        var tmp2 = state.ReadRawString();
                        if (tmp2 != null) value.@event = tmp2;
                        break;
                    }
                    case (3 << 3) | 0:  // params, field 3, unpacked run (varint)
                        value.@params ??= new global::System.Collections.Generic.List<int>();
                        do { value.@params.Add(unchecked((int)state.ReadRawVarint32())); }
                        while ((tag = state.ReadRawTag()) == ((3 << 3) | 0));
                        continue;
                    case (3 << 3) | 2:  // params, field 3, packed
                        value.@params ??= new global::System.Collections.Generic.List<int>();
                        state.ReadPackedVarint32(value.@params);
                        break;
                    case (3 << 3) | 5:  // params, field 3, fixed32
                        value.@params ??= new global::System.Collections.Generic.List<int>();
                        value.@params.Add(unchecked((int)state.ReadRawFixed32()));
                        break;
                    case (3 << 3) | 1:  // params, field 3, fixed64
                        value.@params ??= new global::System.Collections.Generic.List<int>();
                        value.@params.Add(checked((int)unchecked((long)state.ReadRawFixed64())));
                        break;
                    case (4 << 3) | 2:  // class, field 4, length-prefixed
                    case (4 << 3) | 3:  // class, field 4, group
                    {
                        var scope = state.PushScope(tag);
                        value.@class = RawRead_AotFixtures_Keywords_Inner(ref state, value.@class);
                        state.PopScope(scope);
                        break;
                    }
                    // raw read pass: legacy-mode - member lock: target type not raw-eligible
                    case (5 << 3) | 0:
                    case (5 << 3) | 1:
                    case (5 << 3) | 2:  // lock, field 5
                    case (5 << 3) | 3:
                    case (5 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp5 = value.@lock;
                        tmp5 = state.ReadMessage<global::AotFixtures.Keywords.Pair>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp5, s_default);
                        if (tmp5 != null) value.@lock = tmp5;
                        break;
                    }
                    case (6 << 3) | 0:  // value, field 6, varint
                        value.value = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (6 << 3) | 5:  // value, field 6, fixed32
                        value.value = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (6 << 3) | 1:  // value, field 6, fixed64
                        value.value = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTagOrPending();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2 or 3 or 4 or 5 or 6;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Keywords.Pair>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Keywords.Pair global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Keywords.Pair>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Keywords.Pair value)
        {
            int arg1 = default;
            string arg2 = default;
            if (value != null)
            {
                arg1 = value.@if;
                arg2 = value.@else;
            }
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        arg1 = state.ReadInt32();
                        break;
                    }
                    case 2:
                    {
                        var tmp2 = state.ReadString();
                        if (tmp2 != null) arg2 = tmp2;
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            value = new global::AotFixtures.Keywords.Pair(arg1, arg2);
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Keywords.Pair>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Keywords.Pair value)
            => RawWrite_AotFixtures_Keywords_Pair(ref state, value, state.RawDepthBudget);

        public static void RawWrite_AotFixtures_Keywords_Pair(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Keywords.Pair value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            var tmp1 = value.@if;
            state.WriteRawTag((1 << 3) | 0);  // if
            state.WriteRawVarint64(unchecked((ulong)(long)tmp1));
            var tmp2 = value.@else;
            if (tmp2 != null)
            {
                state.WriteRawTag((2 << 3) | 2);  // else
                state.WriteRawString(tmp2);
            }
        }

        private static long Measure_AotFixtures_Keywords_Pair(global::AotFixtures.Keywords.Pair value, int depth, global::System.Collections.Generic.Dictionary<object, long> lengths)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.@if;
            len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp1));  // if
            var tmp2 = value.@else;
            if (tmp2 != null)
            {
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawString(tmp2);  // else
            }
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Keywords.Pair>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Keywords.Pair value)
            => global::ProtoBuf.ProtoWriter.State.TryMeasureRaw(context, out var depth, out var lengths)
                && Measure_AotFixtures_Keywords_Pair(value, depth, lengths) is var len && len <= int.MaxValue
                ? (int)len : -1;

        // raw read pass: skipped - contract shape (value type, tuple, surrogate or external serializer)
    }
}
