// ---- AotFixtures.Nested.NestedModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable PBN9002

namespace AotFixtures.Nested;

partial class NestedModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected NestedModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static NestedModel Instance { get; } = new NestedModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.Nested.Address value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Nested.Address>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.Nested.Address value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Nested.Address>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.Nested.Customer value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Nested.Customer>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.Nested.Customer value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Nested.Customer>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.Nested.Invoice value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Nested.Invoice>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.Nested.Invoice value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Nested.Invoice>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Nested.Address>
        , global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Nested.Customer>
        , global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Nested.Invoice>
    {
        // DEBUG-only: prove each measured length against the bytes actually written.
        // [Conditional] is resolved against YOUR compilation, so a Release build
        // removes both calls and the capture local with them; the bodies are #if DEBUG'd
        // too, so even calling one directly costs nothing there.
        [global::System.Diagnostics.Conditional("DEBUG")]
        private static void DebugCapturePosition(ref global::ProtoBuf.ProtoWriter.State state, ref long position)
        {
#if DEBUG
            position = state.Position64;
#endif
        }

        [global::System.Diagnostics.Conditional("DEBUG")]
        private static void DebugAssertPosition(ref global::ProtoBuf.ProtoWriter.State state, long expected, string member)
        {
#if DEBUG
            var actual = state.Position64;
            // interpolated only on failure: this runs per length-prefixed member in a Debug build
            if (actual != expected) global::System.Diagnostics.Debug.Fail(
                $"Length drift writing '{member}': measured length and bytes written differ by {actual - expected}.");
#endif
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Nested.Address>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Nested.Address global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Nested.Address>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Nested.Address value)
            => RawRead_AotFixtures_Nested_Address(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Nested.Address>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Nested.Address value)
            => RawWrite_AotFixtures_Nested_Address(ref state, value, state.RawDepthBudget);

        public static void RawWrite_AotFixtures_Nested_Address(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Nested.Address value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.City;
            if (tmp1 != null)
            {
                state.WriteRawTag((1 << 3) | 2);  // City
                state.WriteRawString(tmp1);
            }
        }

        private static long Measure_AotFixtures_Nested_Address(global::AotFixtures.Nested.Address value, int depth, global::ProtoBuf.RawLengthBuffer slots)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.City;
            if (tmp1 != null)
            {
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawString(tmp1);  // City
            }
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Nested.Address>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Nested.Address value)
        {
            if (!global::ProtoBuf.ProtoWriter.State.TryMeasureRawSlots(context, out var depth, out var slots)) return -1;
            var entry = slots.Mark();
            var len = Measure_AotFixtures_Nested_Address(value, depth, slots);
            slots.Enter(value, entry);
            return len <= int.MaxValue ? (int)len : -1;
        }

        private static global::AotFixtures.Nested.Address RawRead_AotFixtures_Nested_Address(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Nested.Address value)
        {
            value ??= new global::AotFixtures.Nested.Address();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 2:  // City, field 1, length-prefixed
                    {
                        var tmp1 = state.ReadRawString();
                        if (tmp1 != null) value.City = tmp1;
                        break;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Nested.Customer>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Nested.Customer global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Nested.Customer>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Nested.Customer value)
            => RawRead_AotFixtures_Nested_Customer(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Nested.Customer>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Nested.Customer value)
        {
            var slots = state.RawSlots;
            if (!slots.Leave(value, out var entry))
            {
                entry = slots.Mark();
                Measure_AotFixtures_Nested_Customer(value, state.RawDepthBudget, slots);
            }
            slots.SeekTo(entry);
            RawWrite_AotFixtures_Nested_Customer(ref state, value, state.RawDepthBudget);
        }

        public static void RawWrite_AotFixtures_Nested_Customer(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Nested.Customer value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            long before = 0;
            var tmp1 = value.Id;
            if (tmp1 != 0)
            {
                state.WriteRawTag((1 << 3) | 0);  // Id
                state.WriteRawVarint64(unchecked((ulong)(long)tmp1));
            }
            var tmp2 = value.Address;
            if (tmp2 != null)
            {
                state.WriteRawTag((2 << 3) | 2);  // Address
                var len = state.RawSlots.Next();
                state.WriteRawVarint64((ulong)len);
                DebugCapturePosition(ref state, ref before);
                RawWrite_AotFixtures_Nested_Address(ref state, tmp2, depth);
                DebugAssertPosition(ref state, before + len, "Address");
            }
        }

        private static long Measure_AotFixtures_Nested_Customer(global::AotFixtures.Nested.Customer value, int depth, global::ProtoBuf.RawLengthBuffer slots)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.Id;
            if (tmp1 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp1));  // Id
            var tmp2 = value.Address;
            if (tmp2 != null)
            {
                var slot2 = slots.Reserve();
                var sub = Measure_AotFixtures_Nested_Address(tmp2, depth, slots);
                slots.Set(slot2, sub);
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64((ulong)sub) + sub;  // Address
            }
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Nested.Customer>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Nested.Customer value)
        {
            if (!global::ProtoBuf.ProtoWriter.State.TryMeasureRawSlots(context, out var depth, out var slots)) return -1;
            var entry = slots.Mark();
            var len = Measure_AotFixtures_Nested_Customer(value, depth, slots);
            slots.Enter(value, entry);
            return len <= int.MaxValue ? (int)len : -1;
        }

        private static global::AotFixtures.Nested.Customer RawRead_AotFixtures_Nested_Customer(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Nested.Customer value)
        {
            value ??= new global::AotFixtures.Nested.Customer();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // Id, field 1, varint
                        value.Id = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (1 << 3) | 5:  // Id, field 1, fixed32
                        value.Id = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (1 << 3) | 1:  // Id, field 1, fixed64
                        value.Id = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (2 << 3) | 2:  // Address, field 2, length-prefixed
                    case (2 << 3) | 3:  // Address, field 2, group
                    {
                        var scope = state.PushScope(tag);
                        value.Address = RawRead_AotFixtures_Nested_Address(ref state, value.Address);
                        state.PopScope(scope);
                        break;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Nested.Invoice>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Nested.Invoice global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Nested.Invoice>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Nested.Invoice value)
            => RawRead_AotFixtures_Nested_Invoice(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Nested.Invoice>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Nested.Invoice value)
        {
            var slots = state.RawSlots;
            if (!slots.Leave(value, out var entry))
            {
                entry = slots.Mark();
                Measure_AotFixtures_Nested_Invoice(value, state.RawDepthBudget, slots);
            }
            slots.SeekTo(entry);
            RawWrite_AotFixtures_Nested_Invoice(ref state, value, state.RawDepthBudget);
        }

        public static void RawWrite_AotFixtures_Nested_Invoice(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Nested.Invoice value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            long len;
            long before = 0;
            var tmp1 = value.Number;
            if (tmp1 != 0)
            {
                state.WriteRawTag((1 << 3) | 0);  // Number
                state.WriteRawVarint64(unchecked((ulong)(long)tmp1));
            }
            var tmp2 = value.Customer;
            if (tmp2 != null)
            {
                state.WriteRawTag((2 << 3) | 2);  // Customer
                len = state.RawSlots.Next();
                state.WriteRawVarint64((ulong)len);
                DebugCapturePosition(ref state, ref before);
                RawWrite_AotFixtures_Nested_Customer(ref state, tmp2, depth);
                DebugAssertPosition(ref state, before + len, "Customer");
            }
            var tmp3 = value.ShipTo;
            if (tmp3 != null)
            {
                state.WriteRawTag((3 << 3) | 2);  // ShipTo
                len = state.RawSlots.Next();
                state.WriteRawVarint64((ulong)len);
                DebugCapturePosition(ref state, ref before);
                RawWrite_AotFixtures_Nested_Address(ref state, tmp3, depth);
                DebugAssertPosition(ref state, before + len, "ShipTo");
            }
        }

        private static long Measure_AotFixtures_Nested_Invoice(global::AotFixtures.Nested.Invoice value, int depth, global::ProtoBuf.RawLengthBuffer slots)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            long sub;
            var tmp1 = value.Number;
            if (tmp1 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp1));  // Number
            var tmp2 = value.Customer;
            if (tmp2 != null)
            {
                var slot2 = slots.Reserve();
                sub = Measure_AotFixtures_Nested_Customer(tmp2, depth, slots);
                slots.Set(slot2, sub);
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64((ulong)sub) + sub;  // Customer
            }
            var tmp3 = value.ShipTo;
            if (tmp3 != null)
            {
                var slot3 = slots.Reserve();
                sub = Measure_AotFixtures_Nested_Address(tmp3, depth, slots);
                slots.Set(slot3, sub);
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64((ulong)sub) + sub;  // ShipTo
            }
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Nested.Invoice>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Nested.Invoice value)
        {
            if (!global::ProtoBuf.ProtoWriter.State.TryMeasureRawSlots(context, out var depth, out var slots)) return -1;
            var entry = slots.Mark();
            var len = Measure_AotFixtures_Nested_Invoice(value, depth, slots);
            slots.Enter(value, entry);
            return len <= int.MaxValue ? (int)len : -1;
        }

        private static global::AotFixtures.Nested.Invoice RawRead_AotFixtures_Nested_Invoice(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Nested.Invoice value)
        {
            value ??= new global::AotFixtures.Nested.Invoice();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // Number, field 1, varint
                        value.Number = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (1 << 3) | 5:  // Number, field 1, fixed32
                        value.Number = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (1 << 3) | 1:  // Number, field 1, fixed64
                        value.Number = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (2 << 3) | 2:  // Customer, field 2, length-prefixed
                    case (2 << 3) | 3:  // Customer, field 2, group
                    {
                        var scope = state.PushScope(tag);
                        value.Customer = RawRead_AotFixtures_Nested_Customer(ref state, value.Customer);
                        state.PopScope(scope);
                        break;
                    }
                    case (3 << 3) | 2:  // ShipTo, field 3, length-prefixed
                    case (3 << 3) | 3:  // ShipTo, field 3, group
                    {
                        var scope = state.PushScope(tag);
                        value.ShipTo = RawRead_AotFixtures_Nested_Address(ref state, value.ShipTo);
                        state.PopScope(scope);
                        break;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2 or 3;
        }
    }
}
