// ---- AotFixtures.Nullables.NullablesModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable PBN9002

namespace AotFixtures.Nullables;

partial class NullablesModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected NullablesModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static NullablesModel Instance { get; } = new NullablesModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.Nullables.Optional value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            return state.SerializeRoot<global::AotFixtures.Nullables.Optional>(value, GetSerializer<global::AotFixtures.Nullables.Optional>());
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.Nullables.Optional value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            return state.SerializeRoot<global::AotFixtures.Nullables.Optional>(value, GetSerializer<global::AotFixtures.Nullables.Optional>());
        }
        finally
        {
            state.Dispose();
        }
    }

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Nullables.Optional>
    {
        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Nullables.Optional>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Nullables.Optional global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Nullables.Optional>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Nullables.Optional value)
            => RawRead_AotFixtures_Nullables_Optional(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Nullables.Optional>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Nullables.Optional value)
            => RawWrite_AotFixtures_Nullables_Optional(ref state, value, state.RawDepthBudget);

        public static void RawWrite_AotFixtures_Nullables_Optional(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Nullables.Optional value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.MaybeInt;
            if (tmp1.HasValue)
            {
                var val1 = tmp1.GetValueOrDefault();
                state.WriteRawTag((1 << 3) | 0);  // MaybeInt
                state.WriteRawVarint64(unchecked((ulong)(long)val1));
            }
            var tmp2 = value.MaybeBool;
            if (tmp2.HasValue)
            {
                var val2 = tmp2.GetValueOrDefault();
                state.WriteRawTagBool((2 << 3) | 0, val2);  // MaybeBool
            }
            var tmp3 = value.MaybeDouble;
            if (tmp3.HasValue)
            {
                var val3 = tmp3.GetValueOrDefault();
                state.WriteRawTag((3 << 3) | 1);  // MaybeDouble
                state.WriteRawDouble(val3);
            }
            var tmp4 = value.MaybeLong;
            if (tmp4.HasValue)
            {
                var val4 = tmp4.GetValueOrDefault();
                state.WriteRawTag((4 << 3) | 0);  // MaybeLong
                state.WriteRawVarint64(unchecked((ulong)val4));
            }
            var tmp5 = value.IntWithDefault;
            if (tmp5.HasValue)
            {
                var val5 = tmp5.GetValueOrDefault();
                if (val5 != 5)
                {
                    state.WriteRawTag((5 << 3) | 0);  // IntWithDefault
                    state.WriteRawVarint64(unchecked((ulong)(long)val5));
                }
            }
            var tmp6 = value.IntWithNullDefault;
            if (tmp6.HasValue)
            {
                var val6 = tmp6.GetValueOrDefault();
                state.WriteRawTag((6 << 3) | 0);  // IntWithNullDefault
                state.WriteRawVarint64(unchecked((ulong)(long)val6));
            }
            var tmp7 = value.Plain;
            if (tmp7 != 0)
            {
                state.WriteRawTag((7 << 3) | 0);  // Plain
                state.WriteRawVarint64(unchecked((ulong)(long)tmp7));
            }
        }

        private static long Measure_AotFixtures_Nullables_Optional(global::AotFixtures.Nullables.Optional value, int depth, global::ProtoBuf.RawLengthBuffer slots)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.MaybeInt;
            if (tmp1.HasValue)
            {
                var val1 = tmp1.GetValueOrDefault();
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)val1));  // MaybeInt
            }
            var tmp2 = value.MaybeBool;
            if (tmp2.HasValue)
            {
                var val2 = tmp2.GetValueOrDefault();
                len += 2;  // MaybeBool
            }
            var tmp3 = value.MaybeDouble;
            if (tmp3.HasValue)
            {
                var val3 = tmp3.GetValueOrDefault();
                len += 9;  // MaybeDouble
            }
            var tmp4 = value.MaybeLong;
            if (tmp4.HasValue)
            {
                var val4 = tmp4.GetValueOrDefault();
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)val4));  // MaybeLong
            }
            var tmp5 = value.IntWithDefault;
            if (tmp5.HasValue)
            {
                var val5 = tmp5.GetValueOrDefault();
                if (val5 != 5)
                {
                    len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)val5));  // IntWithDefault
                }
            }
            var tmp6 = value.IntWithNullDefault;
            if (tmp6.HasValue)
            {
                var val6 = tmp6.GetValueOrDefault();
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)val6));  // IntWithNullDefault
            }
            var tmp7 = value.Plain;
            if (tmp7 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp7));  // Plain
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Nullables.Optional>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Nullables.Optional value)
        {
            if (!global::ProtoBuf.ProtoWriter.State.TryMeasureRawSlots(context, out var depth, out var slots)) return -1;
            var entry = slots.Mark();
            var len = Measure_AotFixtures_Nullables_Optional(value, depth, slots);
            slots.Enter(value, entry);
            return len <= int.MaxValue ? (int)len : -1;
        }

        private static global::AotFixtures.Nullables.Optional RawRead_AotFixtures_Nullables_Optional(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Nullables.Optional value)
        {
            value ??= new global::AotFixtures.Nullables.Optional();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // MaybeInt, field 1, varint
                        value.MaybeInt = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (1 << 3) | 5:  // MaybeInt, field 1, fixed32
                        value.MaybeInt = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (1 << 3) | 1:  // MaybeInt, field 1, fixed64
                        value.MaybeInt = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (2 << 3) | 0:  // MaybeBool, field 2, varint
                        value.MaybeBool = state.ReadRawVarint32() != 0;
                        break;
                    case (2 << 3) | 5:  // MaybeBool, field 2, fixed32
                        value.MaybeBool = state.ReadRawFixed32() != 0;
                        break;
                    case (2 << 3) | 1:  // MaybeBool, field 2, fixed64
                        value.MaybeBool = state.ReadRawFixed64() != 0;
                        break;
                    case (3 << 3) | 1:  // MaybeDouble, field 3, fixed64
                        value.MaybeDouble = state.ReadRawDouble();
                        break;
                    case (4 << 3) | 0:  // MaybeLong, field 4, varint
                        value.MaybeLong = unchecked((long)state.ReadRawVarint64());
                        break;
                    case (4 << 3) | 1:  // MaybeLong, field 4, fixed64
                        value.MaybeLong = unchecked((long)state.ReadRawFixed64());
                        break;
                    case (4 << 3) | 5:  // MaybeLong, field 4, fixed32
                        value.MaybeLong = (long)unchecked((int)state.ReadRawFixed32());
                        break;
                    case (5 << 3) | 0:  // IntWithDefault, field 5, varint
                        value.IntWithDefault = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (5 << 3) | 5:  // IntWithDefault, field 5, fixed32
                        value.IntWithDefault = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (5 << 3) | 1:  // IntWithDefault, field 5, fixed64
                        value.IntWithDefault = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (6 << 3) | 0:  // IntWithNullDefault, field 6, varint
                        value.IntWithNullDefault = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (6 << 3) | 5:  // IntWithNullDefault, field 6, fixed32
                        value.IntWithNullDefault = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (6 << 3) | 1:  // IntWithNullDefault, field 6, fixed64
                        value.IntWithNullDefault = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (7 << 3) | 0:  // Plain, field 7, varint
                        value.Plain = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (7 << 3) | 5:  // Plain, field 7, fixed32
                        value.Plain = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (7 << 3) | 1:  // Plain, field 7, fixed64
                        value.Plain = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2 or 3 or 4 or 5 or 6 or 7;
        }
    }
}
