// ---- AotFixtures.Parseable.ParseableModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable PBN9002

namespace AotFixtures.Parseable;

partial class ParseableModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected ParseableModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static ParseableModel Instance { get; } = new ParseableModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.Parseable.Endpoint value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Parseable.Endpoint>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.Parseable.Endpoint value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Parseable.Endpoint>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.Parseable.Holder value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Parseable.Holder>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.Parseable.Holder value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Parseable.Holder>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.Parseable.NotParseable value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Parseable.NotParseable>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.Parseable.NotParseable value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Parseable.NotParseable>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Parseable.Endpoint>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Parseable.Holder>
        , global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Parseable.NotParseable>
    {
        private static readonly ProtoBufGeneratedServices Self = new();

        private static readonly ProtoBufGeneratedServices s_default = new ProtoBufGeneratedServices();

        // DEBUG-only: prove each measured length against the bytes actually written.
        // [Conditional] is resolved against YOUR compilation, so a Release build
        // removes both calls and the capture local with them; the bodies are #if DEBUG'd
        // too, so even calling one directly costs nothing there.
        [global::System.Diagnostics.Conditional("DEBUG")]
        private static void DebugCapturePosition(ref global::ProtoBuf.ProtoWriter.State state, ref long position)
        {
#if DEBUG
            position = state.Position64;
#endif
        }

        [global::System.Diagnostics.Conditional("DEBUG")]
        private static void DebugAssertPosition(ref global::ProtoBuf.ProtoWriter.State state, long expected, string member)
        {
#if DEBUG
            var actual = state.Position64;
            // interpolated only on failure: this runs per length-prefixed member in a Debug build
            if (actual != expected) global::System.Diagnostics.Debug.Fail(
                $"Length drift writing '{member}': measured length and bytes written differ by {actual - expected}.");
#endif
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Parseable.Endpoint>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Parseable.Endpoint global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Parseable.Endpoint>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Parseable.Endpoint value)
            => RawRead_AotFixtures_Parseable_Endpoint(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Parseable.Endpoint>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Parseable.Endpoint value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Address;
            if (tmp1 != null)
            {
                state.WriteFieldHeader(1, global::ProtoBuf.WireType.String);
                state.WriteString(tmp1.ToString());
            }
            var tmp2 = value.Name;
            if (tmp2 != null)
            {
                state.WriteRawTag((2 << 3) | 2);  // Name
                state.WriteRawString(tmp2);
            }
            var tmp3 = value.Ip;
            if (tmp3 != null)
            {
                state.WriteFieldHeader(3, global::ProtoBuf.WireType.String);
                state.WriteString(tmp3.ToString());
            }
        }

        private static global::AotFixtures.Parseable.Endpoint RawRead_AotFixtures_Parseable_Endpoint(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Parseable.Endpoint value)
        {
            value ??= new global::AotFixtures.Parseable.Endpoint();
            uint tag = state.ReadRawTagOrPending();
            while (tag != 0)
            {
                switch (tag)
                {
                    // raw read pass: legacy-mode - member Address: kind Parseable
                    case (1 << 3) | 0:
                    case (1 << 3) | 1:
                    case (1 << 3) | 2:  // Address, field 1
                    case (1 << 3) | 3:
                    case (1 << 3) | 5:
                    {
                        state.StashTag(tag);
                        value.Address = global::AotFixtures.Parseable.Moniker.Parse(state.ReadString());
                        break;
                    }
                    case (2 << 3) | 2:  // Name, field 2, length-prefixed
                    {
                        var tmp2 = state.ReadRawString();
                        if (tmp2 != null) value.Name = tmp2;
                        break;
                    }
                    // raw read pass: legacy-mode - member Ip: kind Parseable
                    case (3 << 3) | 0:
                    case (3 << 3) | 1:
                    case (3 << 3) | 2:  // Ip, field 3
                    case (3 << 3) | 3:
                    case (3 << 3) | 5:
                    {
                        state.StashTag(tag);
                        value.Ip = global::System.Net.IPAddress.Parse(state.ReadString());
                        break;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTagOrPending();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2 or 3;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Parseable.Holder>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Parseable.Holder global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Parseable.Holder>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Parseable.Holder value)
            => RawRead_AotFixtures_Parseable_Holder(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Parseable.Holder>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Parseable.Holder value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            long before = 0;
            var tmp1 = value.Ratio;
            state.WriteFieldHeader(1, global::ProtoBuf.WireType.String);
            state.WriteString(tmp1.ToString());
            var tmp2 = value.Child;
            if (tmp2 != null)
            {
                state.WriteRawTag((2 << 3) | 2);  // Child
                var mark2 = state.RawSlots.Mark();
                var len = Measure_AotFixtures_Parseable_NotParseable(tmp2, state.RawDepthBudget, state.RawSlots, state.Context);
                state.RawSlots.SeekTo(mark2);
                state.WriteRawVarint64((ulong)len);
                DebugCapturePosition(ref state, ref before);
                RawWrite_AotFixtures_Parseable_NotParseable(ref state, tmp2, state.RawDepthBudget);
                DebugAssertPosition(ref state, before + len, "Child");
            }
        }

        private static global::AotFixtures.Parseable.Holder RawRead_AotFixtures_Parseable_Holder(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Parseable.Holder value)
        {
            value ??= new global::AotFixtures.Parseable.Holder();
            uint tag = state.ReadRawTagOrPending();
            while (tag != 0)
            {
                switch (tag)
                {
                    // raw read pass: legacy-mode - member Ratio: kind Parseable
                    case (1 << 3) | 0:
                    case (1 << 3) | 1:
                    case (1 << 3) | 2:  // Ratio, field 1
                    case (1 << 3) | 3:
                    case (1 << 3) | 5:
                    {
                        state.StashTag(tag);
                        value.Ratio = global::AotFixtures.Parseable.Fraction.Parse(state.ReadString());
                        break;
                    }
                    case (2 << 3) | 2:  // Child, field 2, length-prefixed
                    case (2 << 3) | 3:  // Child, field 2, group
                    {
                        var scope = state.PushScope(tag);
                        value.Child = RawRead_AotFixtures_Parseable_NotParseable(ref state, value.Child);
                        state.PopScope(scope);
                        break;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTagOrPending();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Parseable.NotParseable>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Parseable.NotParseable global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Parseable.NotParseable>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Parseable.NotParseable value)
            => RawRead_AotFixtures_Parseable_NotParseable(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Parseable.NotParseable>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Parseable.NotParseable value)
            => RawWrite_AotFixtures_Parseable_NotParseable(ref state, value, state.RawDepthBudget);

        public static void RawWrite_AotFixtures_Parseable_NotParseable(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Parseable.NotParseable value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Value;
            if (tmp1 != 0)
            {
                state.WriteRawTag((1 << 3) | 0);  // Value
                state.WriteRawVarint64(unchecked((ulong)(long)tmp1));
            }
        }

        private static long Measure_AotFixtures_Parseable_NotParseable(global::AotFixtures.Parseable.NotParseable value, int depth, global::ProtoBuf.RawLengthBuffer slots, global::ProtoBuf.ISerializationContext context)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.Value;
            if (tmp1 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp1));  // Value
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Parseable.NotParseable>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Parseable.NotParseable value)
        {
            if (!global::ProtoBuf.ProtoWriter.State.TryMeasureRawSlots(context, out var depth, out var slots)) return -1;
            var entry = slots.Mark();
            var len = Measure_AotFixtures_Parseable_NotParseable(value, depth, slots, context);
            slots.Enter(value, entry);
            return len <= int.MaxValue ? (int)len : -1;
        }

        private static global::AotFixtures.Parseable.NotParseable RawRead_AotFixtures_Parseable_NotParseable(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Parseable.NotParseable value)
        {
            value ??= new global::AotFixtures.Parseable.NotParseable();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // Value, field 1, varint
                        value.Value = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (1 << 3) | 5:  // Value, field 1, fixed32
                        value.Value = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (1 << 3) | 1:  // Value, field 1, fixed64
                        value.Value = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1;
        }
    }
}
