// ---- AotFixtures.Partial.PartialModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable PBN9002

namespace AotFixtures.Partial;

partial class PartialModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected PartialModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static PartialModel Instance { get; } = new PartialModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Contested>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Described>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Excluded>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Mixed>
    {
        private static readonly ProtoBufGeneratedServices s_default = new ProtoBufGeneratedServices();

        private static T[] ArrayAppend<T>(T[] value, global::System.Collections.Generic.List<T> extra)
        {
            if (value is null || value.Length == 0) return extra.ToArray();
            var result = new T[value.Length + extra.Count];
            value.CopyTo(result, 0);
            extra.CopyTo(result, value.Length);
            return result;
        }

        private static T[] ArrayAppend<T>(T[] value, T extra)
        {
            var offset = value?.Length ?? 0;
            var result = new T[offset + 1];
            value?.CopyTo(result, 0);
            result[offset] = extra;
            return result;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Contested>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Partial.Contested global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Contested>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Partial.Contested value)
            => RawRead_AotFixtures_Partial_Contested(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Contested>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Partial.Contested value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Pinned;
            if (tmp1 != 0) state.WriteInt32Varint(1, tmp1);
            var tmp2 = value.FromPartial;
            if (tmp2 != 0) state.WriteInt32Varint(2, tmp2);
        }

        private static global::AotFixtures.Partial.Contested RawRead_AotFixtures_Partial_Contested(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Partial.Contested value)
        {
            value ??= new global::AotFixtures.Partial.Contested();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // Pinned, field 1, varint
                        value.Pinned = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (1 << 3) | 5:  // Pinned, field 1, fixed32
                        value.Pinned = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (1 << 3) | 1:  // Pinned, field 1, fixed64
                        value.Pinned = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (2 << 3) | 0:  // FromPartial, field 2, varint
                        value.FromPartial = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (2 << 3) | 5:  // FromPartial, field 2, fixed32
                        value.FromPartial = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (2 << 3) | 1:  // FromPartial, field 2, fixed64
                        value.FromPartial = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Described>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Partial.Described global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Described>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Partial.Described value)
            => RawRead_AotFixtures_Partial_Described(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Described>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Partial.Described value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Id;
            if (tmp1 != 0) state.WriteInt32Varint(1, tmp1);
            var tmp2 = value.Name;
            state.WriteString(2, tmp2);
            var tmp3 = value.Fixed;
            if (tmp3 != 0)
            {
                state.WriteFieldHeader(3, global::ProtoBuf.WireType.Fixed32);
                state.WriteInt32(tmp3);
            }
            var tmp4 = value.Always;
            state.WriteInt32Varint(4, tmp4);
            var tmp5 = value.Values;
            if (tmp5 != null)
            {
                global::ProtoBuf.Serializers.RepeatedSerializer.CreateVector<int>().WriteRepeated(ref state, 5, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint, tmp5);
            }
            var tmp6 = value.Replaced;
            if (tmp6 != null)
            {
                global::ProtoBuf.Serializers.RepeatedSerializer.CreateVector<int>().WriteRepeated(ref state, 6, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled | global::ProtoBuf.Serializers.SerializerFeatures.OptionClearCollection, tmp6);
            }
        }

        private static global::AotFixtures.Partial.Described RawRead_AotFixtures_Partial_Described(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Partial.Described value)
        {
            value ??= new global::AotFixtures.Partial.Described();
            uint tag = state.ReadRawTagOrPending();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // Id, field 1, varint
                        value.Id = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (1 << 3) | 5:  // Id, field 1, fixed32
                        value.Id = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (1 << 3) | 1:  // Id, field 1, fixed64
                        value.Id = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (2 << 3) | 2:  // Name, field 2, length-prefixed
                    {
                        var tmp2 = state.ReadRawString();
                        if (tmp2 != null) value.Name = tmp2;
                        break;
                    }
                    case (3 << 3) | 5:  // Fixed, field 3, fixed32
                        value.Fixed = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (3 << 3) | 0:  // Fixed, field 3, varint
                        value.Fixed = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (3 << 3) | 1:  // Fixed, field 3, fixed64
                        value.Fixed = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (4 << 3) | 0:  // Always, field 4, varint
                        value.Always = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (4 << 3) | 5:  // Always, field 4, fixed32
                        value.Always = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (4 << 3) | 1:  // Always, field 4, fixed64
                        value.Always = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (5 << 3) | 0:  // Values, field 5, unpacked run (varint)
                    {
                        var buf5 = new global::System.Collections.Generic.List<int>();
                        do { buf5.Add(unchecked((int)state.ReadRawVarint32())); }
                        while ((tag = state.ReadRawTag()) == ((5 << 3) | 0));
                        value.Values = ArrayAppend(value.Values, buf5);
                        continue;
                    }
                    case (5 << 3) | 2:  // Values, field 5, packed
                    {
                        var buf5p = new global::System.Collections.Generic.List<int>();
                        var scope = state.PushLengthPrefix();
                        while (!state.AtScopeEnd) buf5p.Add(unchecked((int)state.ReadRawVarint32()));
                        state.PopScope(scope);
                        value.Values = ArrayAppend(value.Values, buf5p);
                        break;
                    }
                    case (5 << 3) | 5:  // Values, field 5, fixed32
                        value.Values = ArrayAppend(value.Values, unchecked((int)state.ReadRawFixed32()));
                        break;
                    case (5 << 3) | 1:  // Values, field 5, fixed64
                        value.Values = ArrayAppend(value.Values, checked((int)unchecked((long)state.ReadRawFixed64())));
                        break;
                    // raw read pass: legacy-mode - member Replaced: OverwriteList collection
                    case (6 << 3) | 0:
                    case (6 << 3) | 1:
                    case (6 << 3) | 2:  // Replaced, field 6
                    case (6 << 3) | 3:
                    case (6 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp6 = value.Replaced;
                        tmp6 = global::ProtoBuf.Serializers.RepeatedSerializer.CreateVector<int>().ReadRepeated(ref state, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled | global::ProtoBuf.Serializers.SerializerFeatures.OptionClearCollection, tmp6);
                        if (tmp6 != null) value.Replaced = tmp6;
                        break;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTagOrPending();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2 or 3 or 4 or 5 or 6;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Excluded>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Partial.Excluded global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Excluded>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Partial.Excluded value)
            => RawRead_AotFixtures_Partial_Excluded(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Excluded>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Partial.Excluded value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Kept;
            if (tmp1 != 0) state.WriteInt32Varint(1, tmp1);
        }

        private static global::AotFixtures.Partial.Excluded RawRead_AotFixtures_Partial_Excluded(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Partial.Excluded value)
        {
            value ??= new global::AotFixtures.Partial.Excluded();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 0:  // Kept, field 1, varint
                        value.Kept = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (1 << 3) | 5:  // Kept, field 1, fixed32
                        value.Kept = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (1 << 3) | 1:  // Kept, field 1, fixed64
                        value.Kept = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Mixed>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Partial.Mixed global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Mixed>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Partial.Mixed value)
            => RawRead_AotFixtures_Partial_Mixed(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Partial.Mixed>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Partial.Mixed value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp2 = value.OrderOnly;
            if (tmp2 != 0) state.WriteInt32Varint(2, tmp2);
            var tmp7 = value.Both;
            if (tmp7 != 0) state.WriteInt32Varint(7, tmp7);
        }

        private static global::AotFixtures.Partial.Mixed RawRead_AotFixtures_Partial_Mixed(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Partial.Mixed value)
        {
            value ??= new global::AotFixtures.Partial.Mixed();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (2 << 3) | 0:  // OrderOnly, field 2, varint
                        value.OrderOnly = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (2 << 3) | 5:  // OrderOnly, field 2, fixed32
                        value.OrderOnly = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (2 << 3) | 1:  // OrderOnly, field 2, fixed64
                        value.OrderOnly = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    case (7 << 3) | 0:  // Both, field 7, varint
                        value.Both = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (7 << 3) | 5:  // Both, field 7, fixed32
                        value.Both = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (7 << 3) | 1:  // Both, field 7, fixed64
                        value.Both = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 2 or 7;
        }
    }
}
