// ---- AotFixtures.Structs.StructsModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591

namespace AotFixtures.Structs;

partial class StructsModel
{
    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.HasStructs>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.Point>
    {
        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.HasStructs>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Structs.HasStructs global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.HasStructs>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Structs.HasStructs value)
        {
            value ??= new global::AotFixtures.Structs.HasStructs();
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        var tmp1 = value.Location;
                        value.Location = state.ReadMessage<global::AotFixtures.Structs.Point>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp1, this);
                        break;
                    }
                    case 2:
                    {
                        var tmp2 = value.MaybeLocation.GetValueOrDefault();
                        value.MaybeLocation = state.ReadMessage<global::AotFixtures.Structs.Point>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp2, this);
                        break;
                    }
                    case 3:
                    {
                        value.Other = state.ReadInt32();
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.HasStructs>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Structs.HasStructs value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Location;
            state.WriteMessage<global::AotFixtures.Structs.Point>(1, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp1, this);
            var tmp2 = value.MaybeLocation;
            if (tmp2.HasValue)
            {
                state.WriteMessage<global::AotFixtures.Structs.Point>(2, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp2.GetValueOrDefault(), this);
            }
            var tmp3 = value.Other;
            if (tmp3 != 0) state.WriteInt32Varint(3, tmp3);
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.Point>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.Structs.Point global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.Point>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Structs.Point value)
        {
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        value.X = state.ReadInt32();
                        break;
                    }
                    case 2:
                    {
                        var tmp2 = state.ReadString();
                        if (tmp2 != null) value.Label = tmp2;
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.Point>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Structs.Point value)
        {
            var tmp1 = value.X;
            if (tmp1 != 0) state.WriteInt32Varint(1, tmp1);
            var tmp2 = value.Label;
            state.WriteString(2, tmp2);
        }
    }
}

// ---- ProtoModelAttributes.g.cs ----
// <auto-generated/>
#nullable enable
namespace ProtoBuf
{
    /// <summary>
    /// Marks a partial <see cref="global::ProtoBuf.Meta.TypeModel"/> subclass as a compile-time
    /// serialization model, to be populated by the protobuf-net generator.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class ProtoModelAttribute : global::System.Attribute
    {
    }

    /// <summary>
    /// Declares a root type that the associated model can serialize; every contract reachable
    /// from a root is included in the model automatically.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    internal sealed class ProtoSerializableAttribute : global::System.Attribute
    {
        /// <summary>
        /// Create a new instance.
        /// </summary>
        public ProtoSerializableAttribute(global::System.Type type) => Type = type;

        /// <summary>
        /// The root type to include in the model.
        /// </summary>
        public global::System.Type Type { get; }
    }
}
