// ---- AotFixtures.Structs.StructsModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable PBN9002

namespace AotFixtures.Structs;

partial class StructsModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected StructsModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static StructsModel Instance { get; } = new StructsModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.Structs.HasStructs value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Structs.HasStructs>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.Structs.HasStructs value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Structs.HasStructs>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.Structs.Point value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Structs.Point>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.Structs.Point value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            long before = state.Position64;
            GetSerializer<global::AotFixtures.Structs.Point>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Structs.HasStructs>
        , global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Structs.Point>
    {
        private static readonly ProtoBufGeneratedServices Self = new();

        private static readonly ProtoBufGeneratedServices s_default = new ProtoBufGeneratedServices();

        // DEBUG-only: prove each measured length against the bytes actually written.
        // [Conditional] is resolved against YOUR compilation, so a Release build
        // removes both calls and the capture local with them; the bodies are #if DEBUG'd
        // too, so even calling one directly costs nothing there.
        [global::System.Diagnostics.Conditional("DEBUG")]
        private static void DebugCapturePosition(ref global::ProtoBuf.ProtoWriter.State state, ref long position)
        {
#if DEBUG
            position = state.Position64;
#endif
        }

        [global::System.Diagnostics.Conditional("DEBUG")]
        private static void DebugAssertPosition(ref global::ProtoBuf.ProtoWriter.State state, long expected, string member)
        {
#if DEBUG
            var actual = state.Position64;
            // interpolated only on failure: this runs per length-prefixed member in a Debug build
            if (actual != expected) global::System.Diagnostics.Debug.Fail(
                $"Length drift writing '{member}': measured length and bytes written differ by {actual - expected}.");
#endif
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.HasStructs>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Structs.HasStructs global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.HasStructs>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Structs.HasStructs value)
            => RawRead_AotFixtures_Structs_HasStructs(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.HasStructs>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Structs.HasStructs value)
        {
            var slots = state.RawSlots;
            if (!slots.Leave(value, out var entry))
            {
                entry = slots.Mark();
                Measure_AotFixtures_Structs_HasStructs(value, state.RawDepthBudget, slots);
            }
            slots.SeekTo(entry);
            RawWrite_AotFixtures_Structs_HasStructs(ref state, value, state.RawDepthBudget);
        }

        public static void RawWrite_AotFixtures_Structs_HasStructs(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Structs.HasStructs value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            long before = 0;
            var tmp1 = value.Location;
            state.WriteRawTag((1 << 3) | 2);  // Location
            var len = state.RawSlots.Next();
            state.WriteRawVarint64((ulong)len);
            DebugCapturePosition(ref state, ref before);
            RawWrite_AotFixtures_Structs_Point(ref state, tmp1, depth);
            DebugAssertPosition(ref state, before + len, "Location");
            var tmp2 = value.MaybeLocation;
            if (tmp2.HasValue)
            {
                state.WriteMessage<global::AotFixtures.Structs.Point>(2, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp2.GetValueOrDefault(), Self);
            }
            var tmp3 = value.Other;
            if (tmp3 != 0)
            {
                state.WriteRawTag((3 << 3) | 0);  // Other
                state.WriteRawVarint64(unchecked((ulong)(long)tmp3));
            }
        }

        private static long Measure_AotFixtures_Structs_HasStructs(global::AotFixtures.Structs.HasStructs value, int depth, global::ProtoBuf.RawLengthBuffer slots)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            long sub;
            var tmp1 = value.Location;
            var slot1 = slots.Reserve();
            sub = Measure_AotFixtures_Structs_Point(tmp1, depth, slots);
            slots.Set(slot1, sub);
            len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64((ulong)sub) + sub;  // Location
            var tmp2 = value.MaybeLocation;
            if (tmp2.HasValue)
            {
                var val2 = tmp2.GetValueOrDefault();
                sub = Measure_AotFixtures_Structs_Point(val2, depth, null);
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64((ulong)sub) + sub;  // MaybeLocation
            }
            var tmp3 = value.Other;
            if (tmp3 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp3));  // Other
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Structs.HasStructs>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Structs.HasStructs value)
        {
            if (!global::ProtoBuf.ProtoWriter.State.TryMeasureRawSlots(context, out var depth, out var slots)) return -1;
            var entry = slots.Mark();
            var len = Measure_AotFixtures_Structs_HasStructs(value, depth, slots);
            slots.Enter(value, entry);
            return len <= int.MaxValue ? (int)len : -1;
        }

        private static global::AotFixtures.Structs.HasStructs RawRead_AotFixtures_Structs_HasStructs(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Structs.HasStructs value)
        {
            value ??= new global::AotFixtures.Structs.HasStructs();
            uint tag = state.ReadRawTagOrPending();
            while (tag != 0)
            {
                switch (tag)
                {
                    // raw read pass: legacy-mode - member Location: message shape (nullable or struct)
                    case (1 << 3) | 0:
                    case (1 << 3) | 1:
                    case (1 << 3) | 2:  // Location, field 1
                    case (1 << 3) | 3:
                    case (1 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp1 = value.Location;
                        value.Location = state.ReadMessage<global::AotFixtures.Structs.Point>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp1, s_default);
                        break;
                    }
                    // raw read pass: legacy-mode - member MaybeLocation: message shape (nullable or struct)
                    case (2 << 3) | 0:
                    case (2 << 3) | 1:
                    case (2 << 3) | 2:  // MaybeLocation, field 2
                    case (2 << 3) | 3:
                    case (2 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp2 = value.MaybeLocation.GetValueOrDefault();
                        value.MaybeLocation = state.ReadMessage<global::AotFixtures.Structs.Point>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp2, s_default);
                        break;
                    }
                    case (3 << 3) | 0:  // Other, field 3, varint
                        value.Other = unchecked((int)state.ReadRawVarint32());
                        break;
                    case (3 << 3) | 5:  // Other, field 3, fixed32
                        value.Other = unchecked((int)state.ReadRawFixed32());
                        break;
                    case (3 << 3) | 1:  // Other, field 3, fixed64
                        value.Other = checked((int)unchecked((long)state.ReadRawFixed64()));
                        break;
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTagOrPending();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1 or 2 or 3;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.Point>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionTrySkipWritingWhenMeasuring;

        global::AotFixtures.Structs.Point global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.Point>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.Structs.Point value)
        {
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        value.X = state.ReadInt32();
                        break;
                    }
                    case 2:
                    {
                        var tmp2 = state.ReadString();
                        if (tmp2 != null) value.Label = tmp2;
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.Structs.Point>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Structs.Point value)
            => RawWrite_AotFixtures_Structs_Point(ref state, value, state.RawDepthBudget);

        public static void RawWrite_AotFixtures_Structs_Point(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.Structs.Point value, int depth)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            var tmp1 = value.X;
            if (tmp1 != 0)
            {
                state.WriteRawTag((1 << 3) | 0);  // X
                state.WriteRawVarint64(unchecked((ulong)(long)tmp1));
            }
            var tmp2 = value.Label;
            if (tmp2 != null)
            {
                state.WriteRawTag((2 << 3) | 2);  // Label
                state.WriteRawString(tmp2);
            }
        }

        private static long Measure_AotFixtures_Structs_Point(global::AotFixtures.Structs.Point value, int depth, global::ProtoBuf.RawLengthBuffer slots)
        {
            if (--depth < 0) global::ProtoBuf.ProtoWriter.State.ThrowRawTooDeep();
            long len = 0;
            var tmp1 = value.X;
            if (tmp1 != 0) len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawVarint64(unchecked((ulong)(long)tmp1));  // X
            var tmp2 = value.Label;
            if (tmp2 != null)
            {
                len += 1 + global::ProtoBuf.ProtoWriter.State.MeasureRawString(tmp2);  // Label
            }
            return len;
        }

        int global::ProtoBuf.Serializers.IMeasuringSerializer<global::AotFixtures.Structs.Point>.Measure(global::ProtoBuf.ISerializationContext context, global::ProtoBuf.WireType wireType, global::AotFixtures.Structs.Point value)
        {
            if (!global::ProtoBuf.ProtoWriter.State.TryMeasureRawSlots(context, out var depth, out var slots)) return -1;
            var entry = slots.Mark();
            var len = Measure_AotFixtures_Structs_Point(value, depth, slots);
            return len <= int.MaxValue ? (int)len : -1;
        }

        // raw read pass: skipped - contract shape (value type, tuple, surrogate or external serializer)
    }
}
