// ---- AotFixtures.TupleMembers.TupleMembersModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591

namespace AotFixtures.TupleMembers;

partial class TupleMembersModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected TupleMembersModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static TupleMembersModel Instance { get; } = new TupleMembersModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.ISerializer<(int, (int, string))>
        , global::ProtoBuf.Serializers.ISerializer<(int, string)>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.TupleMembers.HasTuples>
        , global::ProtoBuf.Serializers.ISerializer<global::System.Collections.Generic.KeyValuePair<int, string>>
    {
        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<(int, (int, string))>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        (int, (int, string)) global::ProtoBuf.Serializers.ISerializer<(int, (int, string))>.Read(ref global::ProtoBuf.ProtoReader.State state, (int, (int, string)) value)
        {
            int arg1 = default;
            (int, string) arg2 = default;
            arg1 = value.Item1;
            arg2 = value.Item2;
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        arg1 = state.ReadInt32();
                        break;
                    }
                    case 2:
                    {
                        var tmp2 = arg2;
                        arg2 = state.ReadMessage<(int, string)>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp2, this);
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            value = (arg1, arg2);
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<(int, (int, string))>.Write(ref global::ProtoBuf.ProtoWriter.State state, (int, (int, string)) value)
        {
            var tmp1 = value.Item1;
            state.WriteInt32Varint(1, tmp1);
            var tmp2 = value.Item2;
            state.WriteMessage<(int, string)>(2, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp2, this);
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<(int, string)>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        (int, string) global::ProtoBuf.Serializers.ISerializer<(int, string)>.Read(ref global::ProtoBuf.ProtoReader.State state, (int, string) value)
        {
            int arg1 = default;
            string arg2 = default;
            arg1 = value.Item1;
            arg2 = value.Item2;
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        arg1 = state.ReadInt32();
                        break;
                    }
                    case 2:
                    {
                        var tmp2 = state.ReadString();
                        if (tmp2 != null) arg2 = tmp2;
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            value = (arg1, arg2);
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<(int, string)>.Write(ref global::ProtoBuf.ProtoWriter.State state, (int, string) value)
        {
            var tmp1 = value.Item1;
            state.WriteInt32Varint(1, tmp1);
            var tmp2 = value.Item2;
            state.WriteString(2, tmp2);
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.TupleMembers.HasTuples>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.TupleMembers.HasTuples global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.TupleMembers.HasTuples>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.TupleMembers.HasTuples value)
        {
            value ??= new global::AotFixtures.TupleMembers.HasTuples();
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        var tmp1 = value.Named;
                        value.Named = state.ReadMessage<(int, string)>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp1, this);
                        break;
                    }
                    case 2:
                    {
                        var tmp2 = value.Anonymous;
                        value.Anonymous = state.ReadMessage<(int, string)>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp2, this);
                        break;
                    }
                    case 3:
                    {
                        var tmp3 = value.Deep;
                        value.Deep = state.ReadMessage<(int, (int, string))>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp3, this);
                        break;
                    }
                    case 4:
                    {
                        var tmp4 = value.Pair;
                        value.Pair = state.ReadMessage<global::System.Collections.Generic.KeyValuePair<int, string>>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp4, this);
                        break;
                    }
                    case 5:
                    {
                        var tmp5 = value.MaybePair.GetValueOrDefault();
                        value.MaybePair = state.ReadMessage<(int, string)>(global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp5, this);
                        break;
                    }
                    case 6:
                    {
                        value.Other = state.ReadInt32();
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.TupleMembers.HasTuples>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.TupleMembers.HasTuples value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Named;
            state.WriteMessage<(int, string)>(1, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp1, this);
            var tmp2 = value.Anonymous;
            state.WriteMessage<(int, string)>(2, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp2, this);
            var tmp3 = value.Deep;
            state.WriteMessage<(int, (int, string))>(3, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp3, this);
            var tmp4 = value.Pair;
            state.WriteMessage<global::System.Collections.Generic.KeyValuePair<int, string>>(4, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp4, this);
            var tmp5 = value.MaybePair;
            if (tmp5.HasValue)
            {
                state.WriteMessage<(int, string)>(5, global::ProtoBuf.Serializers.SerializerFeatures.CategoryRepeated, tmp5.GetValueOrDefault(), this);
            }
            var tmp6 = value.Other;
            if (tmp6 != 0) state.WriteInt32Varint(6, tmp6);
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::System.Collections.Generic.KeyValuePair<int, string>>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::System.Collections.Generic.KeyValuePair<int, string> global::ProtoBuf.Serializers.ISerializer<global::System.Collections.Generic.KeyValuePair<int, string>>.Read(ref global::ProtoBuf.ProtoReader.State state, global::System.Collections.Generic.KeyValuePair<int, string> value)
        {
            int arg1 = default;
            string arg2 = default;
            arg1 = value.Key;
            arg2 = value.Value;
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        arg1 = state.ReadInt32();
                        break;
                    }
                    case 2:
                    {
                        var tmp2 = state.ReadString();
                        if (tmp2 != null) arg2 = tmp2;
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            value = new global::System.Collections.Generic.KeyValuePair<int, string>(arg1, arg2);
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::System.Collections.Generic.KeyValuePair<int, string>>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::System.Collections.Generic.KeyValuePair<int, string> value)
        {
            var tmp1 = value.Key;
            state.WriteInt32Varint(1, tmp1);
            var tmp2 = value.Value;
            state.WriteString(2, tmp2);
        }
    }
}
