// ---- AotFixtures.BadLevel.BadLevelModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591

namespace AotFixtures.BadLevel;

partial class BadLevelModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected BadLevelModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static BadLevelModel Instance { get; } = new BadLevelModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.BadLevel.GoodLevel>
    {
        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.BadLevel.GoodLevel>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.BadLevel.GoodLevel global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.BadLevel.GoodLevel>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.BadLevel.GoodLevel value)
        {
            value ??= new global::AotFixtures.BadLevel.GoodLevel();
            int field;
            while ((field = state.ReadFieldHeader()) > 0)
            {
                switch (field)
                {
                    case 1:
                    {
                        value.Value = state.ReadInt32();
                        break;
                    }
                    default:
                        state.SkipField();
                        break;
                }
            }
            return value;
        }

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.BadLevel.GoodLevel>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.BadLevel.GoodLevel value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Value;
            if (tmp1 != 0) state.WriteInt32Varint(1, tmp1);
        }
    }
}
