// ---- AotFixtures.MapUnsupported.MapUnsupportedModel.ProtoModel.g.cs ----
// <auto-generated/>
#nullable disable
#pragma warning disable CS1591
#pragma warning disable PBN9002

namespace AotFixtures.MapUnsupported;

partial class MapUnsupportedModel
{
    /// <summary>Use <see cref="Instance"/>; a <c>TypeModel</c> is a cache, and is intended to be shared rather than constructed per use.</summary>
    protected MapUnsupportedModel() { }

    /// <summary>A shared instance of this model; a <c>TypeModel</c> is thread-safe and is intended to be reused.</summary>
    public static MapUnsupportedModel Instance { get; } = new MapUnsupportedModel();

    protected sealed override global::ProtoBuf.Serializers.ISerializer<T> GetSerializer<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicFields | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicMethods | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicNestedTypes | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicNestedTypes)] T>()
        => global::ProtoBuf.Serializers.SerializerCache.Get<ProtoBufGeneratedServices, T>();

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.MapUnsupported.EnumKey value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.MapUnsupported.EnumKey>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.MapUnsupported.EnumKey value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.MapUnsupported.EnumKey>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.MapUnsupported.EnumValue value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.MapUnsupported.EnumValue>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.MapUnsupported.EnumValue value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.MapUnsupported.EnumValue>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.MapUnsupported.MappedEnum value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.MapUnsupported.MappedEnum>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.MapUnsupported.MappedEnum value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.MapUnsupported.MappedEnum>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.IO.Stream destination, global::AotFixtures.MapUnsupported.RepeatedValue value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.MapUnsupported.RepeatedValue>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    /// <summary>Serializes the supplied value.</summary>
    /// <remarks>Prefer this to the generic <c>Serialize&lt;T&gt;</c>: it resolves the serializer at compile time rather than per call.</remarks>
    public long Serialize(global::System.Buffers.IBufferWriter<byte> destination, global::AotFixtures.MapUnsupported.RepeatedValue value, object userState = null)
    {
        var state = global::ProtoBuf.ProtoWriter.State.Create(destination, this, userState);
        try
        {
            if (value is null) return 0;
            long before = state.Position64;
            GetSerializer<global::AotFixtures.MapUnsupported.RepeatedValue>().Write(ref state, value);
            state.Close();
            return state.Position64 - before;
        }
        catch
        {
            state.Abandon();
            throw;
        }
        finally
        {
            state.Dispose();
        }
    }

    private sealed class ProtoBufGeneratedServices
        : global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.EnumKey>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.EnumValue>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.MappedEnum>
        , global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.RepeatedValue>
        , global::ProtoBuf.Serializers.ISerializerProxy<global::AotFixtures.MapUnsupported.Shade>
        , global::ProtoBuf.Serializers.ISerializerProxy<global::AotFixtures.MapUnsupported.Shade?>
        , global::ProtoBuf.Serializers.ISerializerProxy<global::System.Collections.Generic.List<int>>
    {
        private static readonly ProtoBufGeneratedServices Self = new();

        private static readonly ProtoBufGeneratedServices s_default = new ProtoBufGeneratedServices();

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.EnumKey>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.MapUnsupported.EnumKey global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.EnumKey>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.MapUnsupported.EnumKey value)
            => RawRead_AotFixtures_MapUnsupported_EnumKey(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.EnumKey>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.MapUnsupported.EnumKey value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Value;
            if (tmp1 != null)
            {
                global::ProtoBuf.Serializers.MapSerializer.CreateDictionary<global::AotFixtures.MapUnsupported.Shade, int>().WriteMap(ref state, 1, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp1, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint);
            }
        }

        private static global::AotFixtures.MapUnsupported.EnumKey RawRead_AotFixtures_MapUnsupported_EnumKey(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.MapUnsupported.EnumKey value)
        {
            value ??= new global::AotFixtures.MapUnsupported.EnumKey();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 2:  // Value, field 1, map entry run
                    {
                        value.Value ??= new global::System.Collections.Generic.Dictionary<global::AotFixtures.MapUnsupported.Shade, int>();
                        var last = tag;
                        do
                        {
                            var scope = state.PushScope(last);
                            global::AotFixtures.MapUnsupported.Shade k1 = default;
                            int v1 = default;
                            uint etag1 = state.ReadRawTag();
                            while (etag1 != 0)
                            {
                                switch (etag1)
                                {
                                    case (1 << 3) | 0:  // key, varint
                                        k1 = (global::AotFixtures.MapUnsupported.Shade)(unchecked((int)state.ReadRawVarint32()));
                                        break;
                                    case (1 << 3) | 5:  // key, fixed32
                                        k1 = (global::AotFixtures.MapUnsupported.Shade)(unchecked((int)state.ReadRawFixed32()));
                                        break;
                                    case (1 << 3) | 1:  // key, fixed64
                                        k1 = (global::AotFixtures.MapUnsupported.Shade)(checked((int)unchecked((long)state.ReadRawFixed64())));
                                        break;
                                    case (2 << 3) | 0:  // value, varint
                                        v1 = unchecked((int)state.ReadRawVarint32());
                                        break;
                                    case (2 << 3) | 5:  // value, fixed32
                                        v1 = unchecked((int)state.ReadRawFixed32());
                                        break;
                                    case (2 << 3) | 1:  // value, fixed64
                                        v1 = checked((int)unchecked((long)state.ReadRawFixed64()));
                                        break;
                                    default:
                                        if (state.IsScopeEnd(etag1)) goto entryDone1;
                                        if ((etag1 >> 3) is 1 or 2) state.ThrowUnexpectedWireType(etag1);
                                        state.SkipTag(etag1);
                                        break;
                                }
                                etag1 = state.ReadRawTag();
                            }
                            entryDone1:
                            state.PopScope(scope);
                            value.Value[k1] = v1;
                        } while ((tag = state.ReadRawTag()) == last);
                        continue;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.EnumValue>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.MapUnsupported.EnumValue global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.EnumValue>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.MapUnsupported.EnumValue value)
            => RawRead_AotFixtures_MapUnsupported_EnumValue(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.EnumValue>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.MapUnsupported.EnumValue value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Value;
            if (tmp1 != null)
            {
                global::ProtoBuf.Serializers.MapSerializer.CreateDictionary<int, global::AotFixtures.MapUnsupported.Shade>().WriteMap(ref state, 1, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp1, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint);
            }
        }

        private static global::AotFixtures.MapUnsupported.EnumValue RawRead_AotFixtures_MapUnsupported_EnumValue(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.MapUnsupported.EnumValue value)
        {
            value ??= new global::AotFixtures.MapUnsupported.EnumValue();
            uint tag = state.ReadRawTag();
            while (tag != 0)
            {
                switch (tag)
                {
                    case (1 << 3) | 2:  // Value, field 1, map entry run
                    {
                        value.Value ??= new global::System.Collections.Generic.Dictionary<int, global::AotFixtures.MapUnsupported.Shade>();
                        var last = tag;
                        do
                        {
                            var scope = state.PushScope(last);
                            int k1 = default;
                            global::AotFixtures.MapUnsupported.Shade v1 = default;
                            uint etag1 = state.ReadRawTag();
                            while (etag1 != 0)
                            {
                                switch (etag1)
                                {
                                    case (1 << 3) | 0:  // key, varint
                                        k1 = unchecked((int)state.ReadRawVarint32());
                                        break;
                                    case (1 << 3) | 5:  // key, fixed32
                                        k1 = unchecked((int)state.ReadRawFixed32());
                                        break;
                                    case (1 << 3) | 1:  // key, fixed64
                                        k1 = checked((int)unchecked((long)state.ReadRawFixed64()));
                                        break;
                                    case (2 << 3) | 0:  // value, varint
                                        v1 = (global::AotFixtures.MapUnsupported.Shade)(unchecked((int)state.ReadRawVarint32()));
                                        break;
                                    case (2 << 3) | 5:  // value, fixed32
                                        v1 = (global::AotFixtures.MapUnsupported.Shade)(unchecked((int)state.ReadRawFixed32()));
                                        break;
                                    case (2 << 3) | 1:  // value, fixed64
                                        v1 = (global::AotFixtures.MapUnsupported.Shade)(checked((int)unchecked((long)state.ReadRawFixed64())));
                                        break;
                                    default:
                                        if (state.IsScopeEnd(etag1)) goto entryDone1;
                                        if ((etag1 >> 3) is 1 or 2) state.ThrowUnexpectedWireType(etag1);
                                        state.SkipTag(etag1);
                                        break;
                                }
                                etag1 = state.ReadRawTag();
                            }
                            entryDone1:
                            state.PopScope(scope);
                            value.Value[k1] = v1;
                        } while ((tag = state.ReadRawTag()) == last);
                        continue;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTag();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.MappedEnum>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.MapUnsupported.MappedEnum global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.MappedEnum>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.MapUnsupported.MappedEnum value)
            => RawRead_AotFixtures_MapUnsupported_MappedEnum(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.MappedEnum>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.MapUnsupported.MappedEnum value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Value;
            if (tmp1 != null)
            {
                global::ProtoBuf.Serializers.MapSerializer.CreateDictionary<global::AotFixtures.MapUnsupported.Shade, int>().WriteMap(ref state, 1, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp1, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeSignedVarint, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint);
            }
        }

        private static global::AotFixtures.MapUnsupported.MappedEnum RawRead_AotFixtures_MapUnsupported_MappedEnum(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.MapUnsupported.MappedEnum value)
        {
            value ??= new global::AotFixtures.MapUnsupported.MappedEnum();
            uint tag = state.ReadRawTagOrPending();
            while (tag != 0)
            {
                switch (tag)
                {
                    // raw read pass: legacy-mode - member Value: map with per-side format
                    case (1 << 3) | 0:
                    case (1 << 3) | 1:
                    case (1 << 3) | 2:  // Value, field 1
                    case (1 << 3) | 3:
                    case (1 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp1 = value.Value;
                        tmp1 = global::ProtoBuf.Serializers.MapSerializer.CreateDictionary<global::AotFixtures.MapUnsupported.Shade, int>().ReadMap(ref state, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled, tmp1, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeSignedVarint, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint);
                        if (tmp1 != null) value.Value = tmp1;
                        break;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTagOrPending();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1;
        }

        global::ProtoBuf.Serializers.SerializerFeatures global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.RepeatedValue>.Features
            => global::ProtoBuf.Serializers.SerializerFeatures.CategoryMessage | global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString;

        global::AotFixtures.MapUnsupported.RepeatedValue global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.RepeatedValue>.Read(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.MapUnsupported.RepeatedValue value)
            => RawRead_AotFixtures_MapUnsupported_RepeatedValue(ref state, value);

        void global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.RepeatedValue>.Write(ref global::ProtoBuf.ProtoWriter.State state, global::AotFixtures.MapUnsupported.RepeatedValue value)
        {
            global::ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(value);
            var tmp1 = value.Value;
            if (tmp1 != null)
            {
                global::ProtoBuf.Serializers.MapSerializer.CreateDictionary<int, global::System.Collections.Generic.List<int>>().WriteMap(ref state, 1, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled | global::ProtoBuf.Serializers.SerializerFeatures.OptionFailOnDuplicateKey, tmp1, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint);
            }
        }

        private static global::AotFixtures.MapUnsupported.RepeatedValue RawRead_AotFixtures_MapUnsupported_RepeatedValue(ref global::ProtoBuf.ProtoReader.State state, global::AotFixtures.MapUnsupported.RepeatedValue value)
        {
            value ??= new global::AotFixtures.MapUnsupported.RepeatedValue();
            uint tag = state.ReadRawTagOrPending();
            while (tag != 0)
            {
                switch (tag)
                {
                    // raw read pass: legacy-mode - member Value: map with repeated value
                    case (1 << 3) | 0:
                    case (1 << 3) | 1:
                    case (1 << 3) | 2:  // Value, field 1
                    case (1 << 3) | 3:
                    case (1 << 3) | 5:
                    {
                        state.StashTag(tag);
                        var tmp1 = value.Value;
                        tmp1 = global::ProtoBuf.Serializers.MapSerializer.CreateDictionary<int, global::System.Collections.Generic.List<int>>().ReadMap(ref state, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeString | global::ProtoBuf.Serializers.SerializerFeatures.OptionPackedDisabled | global::ProtoBuf.Serializers.SerializerFeatures.OptionFailOnDuplicateKey, tmp1, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint, global::ProtoBuf.Serializers.SerializerFeatures.WireTypeVarint);
                        if (tmp1 != null) value.Value = tmp1;
                        break;
                    }
                    default:
                        if (state.IsScopeEnd(tag)) return value;
                        if (IsKnownField(tag)) state.ThrowUnexpectedWireType(tag);
                        state.SkipTag(tag);
                        break;
                }
                tag = state.ReadRawTagOrPending();
            }
            return value;

            static bool IsKnownField(uint tag) => (tag >> 3) is 1;
        }

        global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.Shade> global::ProtoBuf.Serializers.ISerializerProxy<global::AotFixtures.MapUnsupported.Shade>.Serializer
            => global::ProtoBuf.Serializers.EnumSerializer.CreateInt32<global::AotFixtures.MapUnsupported.Shade>();

        global::ProtoBuf.Serializers.ISerializer<global::AotFixtures.MapUnsupported.Shade?> global::ProtoBuf.Serializers.ISerializerProxy<global::AotFixtures.MapUnsupported.Shade?>.Serializer
            => global::ProtoBuf.Serializers.EnumSerializer.CreateInt32<global::AotFixtures.MapUnsupported.Shade>();

        global::ProtoBuf.Serializers.ISerializer<global::System.Collections.Generic.List<int>> global::ProtoBuf.Serializers.ISerializerProxy<global::System.Collections.Generic.List<int>>.Serializer
            => global::ProtoBuf.Serializers.RepeatedSerializer.CreateList<int>();
    }
}
